// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Copyright 2026 Oxide Computer Company

//! Embeds the third-party payload into the binary.
//!
//! The media carries virtio guest drivers, Win32-OpenSSH and three EFI binaries — about
//! 11 MB, none of it ours, all of it fetched by `tools/fetch-payload.sh` against pinned
//! SHA-256 checksums and never committed. Embedding it is what makes a release artifact a
//! single file: someone who downloads the app has no repository to walk up into.
//!
//! Three behaviours worth knowing about:
//!
//! - **A missing `assets/` is not an error.** It emits an empty table so `cargo test`
//!   still runs on a fresh clone with no download. The tests do not need the payload, and
//!   making them need it would trade a real property for a theoretical one.
//! - **`OXWIN_REQUIRE_PAYLOAD=1` turns that into a hard failure.** CI sets it for release
//!   builds, so an empty table can never be shipped as if it were a real one.
//! - **What is embedded is cross-checked against `payload-manifest.json`.** Provenance is
//!   enforced at download time by the checksums in `fetch-payload.sh`; this catches the
//!   different failure of a partial or stale `assets/` — a driver the manifest lists and
//!   the tree does not have, or one whose size has changed.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env("CARGO_MANIFEST_DIR"));
    // <repo>/crates/oxwin-core -> <repo>/assets. Overridable so a payload can be tried
    // without moving it into place.
    let assets = match std::env::var_os("OXWIN_ASSETS_DIR") {
        Some(dir) => PathBuf::from(dir),
        None => manifest_dir
            .ancestors()
            .nth(2)
            .expect("crates/<crate> has a grandparent")
            .join("assets"),
    };
    println!("cargo::rerun-if-env-changed=OXWIN_ASSETS_DIR");
    println!("cargo::rerun-if-env-changed=OXWIN_REQUIRE_PAYLOAD");
    println!("cargo::rerun-if-changed={}", assets.display());

    let required = std::env::var("OXWIN_REQUIRE_PAYLOAD").as_deref() == Ok("1");
    let out = PathBuf::from(env("OUT_DIR")).join("payload.rs");

    if !assets.join("payload-manifest.json").is_file() {
        if required {
            panic!(
                "OXWIN_REQUIRE_PAYLOAD=1 but {} has no payload-manifest.json.\n\
                 Run ./tools/fetch-payload.sh first.",
                assets.display()
            );
        }
        println!(
            "cargo::warning=no payload in {} — building without an embedded \
             payload. Run ./tools/fetch-payload.sh to embed one.",
            assets.display()
        );
        std::fs::write(&out, empty_table()).expect("writing payload.rs");
        return;
    }

    let mut files = BTreeMap::new();
    collect(&assets, &assets, &mut files);
    check_against_manifest(&assets, &files);

    let mut src = String::from(
        "/// Every file under `assets/`, keyed by its path relative to that directory.\n\
         /// Generated by build.rs. Sorted, so the order is stable across hosts.\n\
         pub static EMBEDDED: &[(&str, &[u8])] = &[\n",
    );
    for (rel, abs) in &files {
        // include_bytes! resolves relative to this file, so the path must be absolute.
        src += &format!("    ({:?}, include_bytes!({:?})),\n", rel, abs);
    }
    src += "];\n\n";
    src += &format!(
        "/// Fingerprint of the embedded payload. Reported by `oxwin doctor`, so that two\n\
         /// artifacts built on different platforms can be shown to carry the same bytes.\n\
         pub static FINGERPRINT: &str = {:?};\n",
        fingerprint(&files)
    );
    std::fs::write(&out, src).expect("writing payload.rs");
    println!(
        "cargo::warning=embedded {} payload files from {}",
        files.len(),
        assets.display()
    );
}

fn empty_table() -> String {
    String::from(
        "/// No payload was present at build time. The engine turns this into an error\n\
         /// naming tools/fetch-payload.sh rather than producing a broken image.\n\
         pub static EMBEDDED: &[(&str, &[u8])] = &[];\n\n\
         pub static FINGERPRINT: &str = \"none\";\n",
    )
}

fn env(key: &str) -> String {
    std::env::var(key).unwrap_or_else(|_| panic!("{key} is not set"))
}

/// Every file under `dir`, keyed by its slash-separated path relative to `root`.
fn collect(root: &Path, dir: &Path, out: &mut BTreeMap<String, PathBuf>) {
    let entries = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("{}: {e}", dir.display()));
    for entry in entries {
        let path = entry.expect("directory entry").path();
        let name = path.file_name().unwrap_or_default().to_string_lossy();
        // Finder droppings are not payload and differ between machines, which would put
        // them in the fingerprint.
        if name == ".DS_Store" {
            continue;
        }
        if path.is_dir() {
            collect(root, &path, out);
        } else {
            let rel = path
                .strip_prefix(root)
                .expect("under root")
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.insert(rel, path);
        }
    }
}

/// Cross-check the tree against the manifest. Scanned rather than parsed with serde: a
/// build script that pulls in a dependency tree to read four fields is a poor trade, and
/// the manifest is written by `fetch-payload.sh` two directories away.
fn check_against_manifest(assets: &Path, files: &BTreeMap<String, PathBuf>) {
    let text = std::fs::read_to_string(assets.join("payload-manifest.json"))
        .expect("reading payload-manifest.json");
    let mut missing = Vec::new();
    let mut wrong_size = Vec::new();

    // Every "path": "..." the manifest names must exist, and every "size": N that
    // follows one must match. The manifest is machine-generated with a fixed shape.
    let mut pending: Option<String> = None;
    for raw in text.lines() {
        let line = raw.trim();
        if let Some(value) = field(line, "\"path\":") {
            let rel =
                value.strip_prefix("assets/").unwrap_or(&value).to_string();
            match files.get(&rel) {
                None => missing.push(rel),
                Some(_) => pending = Some(rel),
            }
        } else if let Some(value) = field(line, "\"size\":") {
            if let (Some(rel), Ok(want)) =
                (pending.take(), value.parse::<u64>())
            {
                let got = files[&rel].metadata().expect("stat").len();
                if got != want {
                    wrong_size
                        .push(format!("{rel}: manifest {want}, found {got}"));
                }
            }
        } else if let Some(value) = field(line, "\"openSsh\":") {
            let rel =
                value.strip_prefix("assets/").unwrap_or(&value).to_string();
            if !files.contains_key(&rel) {
                missing.push(rel);
            }
        }
    }

    // The three the boot partition cannot be built without. Named explicitly because a
    // manifest that has lost its `efi` block would otherwise pass silently.
    for name in ["shellx64.efi", "uefintfs.efi", "exfat_x64.efi"] {
        let rel = format!("efi/{name}");
        if !files.contains_key(&rel) {
            missing.push(rel);
        }
    }

    if !missing.is_empty() || !wrong_size.is_empty() {
        panic!(
            "the payload in {} does not match its manifest — rerun \
             ./tools/fetch-payload.sh\n  missing: {}\n  wrong size: {}",
            assets.display(),
            if missing.is_empty() { "none".into() } else { missing.join(", ") },
            if wrong_size.is_empty() {
                "none".into()
            } else {
                wrong_size.join(", ")
            }
        );
    }
}

/// The value of a `"key": value` line, unquoted and stripped of a trailing comma.
fn field(line: &str, key: &str) -> Option<String> {
    let rest = line.strip_prefix(key)?.trim();
    let rest = rest.strip_suffix(',').unwrap_or(rest);
    Some(rest.trim_matches('"').to_string())
}

/// FNV-1a over the sorted path, length and contents of every file.
///
/// Not a cryptographic digest and not doing a cryptographic job: the bytes were already
/// SHA-256 verified when `fetch-payload.sh` downloaded them. This exists so that "did
/// every platform artifact embed the same payload" is one string comparison.
fn fingerprint(files: &BTreeMap<String, PathBuf>) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    let mut feed = |bytes: &[u8]| {
        for b in bytes {
            hash ^= *b as u64;
            hash = hash.wrapping_mul(0x100_0000_01b3);
        }
    };
    for (rel, abs) in files {
        let data = std::fs::read(abs).expect("reading payload file");
        feed(rel.as_bytes());
        feed(&(data.len() as u64).to_le_bytes());
        feed(&data);
    }
    format!("{hash:016x}")
}
