// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Copyright 2026 Oxide Computer Company

//! The guest bootstrap script.
//!
//! PowerShell that runs as SYSTEM during the `specialize` pass, before any user logs
//! on. The answer file does most of the work, but three things cannot be expressed in
//! it at all:
//!
//! - **Drivers, as a second attempt.** `DriverPaths` should have handled them, but a
//!   driver missed there leaves the guest with no network and no way to fix it.
//! - **OpenSSH.** Server 2022 has it only as a Feature on Demand, and
//!   `Add-WindowsCapability` needs Windows Update or an FoD source — an air-gapped rack
//!   has neither. So the payload rides along on the media, and its Authenticode
//!   signature is checked on the machine itself before anything is installed.
//! - **The ESP fallback bootloader.** Windows registers itself in NVRAM and does not
//!   reliably create `\EFI\BOOT\BOOTX64.EFI`. An Oxide instance drives boot order from
//!   its configured `boot_disk` and does not fall through, so without that path
//!   populated the installed system drops to the EFI shell.
//!
//! Byte-compared against the committed goldens in `testdata/bootstrap/`, which were
//! generated by the JavaScript builder this was ported from; see the tests at the
//! bottom.

use crate::unattend::Config;
use anyhow::Result;

/// Append a block of literal lines. Split on LF so a multi-line literal in the source
/// reads the way it will in the guest; the CRLF join happens once, at the end.
fn push(lines: &mut Vec<String>, block: &str) {
    for line in block.split('\n') {
        lines.push(line.to_string());
    }
}

/// Build the script. CRLF throughout, because it is read by PowerShell on Windows off
/// a volume that may be mounted read-only.
pub fn build(config: &Config) -> Result<String> {
    let keys: Vec<&str> = config
        .ssh_keys
        .iter()
        .map(|k| k.as_str())
        .filter(|k| !k.trim().is_empty())
        .collect();

    let mut lines: Vec<String> = Vec::new();
    push(
        &mut lines,
        r#"# Generated by the Oxide Windows image builder. Runs as SYSTEM in the
# specialize pass, before any user logs on.
$ErrorActionPreference = 'Stop'
$src = Split-Path -Parent $MyInvocation.MyCommand.Path"#,
    );
    // TrimEnd because for media laid out as <drive>:\setup\bootstrap.ps1 the parent of
    // the parent is "E:\" — already ending in a separator. "$root\drivers" then yields
    // "E:\\drivers", which Test-Path accepts but pnputil does not: it fails to expand
    // the *.inf wildcard and exits 2, so no drivers install and the guest comes up with
    // no NIC. Silent apart from that exit code.
    push(
        &mut lines,
        r#"$root = (Split-Path -Parent $src).TrimEnd('\')
"#,
    );
    push(
        &mut lines,
        r#"# Log to the installer media as well as the system drive. The media is the only
# copy anyone can read without getting into the guest: on the rack the console is
# serial-only, and off the rack a Windows NTFS volume is awkward to read (macOS
# 26 dropped NTFS support entirely). Detach the installer disk afterwards and the
# log is right there on a volume every OS can mount.
$log = "$env:SystemDrive\oxide-bootstrap.log"
$mediaLog = "$root\oxide-bootstrap.log"
function Log($m) {
  $line = "$(Get-Date -Format o)  $m"
  $line | Tee-Object -FilePath $log -Append
  # Best effort: the media may be read-only or already gone.
  try { Add-Content -LiteralPath $mediaLog -Value $line -ErrorAction Stop } catch {}
}

Log "Oxide guest bootstrap starting"
"#,
    );

    if config.inject_drivers {
        push(
            &mut lines,
            r#"# Belt and braces: the DriverPaths in the unattend should already have
# handled these, but a driver missed there leaves the guest unreachable.
if (Test-Path "$root\drivers") {
  Log "Installing drivers from $root\drivers"
  $out = & pnputil.exe /add-driver "$root\drivers\*.inf" /subdirs /install 2>&1
  Log "pnputil exit $LASTEXITCODE"
  # Keep the output when it fails. A bare exit code told us nothing, and
  # "no NIC" is expensive to diagnose after the fact.
  if ($LASTEXITCODE -ne 0) { $out | ForEach-Object { Log "  pnputil: $_" } }
  $nic = Get-PnpDevice -Class Net -ErrorAction SilentlyContinue | Where-Object { $_.FriendlyName -match 'VirtIO|Red Hat' }
  Log "virtio NIC present: $([bool]$nic)"
}
"#,
        );
    }

    if config.enable_ssh {
        push(
            &mut lines,
            r#"# Server 2025 ships OpenSSH Server preinstalled. Server 2022 and Windows 11
# have it only as a Feature on Demand, and Add-WindowsCapability needs
# Windows Update or an FoD source - an air-gapped rack has neither, and the
# payload is not on the install media. So: use whatever is already present,
# and fall back to the copy riding along on this disk.
if (-not (Get-Service -Name sshd -ErrorAction SilentlyContinue)) {
  $inbox = "$env:SystemRoot\System32\OpenSSH\sshd.exe"
  $zip = Get-ChildItem -Path "$root\openssh" -Filter 'OpenSSH-Win64*.zip' -ErrorAction SilentlyContinue | Select-Object -First 1
  if (Test-Path $inbox) {
    # sshd.exe here means the Server component, not just the inbox client.
    Log "Registering preinstalled OpenSSH Server"
    & "$env:SystemRoot\System32\OpenSSH\install-sshd.ps1" 2>&1 | Out-Null
  } elseif ($zip) {
    Log "Installing OpenSSH from $($zip.Name)"
    $dest = "$env:ProgramFiles\OpenSSH"
    Expand-Archive -Path $zip.FullName -DestinationPath $env:TEMP\openssh -Force

    # Verify provenance on the machine itself before installing anything.
    # The bundled build is Microsoft's own port (PowerShell/Win32-OpenSSH),
    # Authenticode-signed by Microsoft Corporation off their ESRP pipeline.
    # fetch-payload.sh pins a SHA-256, but that only proves we got the bytes
    # we expected - it says nothing about who signed them. Checking the
    # signature here is free, needs no tooling, and fails closed.
    $stage = "$env:TEMP\openssh\OpenSSH-Win64"
    $unsigned = @()
    foreach ($exe in Get-ChildItem -Path $stage -Filter *.exe) {
      $sig = Get-AuthenticodeSignature -FilePath $exe.FullName
      if ($sig.Status -ne 'Valid' -or $sig.SignerCertificate.Subject -notmatch 'O=Microsoft Corporation') {
        $unsigned += "$($exe.Name) [$($sig.Status)] $($sig.SignerCertificate.Subject)"
      }
    }
    if ($unsigned.Count -gt 0) {
      Log "REFUSING to install OpenSSH: not signed by Microsoft"
      foreach ($u in $unsigned) { Log "  $u" }
    } else {
      Log "OpenSSH payload verified: signed by Microsoft Corporation"
      New-Item -ItemType Directory -Force -Path $dest | Out-Null
      Copy-Item -Path "$stage\*" -Destination $dest -Recurse -Force
      & powershell.exe -ExecutionPolicy Bypass -File "$dest\install-sshd.ps1" 2>&1 | Out-Null
      Log "install-sshd exit $LASTEXITCODE"
    }
  } else {
    Log "WARNING: no OpenSSH present and none on the answer disk"
  }
}

if (Get-Service -Name sshd -ErrorAction SilentlyContinue) {
  Set-Service -Name sshd -StartupType Automatic
  Set-Service -Name ssh-agent -StartupType Automatic -ErrorAction SilentlyContinue
  New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' `
    -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22 -ErrorAction SilentlyContinue | Out-Null

  # Make PowerShell the login shell rather than cmd.
  New-ItemProperty -Path 'HKLM:\SOFTWARE\OpenSSH' -Name DefaultShell `
    -Value "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force | Out-Null
"#,
        );

        if !keys.is_empty() {
            // administrators_authorized_keys covers every member of Administrators, so
            // this works even though the local account is not created until oobeSystem.
            push(
                &mut lines,
                r#"  # sshd ignores this file unless Administrators and SYSTEM are the only
  # principals with access, so the inherited ACL has to go.
  $akFile = "$env:ProgramData\ssh\administrators_authorized_keys"
  New-Item -ItemType Directory -Force -Path "$env:ProgramData\ssh" | Out-Null"#,
            );
            // One `lines` element holding LF-separated text. The surrounding lines
            // are joined with CRLF, so this array block is the one place in the script
            // with bare LFs — preserved because it is what the goldens pin, and
            // PowerShell does not
            // care either way.
            let literals: Vec<String> = keys
                .iter()
                .map(|k| format!("'{}'", k.replace('\'', "''").trim()))
                .collect();
            lines.push(format!(
                "  $keys = @(\n    {}\n  )",
                literals.join(",\n    ")
            ));
            push(
                &mut lines,
                r#"  Set-Content -Path $akFile -Value $keys -Encoding ascii
  $acl = Get-Acl $akFile
  $acl.SetAccessRuleProtection($true, $false)
  $acl.Access | ForEach-Object { $acl.RemoveAccessRule($_) | Out-Null }
  foreach ($who in 'BUILTIN\Administrators', 'NT AUTHORITY\SYSTEM') {
    $acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
      $who, 'FullControl', 'None', 'None', 'Allow'))) | Out-Null
  }
  Set-Acl -Path $akFile -AclObject $acl
  Log "Wrote $($keys.Count) authorized key(s)""#,
            );
        }

        push(
            &mut lines,
            r#"  Start-Service sshd
  Log "sshd started"
} else {
  Log "WARNING: sshd service not registered; SSH is not configured"
}
"#,
        );
    }

    // Make the installed OS bootable via the removable-media fallback path.
    //
    // Windows registers itself with an NVRAM entry pointing at
    // \EFI\Microsoft\Boot\bootmgfw.efi and does not reliably create
    // \EFI\BOOT\BOOTX64.EFI. That is fine where firmware honours guest NVRAM (QEMU
    // does), but an Oxide instance drives boot order from its configured boot_disk —
    // proven on real hardware: pointing boot_disk at a disk with no bootloader at the
    // fallback path drops to the EFI shell rather than trying anything else.
    //
    // Copying bootmgfw.efi into place costs a few hundred KiB and makes the target disk
    // bootable no matter which path the firmware looks at.
    push(
        &mut lines,
        r#"# See docs/windows-install-status.md: Oxide boots the configured boot_disk and
# does not fall through, so the ESP needs the fallback path populated.
try {
  $esp = (Get-Partition | Where-Object { $_.GptType -eq '{c12a7328-f81f-11d2-ba4b-00a0c93ec93b}' } | Select-Object -First 1)
  if ($esp) {
    $letter = 'S'
    if (-not $esp.DriveLetter) { $esp | Set-Partition -NewDriveLetter $letter } else { $letter = $esp.DriveLetter }
    $src2 = "${letter}:\EFI\Microsoft\Boot\bootmgfw.efi"
    $dstDir = "${letter}:\EFI\BOOT"
    if ((Test-Path $src2) -and -not (Test-Path "$dstDir\BOOTX64.EFI")) {
      New-Item -ItemType Directory -Force -Path $dstDir | Out-Null
      Copy-Item -Path $src2 -Destination "$dstDir\BOOTX64.EFI" -Force
      Log "ESP fallback bootloader installed at \EFI\BOOT\BOOTX64.EFI"
    } else {
      Log "ESP fallback bootloader: already present or bootmgfw missing"
    }
  } else { Log "WARNING: no EFI system partition found" }
} catch { Log "WARNING: ESP fallback copy failed: $_" }

Log "Oxide guest bootstrap complete""#,
    );

    // A golden image has to be generalized, or every clone shares one name and one SID.
    //
    // **The sysprep cannot happen at this point in the script.** Everything here runs in
    // the `specialize` pass, which is *before* `oobeSystem`: no account exists yet, OOBE
    // has not run, and the machine is not a finished install. Generalizing here would
    // seal a half-built one.
    //
    // it also cant hang off `FirstLogonCommands`, which fires only on an interactive logon
    // and so would mean turning autologon on, trading a cloning problem for a console
    // session nobody is can see.
    //
    // So what this block emits is only the *registration*: a SYSTEM task that fires at
    // every startup, does nothing while Setup is still running, and generalizes on the
    // first boot where Setup reports itself finished.
    if config.generalize {
        // Its own copy of the answer file, with the password still in it. See
        // `unattend::build_sysprep`: the copy Windows caches has the password replaced
        // by `*SENSITIVE*DATA*DELETED*`, so a sysprep that falls back to it leaves the
        // clone stuck at the out-of-box wizard.
        let sysprep_xml = crate::unattend::build_sysprep(config)?;
        push(
            &mut lines,
            r#"
# Golden image: generalize after the install finishes, so this disk can be cloned.
$genDir = "$env:SystemRoot\Setup\Scripts"
$gen = "$genDir\oxide-generalize.ps1"
$unattend = "$env:SystemRoot\System32\Sysprep\oxide-unattend.xml"
New-Item -ItemType Directory -Force -Path $genDir | Out-Null"#,
        );
        // The answer file, verbatim, inside a single-quoted here-string so nothing in it
        // is expanded by PowerShell on the way to disk.
        push(
            &mut lines,
            "Set-Content -LiteralPath $unattend -Encoding UTF8 -Value @'",
        );
        push(&mut lines, sysprep_xml.trim_end());
        push(&mut lines, "'@");
        push(
            &mut lines,
            r#"# A single-quoted here-string: nothing below is expanded now. It is expanded on the
# machine, on a later boot, by the task registered underneath it.
Set-Content -LiteralPath $gen -Encoding ASCII -Value @'
$ErrorActionPreference = 'Continue'
$log = "$env:SystemDrive\oxide-bootstrap.log"
function GLog($m) {
  "$(Get-Date -Format o)  generalize: $m" | Tee-Object -FilePath $log -Append
}
# Written before sysprep runs, so it is captured into the image. A clone therefore
# finds it and does nothing. Without this every clone would generalize itself and
# shut down on first boot, which is a fleet that turns itself off.
$marker = "$env:SystemDrive\oxide-generalized.txt"
if (Test-Path $marker) {
  GLog "already generalized; this is a clone, nothing to do"
  Unregister-ScheduledTask -TaskName 'OxideGeneralize' -Confirm:$false -ErrorAction SilentlyContinue
  exit 0
}
# The task fires at every startup, including boots where Setup is still working. Do
# nothing until it has finished and let the next boot try again.
$setup = Get-ItemProperty -Path 'HKLM:\SYSTEM\Setup' -ErrorAction SilentlyContinue
if ($setup.SystemSetupInProgress -ne 0 -or $setup.OOBEInProgress -ne 0) {
  GLog "Setup still in progress; waiting for the next boot"
  exit 0
}
$unattend = "$env:SystemRoot\System32\Sysprep\oxide-unattend.xml"
if (-not (Test-Path $unattend)) {
  GLog "WARNING: $unattend is missing. Sysprep would fall back to the cached answer"
  GLog "file, whose password Windows has already deleted, and the clone would stop at"
  GLog "the out-of-box wizard. Refusing to generalize."
  exit 1
}
GLog "install finished; generalizing for cloning with $unattend"
Set-Content -LiteralPath $marker -Value (Get-Date -Format o)
Unregister-ScheduledTask -TaskName 'OxideGeneralize' -Confirm:$false -ErrorAction SilentlyContinue
& "$env:SystemRoot\System32\Sysprep\sysprep.exe" /generalize /oobe /shutdown /unattend:"$unattend"
$code = $LASTEXITCODE
# Branch on the exit code, NOT on reaching this line. sysprep /shutdown returns
# straight away and Windows powers off a moment later, so everything below runs on
# success too unless it is guarded. Getting that wrong produced an infinite loop on a
# rack: sysprep succeeded, the lines below removed the marker and put the task back,
# and so every subsequent boot generalized the machine and shut it down again.
if ($code -eq 0) {
  GLog "sysprep accepted; the machine is shutting down. Snapshot it once it stops."
  exit 0
}
GLog "sysprep FAILED with exit code $code; see C:\Windows\System32\Sysprep\Panther"
# Only now: undo the marker and put the task back, so a real failure retries rather
# than leaving a machine that looks generalized and is not.
Remove-Item -LiteralPath $marker -Force -ErrorAction SilentlyContinue
$a = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`""
$t = New-ScheduledTaskTrigger -AtStartup
$p = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
Register-ScheduledTask -TaskName 'OxideGeneralize' -Action $a -Trigger $t -Principal $p -Force | Out-Null
'@
# Wrapped, because $ErrorActionPreference is 'Stop' for this script: a failure to
# register the task would otherwise abort the bootstrap without saying why, and the
# machine would come up looking fine and never generalize.
try {
  $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$gen`""
  $trigger = New-ScheduledTaskTrigger -AtStartup
  $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
  Register-ScheduledTask -TaskName 'OxideGeneralize' -Action $action -Trigger $trigger -Principal $principal -Force | Out-Null
  Log "golden image: OxideGeneralize registered; the machine will sysprep and shut down once Setup finishes"
} catch { Log "WARNING: could not register OxideGeneralize, so this image will NOT be generalized: $_" }"#,
        );
    }

    Ok(lines.join("\r\n") + "\r\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::settings::WindowsRelease;
    use crate::unattend::Config;
    use std::path::PathBuf;

    fn base() -> Config {
        Config {
            release: WindowsRelease::Server2022,
            edition: "datacenter".into(),
            computer_name: "win-server-01".into(),
            username: "oxide".into(),
            password: "0xide!230xide!23".into(),
            enable_rdp: true,
            inject_drivers: true,
            enable_serial_console: true,
            target_disk: 1,
            locale: "en-US".into(),
            timezone: "UTC".into(),
            product_key: None,
            auto_logon: false,
            generalize: false,
            verbose_serial: false,
            log_path: None,
            show_ui_on_error: true,
            image_index: Some(4),
            skip_image_install: false,
            install_from: None,
            install_from_letter: None,
            install_from_label: None,
            ssh_keys: Vec::new(),
            enable_ssh: true,
        }
    }

    /// Sysprep must never appear in a build that is not a golden image.
    ///
    /// Generalizing a machine somebody asked to be one specific named machine would
    /// wipe its identity and shut it down on first boot, an unrecoverable surprise, and
    /// exactly the kind of thing a `..base()` slip introduces silently.
    #[test]
    fn only_a_golden_image_generalizes() {
        let named = build(&base()).unwrap();
        assert!(!named.contains("sysprep"), "a named build must not sysprep");
        assert!(!named.contains("OxideGeneralize"));

        let golden = build(&Config { generalize: true, ..base() }).unwrap();
        assert!(golden.contains("sysprep.exe\" /generalize /oobe /shutdown"));
        assert!(golden.contains("OxideGeneralize"));
        // And the guard that stops clones generalizing themselves.
        assert!(
            golden.contains("oxide-generalized.txt"),
            "without the marker every clone would sysprep itself on first boot"
        );
        assert!(
            golden.contains("if (Test-Path $marker)"),
            "the marker must actually be tested, not merely written"
        );
        // The recovery path must be reached by a failing exit code, never merely by
        // execution continuing past sysprep. `sysprep /shutdown` returns immediately on
        // success, so an unguarded `Remove-Item $marker` there un-generalizes the
        // machine and re-arms the task, which on a rack produced a guest that
        // generalized and shut itself down on every single boot.
        assert!(
            golden.contains("$code = $LASTEXITCODE")
                && golden.contains("if ($code -eq 0) {"),
            "the sysprep result must be tested by exit code"
        );
        let after_sysprep = golden
            .split("sysprep.exe\" /generalize")
            .nth(1)
            .expect("the sysprep invocation");
        let success_branch = after_sysprep
            .find("if ($code -eq 0) {")
            .expect("the success branch");
        let undo = after_sysprep
            .find("Remove-Item -LiteralPath $marker")
            .expect("the recovery path");
        assert!(
            success_branch < undo,
            "the success branch must exit before the marker is removed"
        );
    }

    /// The generated PowerShell is written out with -Encoding ASCII, so a stray
    /// non-ASCII character in a comment reaches the guest as a replacement byte.
    #[test]
    fn the_script_is_ascii() {
        for (slug, _, config) in cases() {
            let script = build(&config).unwrap();
            assert!(
                script.is_ascii(),
                "{slug}: non-ASCII in the generated script: {:?}",
                script.chars().filter(|c| !c.is_ascii()).collect::<Vec<_>>()
            );
        }
    }

    /// Report the first differing line, with its number, rather than two blobs.
    fn first_difference(want: &str, got: &str) -> Option<String> {
        let wanted: Vec<&str> = want.split("\r\n").collect();
        let ours: Vec<&str> = got.split("\r\n").collect();
        for (i, (w, o)) in wanted.iter().zip(&ours).enumerate() {
            if w != o {
                return Some(format!(
                    "line {}:\n  expected {w:?}\n  got      {o:?}",
                    i + 1
                ));
            }
        }
        if wanted.len() != ours.len() {
            return Some(format!(
                "line count {} vs {}; first extra: {:?}",
                wanted.len(),
                ours.len(),
                wanted.get(ours.len()).or_else(|| ours.get(wanted.len()))
            ));
        }
        None
    }

    /// Every branch in the generator. The slug names the golden file, the label is
    /// prose for a failure message; see the note in `unattend.rs` on why they are not
    /// the same string.
    fn cases() -> Vec<(&'static str, &'static str, Config)> {
        vec![
            ("defaults", "defaults", base()),
            (
                "no-drivers",
                "no drivers",
                Config { inject_drivers: false, ..base() },
            ),
            ("no-ssh", "no ssh", Config { enable_ssh: false, ..base() }),
            (
                "generalize",
                "golden image (registers the sysprep task)",
                Config {
                    generalize: true,
                    // A golden build always has the random-name token, so the golden
                    // shows what really ships rather than an impossible pairing.
                    computer_name: "*".into(),
                    ..base()
                },
            ),
            (
                "one-ssh-key",
                "one ssh key",
                Config {
                    ssh_keys: vec!["ssh-ed25519 AAAAC3Nz key@host".into()],
                    ..base()
                },
            ),
            (
                "several-keys-escaped",
                "several keys, one needing quote escaping",
                Config {
                    ssh_keys: vec![
                        "ssh-rsa AAAAB3 first@host".into(),
                        "ssh-ed25519 AAAAC3 o'brien@host".into(),
                        "  ssh-rsa AAAAB3 padded@host  ".into(),
                    ],
                    ..base()
                },
            ),
            (
                "blank-keys-dropped",
                "blank keys are dropped",
                Config {
                    ssh_keys: vec![
                        "".into(),
                        "   ".into(),
                        "ssh-rsa AAAAB3 x".into(),
                    ],
                    ..base()
                },
            ),
            (
                "nothing-at-all",
                "nothing at all",
                Config {
                    inject_drivers: false,
                    enable_ssh: false,
                    ssh_keys: vec!["ignored because ssh is off".into()],
                    ..base()
                },
            ),
        ]
    }

    /// Rewrite the goldens from the current generator. See the note on the equivalent
    /// test in `unattend.rs`: the diff this produces is the review.
    ///
    ///   cargo test -p oxwin-core dump_goldens -- --ignored
    #[test]
    #[ignore = "rewrites goldens; run deliberately and read the diff"]
    fn dump_goldens() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("testdata/bootstrap");
        std::fs::create_dir_all(&dir).expect("create testdata/bootstrap");
        for (slug, _, config) in cases() {
            std::fs::write(
                dir.join(format!("{slug}.ps1")),
                build(&config).unwrap(),
            )
            .expect("write golden");
        }
    }

    /// The gate. Every branch, against a committed golden byte for byte.
    #[test]
    fn matches_the_goldens() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("testdata/bootstrap");
        for (slug, label, config) in &cases() {
            let path = dir.join(format!("{slug}.ps1"));
            // A missing golden fails. The predecessor skipped when its reference was
            // unavailable, and a test that skips is a test that lies.
            let theirs = std::fs::read_to_string(&path).unwrap_or_else(|e| {
                panic!("{}: {e}. Regenerate with dump_goldens", path.display())
            });
            let ours = build(config).unwrap();
            if let Some(where_) = first_difference(&theirs, &ours) {
                panic!("bootstrap script differs for {label}: {where_}");
            }
        }
    }

    /// A golden nothing compares against is dead weight; a case with no golden would
    /// otherwise be caught only by the read above. The two sets must agree exactly.
    #[test]
    fn every_golden_has_a_case_and_every_case_a_golden() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("testdata/bootstrap");
        let mut on_disk: Vec<String> = std::fs::read_dir(&dir)
            .expect("testdata/bootstrap")
            .map(|e| {
                e.expect("entry")
                    .file_name()
                    .to_string_lossy()
                    .trim_end_matches(".ps1")
                    .to_string()
            })
            .collect();
        on_disk.sort();
        let mut expected: Vec<String> =
            cases().iter().map(|(slug, ..)| slug.to_string()).collect();
        expected.sort();
        assert_eq!(on_disk, expected);
    }

    /// The refusal that matters: the payload is checked on the machine itself, and a
    /// signature that is not Microsoft's stops the install rather than warning.
    #[test]
    fn openssh_is_only_installed_when_microsoft_signed_it() {
        let script = build(&base()).unwrap();
        assert!(script.contains("Get-AuthenticodeSignature"));
        assert!(script.contains("O=Microsoft Corporation"));
        assert!(script.contains("REFUSING to install OpenSSH"));
        // And the refusal branch comes before the copy, not after it.
        let refuse = script.find("REFUSING to install OpenSSH").unwrap();
        let copy = script.find("Copy-Item -Path \"$stage").unwrap();
        assert!(refuse < copy, "the copy happens before the check");
    }

    /// `$root` has to lose a trailing separator or pnputil silently installs nothing:
    /// media laid out as `E:\setup\bootstrap.ps1` makes the grandparent `E:\`, and
    /// `E:\\drivers\*.inf` fails to expand while `Test-Path` still says yes.
    #[test]
    fn the_media_root_is_trimmed_of_its_separator() {
        assert!(
            build(&base())
                .unwrap()
                .contains(r"$root = (Split-Path -Parent $src).TrimEnd('\')")
        );
    }

    #[test]
    fn the_script_is_crlf_throughout_except_the_key_array() {
        let script = build(&base()).unwrap();
        // No key array here, so every newline is a CRLF.
        assert_eq!(
            script.matches('\n').count(),
            script.matches("\r\n").count()
        );
        assert!(script.ends_with("Log \"Oxide guest bootstrap complete\"\r\n"));

        // With keys, the array block is LF-separated. See the note in `build`.
        let script = build(&Config {
            ssh_keys: vec!["ssh-rsa A".into(), "ssh-rsa B".into()],
            ..base()
        })
        .unwrap();
        assert!(script.contains(
            "  $keys = @(\n    'ssh-rsa A',\n    'ssh-rsa B'\n  )\r\n"
        ));
    }

    #[test]
    fn a_key_containing_a_quote_is_escaped_for_powershell() {
        let script = build(&Config {
            ssh_keys: vec!["ssh-rsa AAAA o'brien@host".into()],
            ..base()
        })
        .unwrap();
        assert!(script.contains("'ssh-rsa AAAA o''brien@host'"));
    }

    /// The ESP fallback is the difference between a machine that boots after install
    /// and one that drops to the EFI shell.
    #[test]
    fn the_esp_fallback_bootloader_is_always_installed() {
        for config in [
            base(),
            Config { enable_ssh: false, inject_drivers: false, ..base() },
        ] {
            let script = build(&config).unwrap();
            assert!(script.contains(r"Copy-Item -Path $src2 -Destination "));
            assert!(script.contains("c12a7328-f81f-11d2-ba4b-00a0c93ec93b"));
        }
    }
}
