// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Copyright 2026 Oxide Computer Company

//! Cloud-init (cloudbase-init) in the guest.
//!
//! Upstream cloudbase-init, not the 2022 Oxide fork the public docs still point
//! at: both of that fork's functional patches are in upstream master, and
//! upstream is versioned, pinnable and EV code-signed. See
//! `docs/superpowers/specs/2026-09-22-cloud-init-design.md`.
//!
//! Two conf files, because there are two runs with different jobs:
//!
//! - `cloudbase-init-unattend.conf` is the one-shot run in the `specialize`
//!   pass of a clone's first boot: hostname, volume extension, NTP, RDP. It
//!   must not touch the account, because the account has no profile yet.
//! - `cloudbase-init.conf` is the service, every boot: SSH keys from the
//!   metadata drive, `user_data`, and -- in Mode B only -- the account itself.
//!
//! Both are pinned byte for byte by goldens in `testdata/cloudbase/`.

use crate::unattend::Config;

/// Where the MSI lands on the installer volume.
pub const MSI_VOLUME_PATH: &str = "/cloudbase/CloudbaseInitSetup_x64.msi";
pub const SERVICE_CONF_VOLUME_PATH: &str = "/cloudbase/cloudbase-init.conf";
pub const UNATTEND_CONF_VOLUME_PATH: &str =
    "/cloudbase/cloudbase-init-unattend.conf";

/// The one metadata service. The stock list probes HTTP endpoints that do not
/// exist on a rack, and a guest with no route to them spends its first boot
/// timing out -- a trap in CLAUDE.md.
const METADATA_SERVICE: &str =
    "cloudbaseinit.metadata.services.nocloudservice.NoCloudConfigDriveService";

/// A golden image keeps `<ComputerName>*</ComputerName>` *and* runs
/// `SetHostNamePlugin`, deliberately: `*` guarantees a valid unique name if the
/// config drive is ever missing, and the plugin overwrites it with the
/// instance's name when it is there. A named machine gets neither -- the user
/// typed that name.
fn is_golden(config: &Config) -> bool {
    config.computer_name == "*"
}

fn manages_account(config: &Config) -> bool {
    config.cloud_init.is_some_and(|c| c.manage_account)
}

/// Join the lines the way Windows will read them.
fn crlf(lines: Vec<String>) -> String {
    lines.join("\r\n") + "\r\n"
}

/// The `[config_drive]` block.
///
/// Read from cloudbase-init 1.1.8 (tag exists; commit
/// `a22ac6c4c0850759ae1e7acb2f5d26c2f5afd4d7`), `cloudbaseinit/conf/cloudconfig.py`
/// (despite the filename, it registers the `[config_drive]` option group) and
/// `cloudbaseinit/metadata/services/baseconfigdrive.py`. `types` and
/// `locations` are the current option names; `raw_hdd`, `cdrom` and `vfat` are
/// deprecated booleans kept for backward compatibility that only *add* to
/// whatever `types`/`locations` already contain -- they never narrow the
/// search. `types` and `locations` both default to every accepted value
/// (`{vfat, iso}` / `{cdrom, hdd, partition}`), so setting them alone would not
/// exclude `iso`/`cdrom`: `raw_hdd` and `cdrom` default to `true` and would add
/// `iso`/`cdrom` straight back in. An Oxide config drive is a vFAT volume on a
/// whole disk, so this pins `types=vfat`, `locations=hdd`, and turns the two
/// widening flags off; `vfat=true` (its default) only adds `vfat`/`hdd`, which
/// is already the configured set, so it is left unset. This matches the
/// spec's names and values exactly -- no departure to record.
fn config_drive_block() -> Vec<String> {
    vec![
        "[config_drive]".into(),
        "types=vfat".into(),
        "locations=hdd".into(),
        "raw_hdd=false".into(),
        "cdrom=false".into(),
    ]
}

/// The one-shot `specialize` run on each clone's first boot.
pub fn unattend_conf(config: &Config) -> String {
    // Plugin paths verified against the 1.1.8 tree (each file read, its
    // `class` line grepped). NOTE: NTPClientPlugin lives under `.windows.`,
    // not `.common.` -- `cloudbaseinit/conf/default.py`'s stock `plugins`
    // list registers `cloudbaseinit.plugins.windows.ntpclient.NTPClientPlugin`,
    // and `cloudbaseinit/plugins/common/ntpclient.py`'s `NTPClientPlugin` is
    // the base class the Windows one subclasses, not something the plugin
    // factory is ever pointed at directly.
    let mut plugins: Vec<&str> =
        vec!["cloudbaseinit.plugins.windows.ntpclient.NTPClientPlugin"];
    if is_golden(config) {
        plugins
            .push("cloudbaseinit.plugins.common.sethostname.SetHostNamePlugin");
    }
    plugins.push(
        "cloudbaseinit.plugins.windows.extendvolumes.ExtendVolumesPlugin",
    );
    if config.enable_rdp {
        plugins.push("cloudbaseinit.plugins.windows.rdp.RDPSettingsPlugin");
    }

    let mut lines = vec![
        "# Generated by the Oxide Windows image builder. The one-shot run in"
            .into(),
        "# the specialize pass of a clone's first boot.".into(),
        "[DEFAULT]".into(),
        // The specialize pass owns the reboot: WillReboot=OnRequest reads exit
        // code 1 as "reboot requested", so cloud-init must not reboot itself.
        "allow_reboot=false".into(),
        "stop_service_on_exit=false".into(),
        // No route off the rack, and asking costs a timeout.
        "check_latest_version=false".into(),
        "netbios_host_name_compatibility=false".into(),
        "ntp_enable_service=true".into(),
        "real_time_clock_utc=true".into(),
    ];
    if config.enable_rdp {
        lines.push("rdp_set_keepalive=true".into());
    }
    lines.extend([
        "verbose=true".into(),
        "debug=true".into(),
        r"log_dir=C:\oxide\log".into(),
        "log_file=cloudbase-init-unattend.log".into(),
        format!("metadata_services={METADATA_SERVICE}"),
        format!("plugins={}", plugins.join(",")),
    ]);
    lines.extend(config_drive_block());
    crlf(lines)
}

/// The service, every boot.
pub fn service_conf(config: &Config) -> String {
    let mut plugins: Vec<&str> = Vec::new();
    if manages_account(config) {
        // Mode B. Creates the Windows profile the key plugin needs -- and
        // resets the password doing it, because upstream's
        // BaseCreateUserPlugin::execute calls post_create_user on every path.
        plugins
            .push("cloudbaseinit.plugins.windows.createuser.CreateUserPlugin");
    }
    if is_golden(config) {
        plugins
            .push("cloudbaseinit.plugins.common.sethostname.SetHostNamePlugin");
    }
    plugins.extend([
        "cloudbaseinit.plugins.common.sshpublickeys.SetUserSSHPublicKeysPlugin",
        "cloudbaseinit.plugins.windows.extendvolumes.ExtendVolumesPlugin",
        "cloudbaseinit.plugins.common.userdata.UserDataPlugin",
    ]);

    let mut lines = vec![
        "# Generated by the Oxide Windows image builder. The cloudbase-init"
            .into(),
        "# service, which runs on every boot.".into(),
        "[DEFAULT]".into(),
        format!("username={}", config.username),
        "groups=Administrators".into(),
        "inject_user_password=false".into(),
        "allow_reboot=false".into(),
        "stop_service_on_exit=false".into(),
        "check_latest_version=false".into(),
        "netbios_host_name_compatibility=false".into(),
        "real_time_clock_utc=true".into(),
    ];
    if config.enable_rdp {
        lines.push("rdp_set_keepalive=true".into());
    }
    lines.extend([
        "verbose=true".into(),
        "debug=true".into(),
        r"log_dir=C:\oxide\log".into(),
        "log_file=cloudbase-init.log".into(),
        format!("metadata_services={METADATA_SERVICE}"),
        format!("plugins={}", plugins.join(",")),
        // Both shapes of user_data: #cloud-config YAML and a
        // <powershell>/<script> blob.
        "user_data_plugins=cloudbaseinit.plugins.common.userdataplugins.cloudconfig.CloudConfigPlugin,cloudbaseinit.plugins.common.userdataplugins.shellscript.ShellScriptPlugin".into(),
    ]);
    lines.extend(config_drive_block());
    crlf(lines)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::settings::CloudInit;
    use crate::settings::WindowsRelease;
    use std::path::PathBuf;

    fn base() -> Config {
        Config {
            release: WindowsRelease::Server2022,
            edition: "datacenter".into(),
            computer_name: "*".into(),
            username: "oxide".into(),
            password: "0xide!230xide!23".into(),
            enable_rdp: true,
            inject_drivers: true,
            enable_serial_console: true,
            target_disk: 1,
            partitions: crate::partition::default_layout(),
            ui_language: "en-US".into(),
            region: "en-US".into(),
            timezone: "UTC".into(),
            product_key: None,
            auto_logon: false,
            generalize: true,
            verbose_serial: false,
            log_path: None,
            show_ui_on_error: true,
            image_index: Some(4),
            skip_image_install: false,
            ssh_keys: Vec::new(),
            enable_ssh: true,
            cloud_init: Some(CloudInit { manage_account: false }),
            has_extras: false,
        }
    }

    /// The stock `metadata_services` list probes HTTP metadata endpoints that do
    /// not exist on a rack, and a guest with no route to them spends its first
    /// boot timing out. Exactly one service, in both files.
    #[test]
    fn exactly_one_metadata_service() {
        for conf in [service_conf(&base()), unattend_conf(&base())] {
            let lines: Vec<&str> = conf
                .lines()
                .filter(|l| l.starts_with("metadata_services="))
                .collect();
            assert_eq!(lines.len(), 1, "{conf}");
            assert_eq!(
                lines[0],
                "metadata_services=cloudbaseinit.metadata.services.nocloudservice.NoCloudConfigDriveService"
            );
        }
    }

    /// A named deployment is a machine whose name the user typed. Cloud-init has
    /// no business overwriting it, so the plugin is absent from both files.
    #[test]
    fn a_named_deployment_gets_no_hostname_plugin() {
        let named = Config {
            computer_name: "win-server-01".into(),
            generalize: false,
            ..base()
        };
        for conf in [service_conf(&named), unattend_conf(&named)] {
            assert!(!conf.contains("SetHostNamePlugin"), "{conf}");
        }
        // And a golden image does get it: `*` covers a missing config drive,
        // the plugin overwrites it with the instance's name when there is one.
        for conf in [service_conf(&base()), unattend_conf(&base())] {
            assert!(conf.contains("SetHostNamePlugin"), "{conf}");
        }
    }

    /// Mode A must not carry `CreateUserPlugin`: it resets the password to a
    /// per-instance random one on every path, including the one for an account
    /// that already exists.
    #[test]
    fn only_mode_b_creates_the_user() {
        assert!(!service_conf(&base()).contains("CreateUserPlugin"));
        let managed = Config {
            cloud_init: Some(CloudInit { manage_account: true }),
            ..base()
        };
        assert!(service_conf(&managed).contains("CreateUserPlugin"));
    }

    /// Both user-data shapes have to work: `#cloud-config` YAML and a
    /// `<powershell>`/`<script>` blob.
    #[test]
    fn both_user_data_plugins_are_configured() {
        let conf = service_conf(&base());
        assert!(conf.contains("cloudconfig.CloudConfigPlugin"));
        assert!(conf.contains("shellscript.ShellScriptPlugin"));
    }

    /// RDP keepalive and the RDP plugin are conditional on RDP being on; with
    /// it off they are absent rather than set to false.
    #[test]
    fn rdp_settings_follow_the_rdp_switch() {
        let off = Config { enable_rdp: false, ..base() };
        for conf in [service_conf(&off), unattend_conf(&off)] {
            assert!(!conf.contains("RDPSettingsPlugin"), "{conf}");
            assert!(!conf.contains("rdp_set_keepalive"), "{conf}");
        }
        assert!(unattend_conf(&base()).contains("rdp_set_keepalive=true"));
        assert!(unattend_conf(&base()).contains("RDPSettingsPlugin"));
    }

    /// Everything this tool leaves in a guest is in one place, which is what
    /// makes a machine reachable only over a serial console debuggable.
    #[test]
    fn logs_land_under_the_oxide_directory() {
        assert!(service_conf(&base()).contains(r"log_dir=C:\oxide\log"));
        assert!(service_conf(&base()).contains("log_file=cloudbase-init.log"));
        assert!(
            unattend_conf(&base())
                .contains("log_file=cloudbase-init-unattend.log")
        );
    }

    /// The prototype wrote debug chatter to COM3. An Oxide instance surfaces
    /// COM1, which carries SAC and EMS, and nothing establishes COM3 exists at
    /// all -- so that line was writing into the void. Files only.
    #[test]
    fn nothing_is_logged_to_a_serial_port() {
        for conf in [service_conf(&base()), unattend_conf(&base())] {
            for port in ["COM1", "COM2", "COM3", "COM4"] {
                assert!(!conf.contains(port), "{conf}");
            }
            assert!(!conf.contains("logging_serial_port"), "{conf}");
        }
    }

    /// Turning automatic updates on across somebody's fleet is a policy
    /// decision disguised as a default, and this tool has no update setting.
    #[test]
    fn automatic_updates_are_left_to_windows() {
        for conf in [service_conf(&base()), unattend_conf(&base())] {
            assert!(!conf.contains("WindowsAutoUpdates"), "{conf}");
            assert!(!conf.contains("enable_automatic_updates"), "{conf}");
        }
    }

    /// Read by Python on Windows off a volume that may be mounted read-only,
    /// like every other generated file here.
    #[test]
    fn the_confs_are_crlf_and_ascii() {
        for conf in [service_conf(&base()), unattend_conf(&base())] {
            assert!(conf.is_ascii(), "{conf}");
            assert_eq!(
                conf.matches('\n').count(),
                conf.matches("\r\n").count()
            );
        }
    }

    /// Every branch. The slug names the golden, the label is prose for a
    /// failure message -- kept separate so a reworded label cannot orphan a
    /// golden, exactly as in `unattend` and `bootstrap`.
    fn cases() -> Vec<(&'static str, &'static str, Config)> {
        let named = |c: Config| Config {
            computer_name: "win-server-01".into(),
            generalize: false,
            ..c
        };
        let manage = |c: Config| Config {
            cloud_init: Some(CloudInit { manage_account: true }),
            ..c
        };
        vec![
            ("golden-keep", "golden image, keep my account", base()),
            (
                "golden-manage",
                "golden image, cloud-init manages the account",
                manage(base()),
            ),
            ("named-keep", "named machine, keep my account", named(base())),
            (
                "named-manage",
                "named machine, cloud-init manages the account",
                manage(named(base())),
            ),
            (
                "golden-keep-no-rdp",
                "golden image, keep my account, no rdp",
                Config { enable_rdp: false, ..base() },
            ),
            (
                "named-manage-no-rdp",
                "named machine, managed account, no rdp",
                Config { enable_rdp: false, ..manage(named(base())) },
            ),
        ]
    }

    /// Rewrite the goldens from the current generator. The diff is the review.
    ///
    ///   cargo test -p oxwin-core dump_goldens -- --ignored
    #[test]
    #[ignore = "rewrites goldens; run deliberately and read the diff"]
    fn dump_goldens() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("testdata/cloudbase");
        std::fs::create_dir_all(&dir).expect("create testdata/cloudbase");
        for (slug, _, config) in cases() {
            std::fs::write(
                dir.join(format!("{slug}-service.conf")),
                service_conf(&config),
            )
            .expect("write golden");
            std::fs::write(
                dir.join(format!("{slug}-unattend.conf")),
                unattend_conf(&config),
            )
            .expect("write golden");
        }
    }

    #[test]
    fn matches_the_goldens() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("testdata/cloudbase");
        for (slug, label, config) in &cases() {
            for (suffix, ours) in [
                ("service", service_conf(config)),
                ("unattend", unattend_conf(config)),
            ] {
                let path = dir.join(format!("{slug}-{suffix}.conf"));
                // A missing golden fails. A test that skips is a test that lies.
                let theirs =
                    std::fs::read_to_string(&path).unwrap_or_else(|e| {
                        panic!(
                            "{}: {e}. Regenerate with dump_goldens",
                            path.display()
                        )
                    });
                assert_eq!(theirs, ours, "{suffix} conf differs for {label}");
            }
        }
    }

    /// A golden nothing compares against is dead weight, and a case with no
    /// golden would be caught only by the read above.
    #[test]
    fn every_golden_has_a_case_and_every_case_a_golden() {
        let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join("testdata/cloudbase");
        let mut on_disk: Vec<String> = std::fs::read_dir(&dir)
            .expect("testdata/cloudbase")
            .map(|e| {
                e.expect("entry").file_name().to_string_lossy().to_string()
            })
            .collect();
        on_disk.sort();
        let mut expected: Vec<String> = cases()
            .iter()
            .flat_map(|(slug, ..)| {
                [
                    format!("{slug}-service.conf"),
                    format!("{slug}-unattend.conf"),
                ]
            })
            .collect();
        expected.sort();
        assert_eq!(on_disk, expected);
    }
}
