// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Copyright 2026 Oxide Computer Company

//! The engine: what turns [`Settings`] into an image on disk.
//!
//! This drives [`crate::builder`]. It reads the ISO directly through [`crate::udf`], so
//! it needs no `hdiutil`, no mount, and no administrator rights. Handed a directory it
//! reads that instead, which is how an already-mounted ISO is used.
//!
//! Every structure it composes is pinned byte for byte by committed goldens in its own
//! module — the answer file, the bootstrap script, both filesystems, the partition table.
//! Those goldens were generated by the JavaScript builder this was ported from, whose
//! output is the code that has installed Windows on a real Oxide rack.

use crate::assets::Assets;
use crate::builder::{self, Request};
use crate::media::Media;
use crate::progress::Reporter;
use crate::settings::Settings;
use crate::unattend::Config;
use anyhow::{Context, Result, bail};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, Ordering};

/// A build takes minutes and copies gigabytes, so it has to be interruptible.
#[derive(Clone, Default)]
pub struct Cancel(Arc<AtomicBool>);

impl Cancel {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn cancel(&self) {
        self.0.store(true, Ordering::SeqCst);
    }

    pub fn is_cancelled(&self) -> bool {
        self.0.load(Ordering::SeqCst)
    }

    /// Fail if cancellation has been requested, so a long build can be written as a
    /// straight line of `?` rather than as nested checks.
    pub fn check(&self) -> anyhow::Result<()> {
        if self.is_cancelled() {
            anyhow::bail!("cancelled");
        }
        Ok(())
    }
}

pub struct Engine {
    assets: Assets,
}

impl Engine {
    pub fn new(assets: Assets) -> Self {
        Self { assets }
    }

    /// The payload compiled into this binary, or a directory named by `OXWIN_ASSETS`.
    ///
    /// This used to walk up the directory tree hunting for the repository, which worked
    /// only for someone running from a clone. A downloaded binary has nothing to walk up
    /// into, which is the whole reason the payload is embedded.
    pub fn discover() -> Self {
        Self::new(Assets::discover())
    }

    /// Which payload is in play, for `oxwin doctor` and the log — so "wrong drivers" and
    /// "no drivers" are distinguishable after the fact.
    pub fn assets(&self) -> &Assets {
        &self.assets
    }

    /// Build install media from `settings` into `out`.
    ///
    /// Reports progress through `reporter` and returns the artifact path. Returns
    /// promptly with an error once `cancel` is tripped, and does not leave a half-written
    /// image where a complete one is expected.
    pub fn build(
        &self,
        settings: &Settings,
        out: &Path,
        reporter: &Reporter,
        cancel: &Cancel,
    ) -> Result<PathBuf> {
        let result = self.assemble(settings, out, reporter, cancel);
        if result.is_err() {
            // The same contract `builder::build` keeps, extended to cover the checks
            // above it: nothing is left at `out` by a build that failed, so a stale file
            // there can never be mistaken for this run's output.
            let _ = std::fs::remove_file(out);
        }
        result
    }

    fn assemble(
        &self,
        settings: &Settings,
        out: &Path,
        reporter: &Reporter,
        cancel: &Cancel,
    ) -> Result<PathBuf> {
        let problems = settings.problems();
        if let Some(blocking) = problems.iter().find(|p| p.blocking) {
            bail!("{}", blocking.message);
        }
        // Before anything is opened: a payload-less build fails here in a sentence rather
        // than four minutes into a 4 GiB copy.
        if let Some(problem) = self.assets.problem() {
            bail!("{problem}");
        }
        // A directory is accepted so the engine can be pointed at an ISO someone has
        // already mounted, rather than insisting on the image file.
        let media = Media::at(settings.iso.clone());

        let mut config = Config::from_settings(settings, None);
        config.enable_ssh = settings.enable_ssh;
        // `config.release` is only a starting point. The builder reads what the media
        // actually is and overrides it, so a stale radio button cannot produce an image
        // for the wrong Windows. Detection lives there rather than here because the CLI
        // calls the builder directly and has to be covered by the same check.

        let request = Request {
            media,
            out: out.to_path_buf(),
            config,
            // The edition and experience are already folded into `config.edition` by
            // `Config::from_settings`, so there is nothing to override here.
            edition_hint: None,
            ei_channel: None,
            bare: false,
            assets: self.assets.clone(),
        };
        let output = builder::build(&request, reporter, cancel)
            .context("building the install image")?;
        Ok(output.path)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::settings::{Credentials, Deployment};

    fn settings() -> Settings {
        Settings {
            iso: PathBuf::from("/nonexistent.iso"),
            credentials: Credentials {
                username: "oxide".into(),
                password: "0xide!230xide!23".into(),
                keys: Vec::new(),
            },
            deployment: Deployment::Named { hostname: "win-server-01".into() },
            ..Settings::default()
        }
    }

    /// Validation runs before anything is opened, so a bad configuration fails with the
    /// reason rather than with a filesystem error from three layers down.
    #[test]
    fn blocking_problems_are_reported_before_the_media_is_touched() {
        let engine =
            Engine::new(Assets::Directory(PathBuf::from("/nonexistent")));
        let bad = Settings {
            credentials: Credentials {
                username: String::new(),
                password: String::new(),
                keys: Vec::new(),
            },
            ..settings()
        };
        let err = engine
            .build(
                &bad,
                Path::new("/nonexistent/out.img"),
                &Reporter::silent(),
                &Cancel::new(),
            )
            .err()
            .unwrap()
            .to_string();
        assert!(
            !err.contains("No such file"),
            "opened the media before validating: {err}"
        );
    }

    /// Cancelling must not leave a half-written image behind: one that looks finished
    /// and is not is worse than none at all.
    #[test]
    fn a_cancelled_build_leaves_no_image() {
        let engine =
            Engine::new(Assets::Directory(PathBuf::from("/nonexistent")));
        let out = std::env::temp_dir()
            .join(format!("oxwin-cancel-{}.img", std::process::id()));
        std::fs::write(&out, b"stale").unwrap();
        let cancel = Cancel::new();
        cancel.cancel();
        let _ = engine.build(&settings(), &out, &Reporter::silent(), &cancel);
        assert!(!out.exists(), "the partial image was left behind");
    }
}
