// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Copyright 2026 Oxide Computer Company

//! exFAT volume construction.
//!
//! This builds p1, the media volume WinPE reads. exFAT rather than FAT32 because
//! `install.wim` is over FAT32's 4 GiB per-file limit on every current Windows release:
//! 4.04 GiB on Server 2022, 4.75 GiB on Windows 11 22H2, so it can be copied byte
//! for byte with no WIM tooling, no splitting, and no risk of altering Microsoft's
//! payload. The firmware never reads this partition; it boots the small FAT32 one,
//! which loads a driver for this one.
//!
//! Scope is deliberately narrow. The image is built once and never modified, so every
//! file is allocated contiguously and flagged `NoFatChain`, which means the FAT is
//! never consulted for file data at all. That removes most of the bookkeeping a
//! general-purpose implementation needs.
//!
//! Layout, for the 6 GiB / 128 KiB-cluster case this produces:
//!
//! ```text
//!   sector 0        boot region, 12 sectors, mirrored at sector 12
//!   sector 2048     FAT, 512 sectors
//!   sector 2560     cluster heap; cluster 2 is the allocation bitmap,
//!                   3 the up-case table, 4 the root directory
//! ```
//!
//! Verified two ways: whole-volume against the committed goldens in `testdata/exfat/`,
//! which were generated by the JavaScript builder this was ported from, over a range of
//! configurations; and structure by structure against p1 of an image that installed
//! Windows on real Oxide hardware.

use crate::sparse::SparseImage;
use anyhow::{Result, bail};

/// One definition, shared with the partition table.
const SECTOR: u64 = crate::mbr::SECTOR as u64;

/// Bytes per directory entry.
const ENTRY: usize = 32;

/// The up-case table covers the whole Basic Multilingual Plane.
const UPCASE_ENTRIES: usize = 65536;
const UPCASE_BYTES: usize = UPCASE_ENTRIES * 2;

/// Directory entry type codes.
const E_VOLUME_LABEL: u8 = 0x83;
const E_ALLOCATION_BITMAP: u8 = 0x81;
const E_UPCASE_TABLE: u8 = 0x82;
const E_FILE: u8 = 0x85;
const E_STREAM: u8 = 0xc0;
const E_NAME: u8 = 0xc1;

const ATTR_DIRECTORY: u16 = 0x10;
const ATTR_ARCHIVE: u16 = 0x20;

/// `AllocationPossible | NoFatChain`. The second flag is what says "this file is one
/// contiguous run, do not walk the FAT for it".
const FLAGS_CONTIGUOUS: u8 = 0x03;

/// UTF-16 code units per name entry.
const NAME_CHARS_PER_ENTRY: usize = 15;

/// The boot region is 12 sectors and appears twice: main at sector 0, backup at 12.
const BOOT_REGION_SECTORS: u64 = 12;

/// Where the FAT starts, on a 1 MiB boundary, well clear of both boot regions.
const FAT_OFFSET_SECTORS: u64 = 2048;

/// A directory-entry timestamp, as the single 32-bit field exFAT packs it into.
///
/// No clock and no time zone, for the same reason as [`crate::fat32::Timestamp`]: the
/// builders this was ported from encoded an explicit UTC instant with local-time getters,
/// so every entry in both volumes carried the builder host's zone and no two people
/// produced the same image. Holding the encoded field makes that unrepresentable.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Timestamp(pub u32);

impl Timestamp {
    /// 2020-01-01 00:00:00 — what every image we build is stamped with.
    pub const MEDIA_EPOCH: Self = Self((40 << 25) | (1 << 21) | (1 << 16));

    /// Encode a civil date and time. Seconds have two-second resolution.
    pub fn from_civil(
        year: u16,
        month: u8,
        day: u8,
        hour: u8,
        minute: u8,
        second: u8,
    ) -> Result<Self> {
        if !(1980..=2107).contains(&year) {
            bail!("year {year} is outside exFAT's 1980..=2107 range");
        }
        if !(1..=12).contains(&month) || !(1..=31).contains(&day) {
            bail!("{year}-{month}-{day} is not a date");
        }
        if hour > 23 || minute > 59 || second > 59 {
            bail!("time {hour}:{minute}:{second} is not a time of day");
        }
        Ok(Self(
            (((year - 1980) as u32) << 25)
                | ((month as u32) << 21)
                | ((day as u32) << 16)
                | ((hour as u32) << 11)
                | ((minute as u32) << 5)
                | ((second / 2) as u32),
        ))
    }
}

/// A file whose bytes the caller still has to write, at `offset` in the finished image.
///
/// This is how a 4 GiB `install.wim` gets into the volume without being held in memory
/// alongside the image that contains it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Placement {
    pub path: String,
    pub offset: u64,
    pub size: u64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Geometry {
    pub total_sectors: u64,
    pub sectors_per_cluster: u32,
    pub sectors_per_cluster_shift: u8,
    pub cluster_bytes: u64,
    pub fat_offset: u32,
    pub fat_length: u32,
    pub cluster_heap_offset: u32,
    pub cluster_count: u32,
}

impl Geometry {
    pub fn capacity_bytes(&self) -> u64 {
        self.cluster_count as u64 * self.cluster_bytes
    }
}

#[derive(Debug, Clone)]
pub struct Options {
    pub size_bytes: u64,
    /// Upper-cased and truncated to 11 characters, as `exfat.js` does.
    pub label: String,
    /// `None` picks by volume size: 128 KiB clusters over 2 GiB, 32 KiB below. Big
    /// clusters keep the FAT and bitmap small, and these volumes hold a handful of
    /// very large files, so internal fragmentation does not matter.
    pub sectors_per_cluster: Option<u32>,
    /// Recorded in the boot sector. Informational — nothing reads it to find the
    /// volume — but wrong values confuse tools that check it.
    pub partition_offset_lba: u64,
    pub volume_serial: u32,
    pub stamp: Timestamp,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            size_bytes: 0,
            label: "OXIDE".to_string(),
            sectors_per_cluster: None,
            partition_offset_lba: 0,
            volume_serial: 0x4f58_4944, // "OXID"
            stamp: Timestamp::MEDIA_EPOCH,
        }
    }
}

impl Options {
    /// The known-good configuration of p1: the media volume WinPE reads.
    pub fn media(sectors: u64, partition_offset_lba: u64) -> Self {
        Self {
            size_bytes: sectors * SECTOR,
            label: "WINSETUP".to_string(),
            partition_offset_lba,
            ..Self::default()
        }
    }
}

struct Node {
    name: String,
    is_dir: bool,
    /// Insertion-ordered, keyed by upper-cased name. The order fixes both entry order
    /// and cluster allocation order, so the volume is only reproducible while it is
    /// stable.
    children: Vec<(String, usize)>,
    data: Option<Vec<u8>>,
    reserved: bool,
    path: String,
    first_cluster: u32,
    cluster_count: u32,
    byte_size: u64,
    /// Directory entries this directory holds, including the three fixed ones if it is
    /// the root. Set by `measure`.
    entry_count: u64,
}

impl Node {
    fn new(name: String, is_dir: bool) -> Self {
        Self {
            name,
            is_dir,
            children: Vec::new(),
            data: None,
            reserved: false,
            path: String::new(),
            first_cluster: 0,
            cluster_count: 0,
            byte_size: 0,
            entry_count: 0,
        }
    }
}

const ROOT: usize = 0;

/// A contiguous cluster run.
#[derive(Debug, Clone, Copy)]
struct Alloc {
    first: u32,
    count: u32,
}

pub struct ExFatBuilder {
    label: String,
    partition_offset_lba: u64,
    volume_serial: u32,
    stamp: Timestamp,
    size_bytes: u64,
    geometry: Geometry,
    nodes: Vec<Node>,
    /// Every run handed out, so the FAT can carry a real chain for each.
    allocations: Vec<Alloc>,
    upcase_checksum: u32,
    placements: Vec<Placement>,
}

impl ExFatBuilder {
    pub fn new(opts: Options) -> Result<Self> {
        if opts.size_bytes == 0 {
            bail!("an exFAT volume needs a size");
        }
        let label: String =
            opts.label.to_uppercase().chars().take(11).collect();

        let shift = match opts.sectors_per_cluster {
            Some(spc) => {
                if !spc.is_power_of_two() {
                    bail!(
                        "sectors per cluster must be a power of two, got {spc}"
                    );
                }
                spc.trailing_zeros() as u8
            }
            // 128 KiB over 2 GiB, 32 KiB below.
            None => {
                if opts.size_bytes > 2 * 1024 * 1024 * 1024 {
                    8
                } else {
                    6
                }
            }
        };
        let geometry = geometry_for(opts.size_bytes, shift)?;

        Ok(Self {
            label,
            partition_offset_lba: opts.partition_offset_lba,
            volume_serial: opts.volume_serial,
            stamp: opts.stamp,
            size_bytes: opts.size_bytes,
            geometry,
            nodes: vec![Node::new(String::new(), true)],
            allocations: Vec::new(),
            upcase_checksum: 0,
            placements: Vec::new(),
        })
    }

    pub fn geometry(&self) -> Geometry {
        self.geometry
    }

    /// Files whose bytes the caller still has to write. Empty until `build`.
    pub fn placements(&self) -> &[Placement] {
        &self.placements
    }

    pub fn add_dir(&mut self, path: &str) -> Result<usize> {
        let mut node = ROOT;
        for part in split_path(path) {
            check_name(part)?;
            let key = part.to_uppercase();
            match self.child(node, &key) {
                Some(existing) => {
                    if !self.nodes[existing].is_dir {
                        bail!(
                            "cannot create directory {path}: {part} is a file"
                        );
                    }
                    node = existing;
                }
                None => {
                    let child = Node::new(part.to_string(), true);
                    let id = self.push(child);
                    self.nodes[node].children.push((key, id));
                    node = id;
                }
            }
        }
        Ok(node)
    }

    pub fn add_file(&mut self, path: &str, data: Vec<u8>) -> Result<()> {
        let size = data.len() as u64;
        self.insert_file(path, size, Some(data), false)
    }

    /// Reserve `size` bytes without supplying them. After `build`, the bytes go at the
    /// matching entry in `placements`.
    pub fn reserve_file(&mut self, path: &str, size: u64) -> Result<()> {
        self.insert_file(path, size, None, true)
    }

    fn insert_file(
        &mut self,
        path: &str,
        size: u64,
        data: Option<Vec<u8>>,
        reserved: bool,
    ) -> Result<()> {
        let mut parts = split_path(path);
        let name = match parts.pop() {
            Some(name) => name,
            None => bail!("a file needs a name, got {path:?}"),
        };
        check_name(name)?;
        let dir = if parts.is_empty() {
            ROOT
        } else {
            self.add_dir(&parts.join("/"))?
        };

        let mut node = Node::new(name.to_string(), false);
        node.data = data;
        node.reserved = reserved;
        node.byte_size = size;
        node.path = if parts.is_empty() {
            format!("/{name}")
        } else {
            format!("/{}/{name}", parts.join("/"))
        };

        let key = name.to_uppercase();
        let id = self.push(node);
        // Last writer wins, in place. A caller overriding `sources/EI.CFG` with
        // `sources/ei.cfg` means one file, not two entries a case-insensitive reader
        // cannot tell apart; replacing in place keeps entry order and so the bytes.
        match self.nodes[dir].children.iter().position(|(k, _)| *k == key) {
            Some(slot) => self.nodes[dir].children[slot] = (key, id),
            None => self.nodes[dir].children.push((key, id)),
        }
        Ok(())
    }

    fn push(&mut self, node: Node) -> usize {
        self.nodes.push(node);
        self.nodes.len() - 1
    }

    fn child(&self, dir: usize, key: &str) -> Option<usize> {
        self.nodes[dir]
            .children
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, id)| *id)
    }

    fn kids(&self, dir: usize) -> Vec<usize> {
        self.nodes[dir].children.iter().map(|(_, id)| *id).collect()
    }

    pub fn build(&mut self) -> Result<SparseImage> {
        let upcase = upcase_table();
        self.upcase_checksum = checksum32(&upcase);
        self.allocations.clear();
        self.placements.clear();

        let bitmap_bytes = (self.geometry.cluster_count as u64).div_ceil(8);

        // Fixed metadata first, then the tree, all contiguous.
        //
        // Every run is recorded so the FAT can carry a chain for it. Files and
        // subdirectories set NoFatChain and do not strictly need one, but the
        // allocation bitmap, up-case table and root directory have no such flag in
        // their entries — their chains must be in the FAT or the volume will not
        // mount. Writing chains for everything is cheap and keeps the two views
        // consistent.
        let mut next: u32 = 2;
        let bitmap = self.take(&mut next, bitmap_bytes)?;
        let upcase_alloc = self.take(&mut next, UPCASE_BYTES as u64)?;

        self.measure(ROOT, true);
        let root_bytes = self.nodes[ROOT].entry_count * ENTRY as u64;
        let root_alloc = self.take(&mut next, root_bytes)?;
        self.nodes[ROOT].first_cluster = root_alloc.first;
        self.nodes[ROOT].cluster_count = root_alloc.count;

        self.allocate_children(ROOT, &mut next)?;

        let used = next - 2;
        if used > self.geometry.cluster_count {
            bail!(
                "contents need {} but the volume holds {}",
                fmt_bytes(used as u64 * self.geometry.cluster_bytes),
                fmt_bytes(self.geometry.capacity_bytes()),
            );
        }

        let mut image = SparseImage::new(self.size_bytes)?;
        self.write_boot_region(&mut image, 0, &root_alloc)?;
        self.write_boot_region(&mut image, BOOT_REGION_SECTORS, &root_alloc)?;
        self.write_fat(&mut image)?;
        self.write_bitmap(&mut image, &bitmap, used)?;
        image.write(self.cluster_offset(upcase_alloc.first), &upcase)?;
        self.write_dir(
            &mut image,
            ROOT,
            true,
            &bitmap,
            &upcase_alloc,
            bitmap_bytes,
        )?;
        Ok(image)
    }

    /// Hand out a contiguous run big enough for `bytes`, recording it for the FAT.
    ///
    /// Zero bytes still takes one cluster: a directory with no children is still a
    /// directory and needs somewhere to be.
    fn take(&mut self, next: &mut u32, bytes: u64) -> Result<Alloc> {
        let first = *next;
        let count =
            u32::try_from(bytes.div_ceil(self.geometry.cluster_bytes).max(1))
                .map_err(|_| {
                anyhow::anyhow!("allocation of {bytes} bytes is too large")
            })?;
        *next = next
            .checked_add(count)
            .ok_or_else(|| anyhow::anyhow!("cluster numbering overflowed"))?;
        let alloc = Alloc { first, count };
        self.allocations.push(alloc);
        Ok(alloc)
    }

    /// Entry counts, which depend only on names, so this runs before any cluster
    /// exists. exFAT has no `.` or `..`, so a subdirectory counts only its children.
    fn measure(&mut self, dir: usize, is_root: bool) {
        // Volume label, allocation bitmap, up-case table.
        let mut entries: u64 = if is_root { 3 } else { 0 };
        for id in self.kids(dir) {
            let name_entries = self.nodes[id]
                .name
                .chars()
                .count()
                .div_ceil(NAME_CHARS_PER_ENTRY);
            entries += 2 + name_entries as u64;
            if self.nodes[id].is_dir {
                self.measure(id, false);
            }
        }
        self.nodes[dir].entry_count = entries;
    }

    fn allocate_children(&mut self, dir: usize, next: &mut u32) -> Result<()> {
        for id in self.kids(dir) {
            let is_dir = self.nodes[id].is_dir;
            let bytes = if is_dir {
                self.nodes[id].entry_count * ENTRY as u64
            } else {
                self.nodes[id].byte_size
            };
            if !is_dir && self.nodes[id].byte_size == 0 {
                // An empty file names cluster 0 and takes no space at all.
                self.nodes[id].first_cluster = 0;
                self.nodes[id].cluster_count = 0;
            } else {
                let alloc = self.take(next, bytes)?;
                self.nodes[id].first_cluster = alloc.first;
                self.nodes[id].cluster_count = alloc.count;
            }
            if is_dir {
                self.allocate_children(id, next)?;
            }
        }
        Ok(())
    }

    fn cluster_offset(&self, cluster: u32) -> u64 {
        (self.geometry.cluster_heap_offset as u64
            + (cluster as u64 - 2) * self.geometry.sectors_per_cluster as u64)
            * SECTOR
    }

    fn write_boot_region(
        &self,
        image: &mut SparseImage,
        start_sector: u64,
        root: &Alloc,
    ) -> Result<()> {
        let mut boot = [0u8; SECTOR as usize];
        boot[0..3].copy_from_slice(&[0xeb, 0x76, 0x90]);
        boot[3..11].copy_from_slice(b"EXFAT   ");
        put64(&mut boot, 64, self.partition_offset_lba);
        put64(&mut boot, 72, self.geometry.total_sectors);
        put32(&mut boot, 80, self.geometry.fat_offset);
        put32(&mut boot, 84, self.geometry.fat_length);
        put32(&mut boot, 88, self.geometry.cluster_heap_offset);
        put32(&mut boot, 92, self.geometry.cluster_count);
        put32(&mut boot, 96, root.first);
        put32(&mut boot, 100, self.volume_serial);
        put16(&mut boot, 104, 0x0100); // revision 1.00
        put16(&mut boot, 106, 0); // volume flags
        boot[108] = 9; // bytes per sector shift: 512
        boot[109] = self.geometry.sectors_per_cluster_shift;
        boot[110] = 1; // one FAT
        boot[111] = 0x80; // drive select
        boot[112] = 0; // percent in use
        boot[510] = 0x55;
        boot[511] = 0xaa;
        image.write(start_sector * SECTOR, &boot)?;

        // Extended boot sectors 1..=8 are empty but must carry the signature.
        let mut ext = [0u8; SECTOR as usize];
        put32(&mut ext, 508, 0xaa55_0000);
        for i in 1..=8u64 {
            image.write((start_sector + i) * SECTOR, &ext)?;
        }

        // Sector 9 (OEM parameters) and 10 (reserved) stay zero.

        // Sector 11 holds a checksum over the preceding eleven sectors, repeated to
        // fill it. VolumeFlags and PercentInUse are excluded because they change at
        // runtime, and a checksum over a field that moves would invalidate itself.
        let mut region = vec![0u8; 11 * SECTOR as usize];
        region[..SECTOR as usize].copy_from_slice(&boot);
        for i in 1..=8usize {
            let at = i * SECTOR as usize;
            region[at..at + SECTOR as usize].copy_from_slice(&ext);
        }
        let mut sum: u32 = 0;
        for (i, byte) in region.iter().enumerate() {
            if i == 106 || i == 107 || i == 112 {
                continue;
            }
            sum = sum.rotate_right(1).wrapping_add(*byte as u32);
        }
        let mut check = [0u8; SECTOR as usize];
        for i in 0..SECTOR as usize / 4 {
            put32(&mut check, i * 4, sum);
        }
        image.write((start_sector + 11) * SECTOR, &check)?;
        Ok(())
    }

    fn write_fat(&self, image: &mut SparseImage) -> Result<()> {
        let highest = self
            .allocations
            .iter()
            .map(|a| a.first as u64 + a.count as u64)
            .max()
            .unwrap_or(2);
        let mut fat = vec![0u8; highest as usize * 4];
        put32(&mut fat, 0, 0xffff_fff8); // media descriptor
        put32(&mut fat, 4, 0xffff_ffff); // reserved

        for alloc in &self.allocations {
            for i in 0..alloc.count {
                let cluster = alloc.first + i;
                let next = if i == alloc.count - 1 {
                    0xffff_ffff
                } else {
                    cluster + 1
                };
                put32(&mut fat, cluster as usize * 4, next);
            }
        }
        image.write(self.geometry.fat_offset as u64 * SECTOR, &fat)
    }

    fn write_bitmap(
        &self,
        image: &mut SparseImage,
        bitmap: &Alloc,
        used: u32,
    ) -> Result<()> {
        // Only the used prefix is written; the rest of the bitmap is zero, which is
        // what "free" means, so it costs nothing.
        let mut bytes = vec![0u8; ((used as u64).div_ceil(8).max(1)) as usize];
        for i in 0..used as usize {
            bytes[i >> 3] |= 1 << (i & 7);
        }
        image.write(self.cluster_offset(bitmap.first), &bytes)
    }

    fn write_dir(
        &mut self,
        image: &mut SparseImage,
        dir: usize,
        is_root: bool,
        bitmap: &Alloc,
        upcase: &Alloc,
        bitmap_bytes: u64,
    ) -> Result<()> {
        let capacity =
            self.nodes[dir].cluster_count as u64 * self.geometry.cluster_bytes;
        let mut buf = vec![0u8; capacity as usize];
        let mut at = 0usize;

        if is_root {
            let mut label = [0u8; ENTRY];
            label[0] = E_VOLUME_LABEL;
            label[1] = self.label.chars().count() as u8;
            put_utf16(&mut label, 2, &self.label);
            at = put_entry(&mut buf, at, &label)?;

            let mut bm = [0u8; ENTRY];
            bm[0] = E_ALLOCATION_BITMAP;
            bm[1] = 0; // first of one bitmap; a second would set bit 0
            put32(&mut bm, 20, bitmap.first);
            put64(&mut bm, 24, bitmap_bytes);
            at = put_entry(&mut buf, at, &bm)?;

            let mut uc = [0u8; ENTRY];
            uc[0] = E_UPCASE_TABLE;
            put32(&mut uc, 4, self.upcase_checksum);
            put32(&mut uc, 20, upcase.first);
            put64(&mut uc, 24, UPCASE_BYTES as u64);
            at = put_entry(&mut buf, at, &uc)?;
        }

        for id in self.kids(dir) {
            for entry in self.file_entry_set(id) {
                at = put_entry(&mut buf, at, &entry)?;
            }
        }

        let offset = self.cluster_offset(self.nodes[dir].first_cluster);
        image.write(offset, &buf)?;

        for id in self.kids(dir) {
            if self.nodes[id].is_dir {
                self.write_dir(image, id, false, bitmap, upcase, bitmap_bytes)?;
            } else if self.nodes[id].reserved {
                self.placements.push(Placement {
                    path: self.nodes[id].path.clone(),
                    offset: self.cluster_offset(self.nodes[id].first_cluster),
                    size: self.nodes[id].byte_size,
                });
            } else if self.nodes[id].byte_size > 0 {
                let offset = self.cluster_offset(self.nodes[id].first_cluster);
                if let Some(data) = &self.nodes[id].data {
                    image.write(offset, data)?;
                }
            }
        }
        Ok(())
    }

    /// The file entry, its stream extension, and the name entries — one directory
    /// entry set, which is how exFAT represents a single file.
    fn file_entry_set(&self, id: usize) -> Vec<[u8; ENTRY]> {
        let node = &self.nodes[id];
        let chars: Vec<char> = node.name.chars().collect();
        let name_entries = chars.len().div_ceil(NAME_CHARS_PER_ENTRY);
        let size = if node.is_dir {
            node.entry_count * ENTRY as u64
        } else {
            node.byte_size
        };

        let mut file = [0u8; ENTRY];
        file[0] = E_FILE;
        file[1] = 1 + name_entries as u8; // secondary entries following
        put16(
            &mut file,
            4,
            if node.is_dir { ATTR_DIRECTORY } else { ATTR_ARCHIVE },
        );
        put32(&mut file, 8, self.stamp.0); // created
        put32(&mut file, 12, self.stamp.0); // modified
        put32(&mut file, 16, self.stamp.0); // accessed

        let mut stream = [0u8; ENTRY];
        stream[0] = E_STREAM;
        stream[1] = FLAGS_CONTIGUOUS;
        stream[3] = chars.len() as u8;
        put16(&mut stream, 4, name_hash(&node.name));
        put64(&mut stream, 8, size); // valid data length
        put32(&mut stream, 20, node.first_cluster);
        put64(&mut stream, 24, size);

        let mut all = vec![file, stream];
        for i in 0..name_entries {
            let mut e = [0u8; ENTRY];
            e[0] = E_NAME;
            let chunk: String = chars
                .iter()
                .skip(i * NAME_CHARS_PER_ENTRY)
                .take(NAME_CHARS_PER_ENTRY)
                .collect();
            put_utf16(&mut e, 2, &chunk);
            all.push(e);
        }

        // The set checksum spans every entry, skipping its own two bytes. A reader
        // that finds a mismatch treats the whole set as corrupt, so this is the
        // difference between a file being there and the volume looking damaged.
        let mut sum: u16 = 0;
        for (index, byte) in all.iter().flatten().enumerate() {
            if index == 2 || index == 3 {
                continue;
            }
            sum = sum.rotate_right(1).wrapping_add(*byte as u16);
        }
        put16(&mut all[0], 2, sum);
        all
    }
}

fn geometry_for(size_bytes: u64, shift: u8) -> Result<Geometry> {
    if shift > 25 {
        bail!("sectors-per-cluster shift {shift} is out of range");
    }
    let spc = 1u64 << shift;
    let total_sectors = size_bytes / SECTOR;
    if total_sectors <= FAT_OFFSET_SECTORS {
        bail!("a {size_bytes}-byte volume is too small for exFAT");
    }

    // Solve for a cluster count whose FAT and bitmap fit alongside it. The FAT's size
    // depends on the cluster count and the cluster count depends on the FAT's size, so
    // it is estimate-then-correct; at these sizes it converges in one pass.
    let mut cluster_count = (total_sectors - FAT_OFFSET_SECTORS) / spc;
    for _ in 0..4 {
        let fat_sectors = ((cluster_count + 2) * 4).div_ceil(SECTOR);
        let fat_length = align(fat_sectors, spc);
        let heap = FAT_OFFSET_SECTORS + fat_length;
        if heap >= total_sectors {
            bail!("a {size_bytes}-byte volume is too small for exFAT");
        }
        let next = (total_sectors - heap) / spc;
        if next == cluster_count {
            break;
        }
        cluster_count = next;
    }

    let fat_length = align(((cluster_count + 2) * 4).div_ceil(SECTOR), spc);
    let cluster_heap_offset = FAT_OFFSET_SECTORS + fat_length;
    if cluster_count < 16 {
        bail!("volume too small for exFAT: {cluster_count} clusters");
    }
    Ok(Geometry {
        total_sectors,
        sectors_per_cluster: spc as u32,
        sectors_per_cluster_shift: shift,
        cluster_bytes: spc * SECTOR,
        fat_offset: FAT_OFFSET_SECTORS as u32,
        fat_length: u32::try_from(fat_length)
            .map_err(|_| anyhow::anyhow!("FAT is too large to address"))?,
        cluster_heap_offset: u32::try_from(cluster_heap_offset).map_err(
            |_| anyhow::anyhow!("cluster heap is too far into the volume"),
        )?,
        cluster_count: u32::try_from(cluster_count)
            .map_err(|_| anyhow::anyhow!("too many clusters"))?,
    })
}

// --- helpers ------------------------------------------------------------

fn put16(buf: &mut [u8], at: usize, value: u16) {
    buf[at..at + 2].copy_from_slice(&value.to_le_bytes());
}

fn put32(buf: &mut [u8], at: usize, value: u32) {
    buf[at..at + 4].copy_from_slice(&value.to_le_bytes());
}

fn put64(buf: &mut [u8], at: usize, value: u64) {
    buf[at..at + 8].copy_from_slice(&value.to_le_bytes());
}

fn put_entry(buf: &mut [u8], at: usize, entry: &[u8; ENTRY]) -> Result<usize> {
    if at + ENTRY > buf.len() {
        bail!("directory entries overflow the clusters measured for them");
    }
    buf[at..at + ENTRY].copy_from_slice(entry);
    Ok(at + ENTRY)
}

/// Write `s` as UTF-16LE code units at `at`.
fn put_utf16(buf: &mut [u8], at: usize, s: &str) {
    for (i, unit) in s.encode_utf16().enumerate() {
        put16(buf, at + i * 2, unit);
    }
}

fn align(value: u64, to: u64) -> u64 {
    value.div_ceil(to) * to
}

fn split_path(path: &str) -> Vec<&str> {
    path.split(['/', '\\']).filter(|p| !p.is_empty() && *p != ".").collect()
}

/// Names are limited to the Basic Multilingual Plane.
///
/// `exfat.js` writes one 16-bit unit per code point and counts name length in code
/// points, so anything needing a surrogate pair overflows its name entries and throws.
/// Refusing it up front with an explanation beats matching the crash, and nothing on
/// Windows media comes close.
fn check_name(name: &str) -> Result<()> {
    if let Some(c) = name.chars().find(|c| *c as u32 > 0xffff) {
        bail!(
            "{name:?} contains {c:?}, which is outside the range exFAT names are \
             written in here"
        );
    }
    if name.chars().count() > 255 {
        bail!("{name:?} is longer than exFAT's 255-character limit");
    }
    Ok(())
}

/// The up-case table: a Unicode simple-uppercase mapping over the whole BMP.
///
/// Derived rather than embedded, and derived the same way `exfat.js` derives it —
/// take the standard uppercase mapping and keep it only where it maps one character to
/// exactly one character, so `ß` stays `ß` rather than becoming `SS`. Hand-folding
/// ASCII and Latin-1 instead produces a table `fsck_exfat` rejects.
///
/// The table is anchored by its checksum: the test pins it to the value in p1 of an
/// image that booted, so a Unicode data change in either language shows up as a test
/// failure rather than as a volume Windows quietly dislikes.
fn upcase_table() -> Vec<u8> {
    let mut table = vec![0u8; UPCASE_BYTES];
    for code in 0..UPCASE_ENTRIES as u32 {
        let mut up = code as u16;
        // Surrogates have no case mapping and pass through untouched.
        if !(0xd800..=0xdfff).contains(&code) {
            if let Some(c) = char::from_u32(code) {
                let mut upper = c.to_uppercase();
                if let (Some(u), None) = (upper.next(), upper.next()) {
                    if (u as u32) <= 0xffff {
                        up = u as u32 as u16;
                    }
                }
            }
        }
        put16(&mut table, code as usize * 2, up);
    }
    table
}

fn checksum32(bytes: &[u8]) -> u32 {
    let mut sum: u32 = 0;
    for byte in bytes {
        sum = sum.rotate_right(1).wrapping_add(*byte as u32);
    }
    sum
}

/// The name hash stored in the stream extension, so a reader can reject a name without
/// comparing it.
///
/// Note this up-cases by hand — ASCII plus the Latin-1 range — rather than through the
/// up-case table the volume carries, which is what the specification calls for. Only
/// names outside those ranges would hash differently, and every name on Windows media
/// is ASCII. Preserved as `exfat.js` has it so the two engines agree.
fn name_hash(name: &str) -> u16 {
    let mut hash: u16 = 0;
    for ch in name.chars() {
        let mut c = ch as u32 as u16;
        if (0x61..=0x7a).contains(&c) {
            c -= 0x20;
        } else if (0xe0..=0xfe).contains(&c) && c != 0xf7 {
            c -= 0x20;
        }
        hash = hash.rotate_right(1).wrapping_add(c & 0xff);
        hash = hash.rotate_right(1).wrapping_add(c >> 8);
    }
    hash
}

fn fmt_bytes(n: u64) -> String {
    const UNITS: [&str; 4] = ["B", "KiB", "MiB", "GiB"];
    let mut value = n as f64;
    let mut unit = 0;
    while value >= 1024.0 && unit < UNITS.len() - 1 {
        value /= 1024.0;
        unit += 1;
    }
    format!("{value:.1} {}", UNITS[unit])
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    /// p1 of `ws2022-win-server-01-install.img`: 6 GiB at LBA 2048.
    const MEDIA_SECTORS: u64 = 12_582_912;
    const MEDIA_LBA: u64 = 2048;

    /// The up-case table checksum stored in that volume's root directory. Four bytes
    /// that pin all 131072 bytes of the table, and with them the Unicode data of both
    /// languages, to something that booted.
    const REFERENCE_UPCASE_CHECKSUM: u32 = 0x8742_138f;

    /// The boot region checksum from that volume, covering the eleven sectors before
    /// it. Fixed entirely by the geometry, so this is hermetic.
    const REFERENCE_BOOT_CHECKSUM: u32 = 0xc64f_051d;

    fn golden(name: &str) -> Vec<u8> {
        let text = include_str!("../testdata/reference-media.txt");
        let hex = text
            .lines()
            .filter(|l| !l.starts_with('#'))
            .find_map(|l| l.strip_prefix(&format!("{name} ")))
            .unwrap_or_else(|| panic!("no golden region named {name}"));
        (0..hex.len() / 2)
            .map(|i| u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap())
            .collect()
    }

    fn first_difference(want: &[u8], got: &[u8]) -> Option<String> {
        for (i, (x, y)) in want.iter().zip(got).enumerate() {
            if x != y {
                return Some(format!(
                    "byte {i} (0x{i:x}): expected 0x{x:02x}, got 0x{y:02x}"
                ));
            }
        }
        if want.len() != got.len() {
            return Some(format!("length {} vs {}", want.len(), got.len()));
        }
        None
    }

    fn assert_region(image: &SparseImage, offset: u64, name: &str) {
        let want = golden(name);
        let got = image.read(offset, want.len());
        if let Some(where_) = first_difference(&want, &got) {
            panic!("{name} differs from the reference volume: {where_}");
        }
    }

    /// One entry in a volume description, shared between the two engines.
    enum Item {
        Dir(&'static str),
        Text(&'static str, &'static str),
        Reserved(&'static str, u64),
    }

    struct Spec {
        name: &'static str,
        size_bytes: u64,
        label: &'static str,
        sectors_per_cluster: Option<u32>,
        partition_offset_lba: u64,
        items: Vec<Item>,
    }

    fn media_spec(name: &'static str, items: Vec<Item>) -> Spec {
        Spec {
            name,
            size_bytes: MEDIA_SECTORS * SECTOR,
            label: "WINSETUP",
            sectors_per_cluster: None,
            partition_offset_lba: MEDIA_LBA,
            items,
        }
    }

    fn build_ours(spec: &Spec) -> (ExFatBuilder, SparseImage) {
        let mut b = ExFatBuilder::new(Options {
            size_bytes: spec.size_bytes,
            label: spec.label.to_string(),
            sectors_per_cluster: spec.sectors_per_cluster,
            partition_offset_lba: spec.partition_offset_lba,
            ..Options::default()
        })
        .unwrap();
        for item in &spec.items {
            match item {
                Item::Dir(path) => {
                    b.add_dir(path).unwrap();
                }
                Item::Text(path, text) => {
                    b.add_file(path, text.as_bytes().to_vec()).unwrap()
                }
                Item::Reserved(path, size) => {
                    b.reserve_file(path, *size).unwrap()
                }
            }
        }
        let image = b.build().unwrap();
        (b, image)
    }

    fn golden_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata/exfat")
    }

    /// Golden filename for a spec. The name is the identifier every assertion here
    /// already reports, so it is also the slug; `every_golden_has_a_spec` below catches
    /// the rename that would otherwise orphan a file.
    fn slug(spec: &Spec) -> String {
        spec.name.replace(' ', "-")
    }

    /// Serialise a block stream: offset as u64 LE, length as u32 LE, then the bytes.
    /// This is the encoding the committed goldens were written in, so it is fixed.
    fn encode_blocks(blocks: &[(u64, Vec<u8>)]) -> Vec<u8> {
        let mut out = Vec::new();
        for (offset, data) in blocks {
            out.extend_from_slice(&offset.to_le_bytes());
            out.extend_from_slice(&(data.len() as u32).to_le_bytes());
            out.extend_from_slice(data);
        }
        out
    }

    fn decode_blocks(raw: &[u8]) -> Vec<(u64, Vec<u8>)> {
        let mut blocks = Vec::new();
        let mut at = 0usize;
        while at < raw.len() {
            let offset =
                u64::from_le_bytes(raw[at..at + 8].try_into().unwrap());
            let len =
                u32::from_le_bytes(raw[at + 8..at + 12].try_into().unwrap())
                    as usize;
            at += 12;
            blocks.push((offset, raw[at..at + len].to_vec()));
            at += len;
        }
        blocks
    }

    /// The committed volume, as a list of non-zero blocks.
    ///
    /// A missing golden fails. The predecessor of this generated its reference by
    /// running the builder this was ported from, and returned None when that was not
    /// installed — so every caller skipped, and a machine without it ran a suite that
    /// proved nothing while reporting success.
    fn read_blocks_golden(spec: &Spec) -> Vec<(u64, Vec<u8>)> {
        let path = golden_dir().join(format!("{}.blocks", slug(spec)));
        let raw = std::fs::read(&path).unwrap_or_else(|e| {
            panic!("{}: {e}. Regenerate with dump_js_goldens", path.display())
        });
        decode_blocks(&raw)
    }

    /// Rewrite the goldens from the current builder. See the note on `dump_goldens` in
    /// `unattend.rs`: the committed goldens came from the JavaScript builder, so running
    /// this replaces that provenance with "whatever the Rust does today" and the diff it
    /// produces is the review.
    ///
    ///   cargo test -p oxwin-core dump_goldens -- --ignored
    #[test]
    #[ignore = "rewrites goldens; run deliberately and read the diff"]
    fn dump_goldens() {
        let dir = golden_dir();
        std::fs::create_dir_all(&dir).expect("create testdata/exfat");
        for spec in specs() {
            let (_, image) = build_ours(&spec);
            let blocks: Vec<(u64, Vec<u8>)> = image
                .non_zero_blocks()
                .iter()
                .map(|c| (c.offset, c.data.to_vec()))
                .collect();
            std::fs::write(
                dir.join(format!("{}.blocks", slug(&spec))),
                encode_blocks(&blocks),
            )
            .expect("write blocks");
        }

        // The placements spec is compared only on its placements report, so only that is
        // snapshotted. Its block stream was never verified against the reference, and a
        // golden nothing has checked is worse than no golden.
        let spec = placements_spec();
        let (builder, _) = build_ours(&spec);
        let placements: Vec<serde_json::Value> = builder
            .placements()
            .iter()
            .map(|p| {
                serde_json::json!({
                    "path": p.path, "offset": p.offset, "size": p.size,
                })
            })
            .collect();
        std::fs::write(
            dir.join("placements.json"),
            serde_json::to_string(&serde_json::json!({
                "placements": placements
            }))
            .expect("json"),
        )
        .expect("write placements report");
    }

    /// A golden nothing compares against is dead weight; a spec with no golden would be
    /// caught only by the reads above. The two sets must agree exactly.
    #[test]
    fn every_golden_has_a_spec_and_every_spec_a_golden() {
        let mut on_disk: Vec<String> = std::fs::read_dir(golden_dir())
            .expect("testdata/exfat")
            .map(|e| {
                e.expect("entry").file_name().to_string_lossy().to_string()
            })
            .collect();
        on_disk.sort();
        let mut expected: Vec<String> = specs()
            .iter()
            .map(|s| format!("{}.blocks", slug(s)))
            .chain(["placements.json".to_string()])
            .collect();
        expected.sort();
        assert_eq!(on_disk, expected);
    }

    /// Compare a volume against its golden, block for block.
    ///
    /// This is a complete comparison, not a sampled one: holes read as zero on both
    /// sides and an all-zero block is excluded by both, so two volumes with the same
    /// non-zero blocks are identical byte for byte.
    fn assert_matches_golden(spec: &Spec) {
        let theirs = read_blocks_golden(spec);
        let (_, image) = build_ours(spec);
        let ours = image.non_zero_blocks();

        let their_offsets: Vec<u64> = theirs.iter().map(|(o, _)| *o).collect();
        let our_offsets: Vec<u64> = ours.iter().map(|c| c.offset).collect();
        assert_eq!(
            their_offsets, our_offsets,
            "{}: different blocks written",
            spec.name
        );
        for ((offset, want), got) in theirs.iter().zip(&ours) {
            if let Some(where_) = first_difference(want, got.data) {
                panic!(
                    "{}: block at {offset} differs: {where_} \
                     (absolute byte {})",
                    spec.name,
                    offset
                        + where_
                            .split_whitespace()
                            .nth(1)
                            .and_then(|s| s.parse::<u64>().ok())
                            .unwrap_or(0)
                );
            }
        }
    }

    fn specs() -> Vec<Spec> {
        vec![
            // The real thing: the media tree's shape, with install.wim reserved at its
            // true size. This is the configuration that has to be right.
            media_spec(
                "server-2022 media",
                vec![
                    Item::Text(
                        "/autorun.inf",
                        "[autorun]\r\nopen=setup.exe\r\n",
                    ),
                    Item::Text("/boot/bcd", "bcd"),
                    Item::Text("/boot/boot.sdi", "sdi"),
                    Item::Text("/bootmgr", "bootmgr"),
                    Item::Text("/bootmgr.efi", "bootmgr.efi"),
                    Item::Text("/efi/boot/bootx64.efi", "efi"),
                    Item::Text("/setup.exe", "setup"),
                    Item::Reserved("/sources/install.wim", 4_340_202_461),
                    Item::Text("/sources/boot.wim", "boot.wim"),
                    Item::Text("/sources/ei.cfg", "[Channel]\r\nRetail\r\n"),
                    Item::Text("/support/logging/x.txt", "log"),
                    Item::Text("/autounattend.xml", "<unattend/>"),
                    Item::Text("/setup/oxide-bootstrap.ps1", "bootstrap"),
                    Item::Text("/drivers/NetKVM/2k22/amd64/netkvm.inf", "inf"),
                    Item::Text("/openssh/OpenSSH-Win64.zip", "zip"),
                ],
            ),
            // Empty volume: only the three metadata entries in the root.
            media_spec("empty volume", vec![]),
            // A name needing several name entries, one exactly on the 15-unit
            // boundary, and one at 16 to cross it.
            media_spec(
                "long names",
                vec![
                    Item::Text("/123456789012345", "exactly fifteen"),
                    Item::Text("/1234567890123456", "sixteen, so two"),
                    Item::Text(
                        "/a name of forty-five characters exactly here.txt",
                        "four entries",
                    ),
                ],
            ),
            // Empty files and empty directories: both special cases in allocation.
            media_spec(
                "empty files and directories",
                vec![
                    Item::Dir("/empty-dir"),
                    Item::Text("/empty.txt", ""),
                    Item::Text("/after.txt", "not empty"),
                    Item::Dir("/nested/empty"),
                ],
            ),
            // Mixed case, which is where the up-case keying and the name hash meet.
            media_spec(
                "mixed case names",
                vec![
                    Item::Text("/Sources/Install.wim", "one"),
                    Item::Text("/MiXeD.TxT", "two"),
                    Item::Text("/Ünïcødé.txt", "three"),
                ],
            ),
            // A file spanning many clusters, so the FAT chain is long enough to be
            // wrong in an interesting way.
            media_spec(
                "multi-cluster file",
                vec![Item::Reserved("/big.bin", 40 * 1024 * 1024)],
            ),
            // A small volume, which takes the 32 KiB default cluster size instead.
            Spec {
                name: "small volume",
                size_bytes: 64 * 1024 * 1024,
                label: "OXIDE",
                sectors_per_cluster: None,
                partition_offset_lba: 0,
                items: vec![Item::Text("/a.txt", "a"), Item::Dir("/d")],
            },
            // An explicit cluster size, and a label needing truncation.
            Spec {
                name: "explicit geometry",
                size_bytes: 256 * 1024 * 1024,
                label: "a-very-long-label-indeed",
                sectors_per_cluster: Some(8),
                partition_offset_lba: 1_048_576,
                items: vec![
                    Item::Text("/x.bin", "x"),
                    Item::Reserved("/y.bin", 70_000),
                ],
            },
        ]
    }

    /// Placements have to agree too, or the caller streams `install.wim` into the
    /// wrong place and the volume is quietly wrong where it matters most.
    fn placements_spec() -> Spec {
        media_spec(
            "placements",
            vec![
                Item::Reserved("/sources/install.wim", 4_340_202_461),
                Item::Text("/autorun.inf", "x"),
                Item::Reserved("/sources/install2.wim", 1_000_000),
            ],
        )
    }

    /// The gate: every configuration byte for byte against its committed golden.
    #[test]
    fn matches_the_goldens() {
        for spec in specs() {
            assert_matches_golden(&spec);
        }
    }

    #[test]
    fn placements_match_the_golden() {
        let spec = placements_spec();
        let path = golden_dir().join("placements.json");
        let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| {
            panic!("{}: {e}. Regenerate with dump_js_goldens", path.display())
        });
        let theirs: serde_json::Value = serde_json::from_str(&raw).unwrap();
        let (builder, _) = build_ours(&spec);
        let ours: Vec<serde_json::Value> = builder
            .placements()
            .iter()
            .map(|p| {
                serde_json::json!({
                    "path": p.path, "offset": p.offset, "size": p.size,
                })
            })
            .collect();
        assert_eq!(theirs["placements"], serde_json::Value::Array(ours));
    }

    #[test]
    fn geometry_matches_the_reference_volume() {
        let b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        let g = b.geometry();
        assert_eq!(g.total_sectors, 12_582_912);
        assert_eq!(g.sectors_per_cluster_shift, 8); // 128 KiB clusters
        assert_eq!(g.cluster_bytes, 131_072);
        assert_eq!(g.fat_offset, 2048);
        assert_eq!(g.fat_length, 512);
        assert_eq!(g.cluster_heap_offset, 2560);
        assert_eq!(g.cluster_count, 49_142);
    }

    /// The first sector firmware-independent readers look at, and the checksum over
    /// the eleven sectors after it. Both are fixed by geometry alone, so this compares
    /// against the real volume without needing any of its files.
    #[test]
    fn the_boot_region_matches_the_reference_volume() {
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        let image = b.build().unwrap();
        assert_region(&image, 0, "boot-sector");
        assert_region(&image, SECTOR, "ext-boot-sector");
        assert_region(&image, 11 * SECTOR, "checksum-sector");
        let stored =
            u32::from_le_bytes(image.read(11 * SECTOR, 4).try_into().unwrap());
        assert_eq!(stored, REFERENCE_BOOT_CHECKSUM);
    }

    #[test]
    fn the_backup_boot_region_is_a_copy() {
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        let image = b.build().unwrap();
        let main = image.read(0, 12 * SECTOR as usize);
        let backup = image.read(12 * SECTOR, 12 * SECTOR as usize);
        assert_eq!(main, backup);
    }

    /// The three entries every exFAT root carries. Independent of the file tree, so
    /// this too is checked against the real volume hermetically.
    #[test]
    fn the_root_metadata_entries_match_the_reference_volume() {
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        let image = b.build().unwrap();
        // Bitmap at cluster 2, up-case at 3, root at 4, whatever the volume holds.
        let root = (2560 + (4 - 2) * 256) * SECTOR;
        assert_region(&image, root, "root-metadata");
        // Only the first five FAT entries are fixed by geometry; the rest describe
        // files and are compared against exfat.js instead.
        assert_region(&image, 2048 * SECTOR, "fat-head");
    }

    /// 131072 bytes of derived Unicode data, pinned by four bytes from the image that
    /// booted. If Rust's Unicode tables ever move, this is where it shows.
    #[test]
    fn the_upcase_table_is_the_one_that_booted() {
        let table = upcase_table();
        assert_eq!(table.len(), UPCASE_BYTES);
        assert_eq!(checksum32(&table), REFERENCE_UPCASE_CHECKSUM);

        let entry = |c: u32| {
            u16::from_le_bytes([
                table[c as usize * 2],
                table[c as usize * 2 + 1],
            ])
        };
        assert_eq!(entry('a' as u32), 'A' as u16);
        assert_eq!(entry('A' as u32), 'A' as u16);
        assert_eq!(entry('7' as u32), '7' as u16);
        // A mapping that expands to two characters is not a simple mapping, so the
        // character stays as itself.
        assert_eq!(entry(0x00df), 0x00df); // sharp s
        assert_eq!(entry(0xfb01), 0xfb01); // fi ligature
        // A one-to-one mapping outside ASCII is taken.
        assert_eq!(entry(0x00e9), 0x00c9); // é -> É
        assert_eq!(entry(0x0131), 'I' as u16); // dotless i
        // Surrogates have no case mapping and pass through.
        assert_eq!(entry(0xd800), 0xd800);
        assert_eq!(entry(0xdfff), 0xdfff);
    }

    #[test]
    fn a_volume_too_small_is_refused() {
        for size in [0, 512, 1024 * 1024] {
            assert!(
                ExFatBuilder::new(Options {
                    size_bytes: size,
                    ..Options::default()
                })
                .is_err(),
                "{size} bytes should be refused"
            );
        }
    }

    #[test]
    fn contents_larger_than_the_volume_are_refused() {
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        b.reserve_file("/big.bin", 7 * 1024 * 1024 * 1024).unwrap();
        let err = b.build().err().unwrap().to_string();
        assert!(err.contains("volume holds"), "unhelpful error: {err}");
    }

    /// exFAT's whole reason for existing here: a file FAT32 cannot hold.
    #[test]
    fn a_file_over_four_gib_is_accepted() {
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        b.reserve_file("/sources/install.wim", 4_340_202_461).unwrap();
        b.build().unwrap();
        let placement = &b.placements()[0];
        assert_eq!(placement.size, 4_340_202_461);
        // And the size lands in the stream extension as a 64-bit value, which is the
        // part FAT32 structurally cannot express.
        assert_eq!(placement.path, "/sources/install.wim");
    }

    #[test]
    fn every_allocation_gets_a_fat_chain() {
        // Files set NoFatChain and do not need one, but the bitmap, up-case table and
        // root directory have no such flag — their chains must be in the FAT or the
        // volume will not mount at all.
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        b.reserve_file("/big.bin", 400_000).unwrap(); // four clusters
        let image = b.build().unwrap();
        let fat = 2048 * SECTOR;
        let read = |cluster: u32| {
            u32::from_le_bytes(
                image.read(fat + cluster as u64 * 4, 4).try_into().unwrap(),
            )
        };
        assert_eq!(read(0), 0xffff_fff8); // media descriptor
        assert_eq!(read(1), 0xffff_ffff);
        assert_eq!(read(2), 0xffff_ffff); // bitmap, one cluster
        assert_eq!(read(3), 0xffff_ffff); // up-case table, one cluster
        assert_eq!(read(4), 0xffff_ffff); // root directory
        // The file: four clusters chained, then end of chain.
        assert_eq!(read(5), 6);
        assert_eq!(read(6), 7);
        assert_eq!(read(7), 8);
        assert_eq!(read(8), 0xffff_ffff);
    }

    #[test]
    fn the_bitmap_marks_exactly_the_used_clusters() {
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        b.reserve_file("/big.bin", 400_000).unwrap();
        let image = b.build().unwrap();
        // bitmap, up-case, root, four file clusters: seven, from cluster 2.
        let bytes = image.read(2560 * SECTOR, 2);
        assert_eq!(bytes[0], 0b0111_1111);
        assert_eq!(bytes[1], 0);
    }

    #[test]
    fn an_empty_file_names_cluster_zero_and_takes_no_space() {
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        b.add_file("/empty.txt", Vec::new()).unwrap();
        b.add_file("/after.txt", b"x".to_vec()).unwrap();
        b.build().unwrap();
        let empty = b.child(ROOT, "EMPTY.TXT").unwrap();
        let after = b.child(ROOT, "AFTER.TXT").unwrap();
        assert_eq!(b.nodes[empty].first_cluster, 0);
        // Root is cluster 4, so the next real allocation is 5 — the empty file did not
        // consume it.
        assert_eq!(b.nodes[after].first_cluster, 5);
    }

    /// An empty directory still needs somewhere to be.
    #[test]
    fn an_empty_directory_gets_a_cluster() {
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        b.add_dir("/empty").unwrap();
        b.build().unwrap();
        let dir = b.child(ROOT, "EMPTY").unwrap();
        assert_eq!(b.nodes[dir].cluster_count, 1);
        assert_eq!(b.nodes[dir].first_cluster, 5);
        // And its directory entry reports zero bytes, because it holds no entries.
        assert_eq!(b.nodes[dir].entry_count, 0);
    }

    /// exFAT has no "." or ".." entries, unlike FAT32. A subdirectory's size counts
    /// only its children, so getting this wrong makes a directory look empty.
    #[test]
    fn a_subdirectory_counts_only_its_children() {
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        b.add_file("/dir/a.txt", b"a".to_vec()).unwrap();
        b.add_file("/dir/b.txt", b"b".to_vec()).unwrap();
        b.build().unwrap();
        let dir = b.child(ROOT, "DIR").unwrap();
        // Two files, each a file entry, a stream extension and one name entry.
        assert_eq!(b.nodes[dir].entry_count, 6);
        // The root has the three metadata entries plus one three-entry set for "dir".
        assert_eq!(b.nodes[ROOT].entry_count, 6);
    }

    #[test]
    fn name_hashes_are_case_folded() {
        assert_eq!(name_hash("autorun.inf"), name_hash("AUTORUN.INF"));
        assert_eq!(name_hash("Sources"), name_hash("SOURCES"));
        assert_ne!(name_hash("boot"), name_hash("bootx"));
        // 0xf7 is division sign, not a letter, so it is not folded — the one exception
        // in the Latin-1 range.
        assert_ne!(name_hash("\u{f7}"), name_hash("\u{d7}"));
    }

    #[test]
    fn a_name_outside_the_bmp_is_refused_with_an_explanation() {
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        let err = b.add_file("/emoji \u{1f600}.txt", Vec::new()).err().unwrap();
        assert!(err.to_string().contains("outside the range"), "{err}");
    }

    #[test]
    fn a_file_where_a_directory_is_expected_is_refused() {
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        b.add_file("/sources", b"not a directory".to_vec()).unwrap();
        assert!(b.add_file("/sources/install.wim", Vec::new()).is_err());
    }

    #[test]
    fn adding_the_same_path_twice_replaces_it_in_place() {
        let mut b = ExFatBuilder::new(Options::media(MEDIA_SECTORS, MEDIA_LBA))
            .unwrap();
        b.add_file("/sources/EI.CFG", b"first".to_vec()).unwrap();
        b.add_file("/a.txt", b"a".to_vec()).unwrap();
        b.add_file("/sources/ei.cfg", b"second".to_vec()).unwrap();
        let sources = b.child(ROOT, "SOURCES").unwrap();
        assert_eq!(b.nodes[sources].children.len(), 1);
        let file = b.child(sources, "EI.CFG").unwrap();
        assert_eq!(b.nodes[file].data.as_deref(), Some(&b"second"[..]));
        assert_eq!(b.nodes[ROOT].children[0].0, "SOURCES");
    }

    #[test]
    fn the_label_is_upper_cased_and_truncated() {
        let b = ExFatBuilder::new(Options {
            label: "a-rather-long-label".to_string(),
            ..Options::media(MEDIA_SECTORS, MEDIA_LBA)
        })
        .unwrap();
        assert_eq!(b.label, "A-RATHER-LO");
    }

    #[test]
    fn timestamps_have_no_time_zone_in_them() {
        assert_eq!(
            Timestamp::from_civil(2020, 1, 1, 0, 0, 0).unwrap(),
            Timestamp::MEDIA_EPOCH
        );
        // What the reference volume actually carries: the US/Eastern rendering of the
        // midnight UTC it was asked for, before the local-time-getter fix.
        assert_eq!(
            Timestamp::from_civil(2019, 12, 31, 19, 0, 0).unwrap().0,
            0x4f9f_9800
        );
        assert!(Timestamp::from_civil(1979, 1, 1, 0, 0, 0).is_err());
        assert!(Timestamp::from_civil(2020, 1, 1, 0, 60, 0).is_err());
    }
}
