// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Copyright 2026 Oxide Computer Company

//! This workspace is MPL-2.0, but the image it builds is mostly not ours: virtio guest
//! drivers, Win32-OpenSSH, a UEFI Shell, three filesystem drivers and a chain loader.
//! **Two of those are copyleft** — `uefintfs.efi` is GPL-2.0-or-later and the three
//! `efifs` drivers are GPL-3.0-or-later, being GRUB2-derived — so every release of this
//! tool conveys GPL'd object code and owes the corresponding notices and source.
//!
//! These are standalone UEFI executables, unmodified, loaded and run by firmware in its own
//! context; nothing here links against them or shares data structures with them, so the
//! MPL code stays MPL under GPLv2 §2 / GPLv3 §5 mere aggregation. `build.rs` does
//! `include_bytes!` the whole payload into one binary, see THIRD-PARTY.md.
//!
//! Why the notices live here and not in `payload-manifest.json`, which would otherwise be
//! the natural home:
//!
//! - The manifest is generated by `fetch-payload.sh` into a gitignored `assets/`, so a
//!   fresh clone would have no notices at all and a reader of the repository could not
//!   find the terms.
//! - The manifest is only as present as the payload is. A build with no payload still
//!   ships this table, which is the case where getting it wrong is cheapest and least
//!   noticed.
//! - Adding fields to the manifest would change the embedded payload and therefore the
//!   fingerprint, for a change that carries no bytes onto any volume.
//!
//! The license texts are committed under `licenses/` and `include_str!`d, which is the
//! one exception to the ground rule that third-party files are not committed: that rule
//! exists to keep binaries out of the tree, and a license text is precisely the thing
//! that has to travel with the artifact rather than be fetched by whoever builds it.
//!
//! The versions here are duplicated from `tools/fetch-payload.sh`, so
//! `every_pinned_version_is_accounted_for` reads that script and requires them to agree.
//! One constant in two places has already drifted once in this workspace and skipped the
//! bootstrap script on every install.

/// The terms one payload component is under.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum License {
    /// `uefi-ntfs`. Its `LICENSE.txt` is the GPLv2 text and `boot.c` says "either
    /// version 2 of the License, or (at your option) any later version".
    Gpl2OrLater,
    /// `efifs`, which is GPLv3+ because the drivers are GRUB 2.0 read-only drivers.
    Gpl3OrLater,
    /// EDK2, and therefore the UEFI Shell binary built from it.
    Bsd2ClausePatent,
    /// The virtio-win guest drivers.
    Bsd3Clause,
    /// OpenSSH's own summary file, which is a collection of BSD-and-freer terms rather
    /// than one nameable license.
    OpenSsh,
}

impl License {
    /// The SPDX identifier, or the closest thing to one.
    pub fn spdx(self) -> &'static str {
        match self {
            Self::Gpl2OrLater => "GPL-2.0-or-later",
            Self::Gpl3OrLater => "GPL-3.0-or-later",
            Self::Bsd2ClausePatent => "BSD-2-Clause-Patent",
            Self::Bsd3Clause => "BSD-3-Clause",
            Self::OpenSsh => "OpenSSH (BSD-style, see text)",
        }
    }

    /// Whether conveying this component obliges us to offer its source.
    pub fn is_copyleft(self) -> bool {
        matches!(self, Self::Gpl2OrLater | Self::Gpl3OrLater)
    }

    /// The full text, as committed under `licenses/`.
    pub fn text(self) -> &'static str {
        match self {
            Self::Gpl2OrLater => {
                include_str!("../../../licenses/GPL-2.0.txt")
            }
            Self::Gpl3OrLater => {
                include_str!("../../../licenses/GPL-3.0.txt")
            }
            Self::Bsd2ClausePatent => {
                include_str!("../../../licenses/BSD-2-Clause-Patent.txt")
            }
            Self::Bsd3Clause => {
                include_str!("../../../licenses/BSD-3-Clause-virtio-win.txt")
            }
            Self::OpenSsh => include_str!("../../../licenses/OpenSSH.txt"),
        }
    }
}

/// One third-party component the built image carries.
#[derive(Debug, Clone, Copy)]
pub struct Component {
    /// Upstream's name for it.
    pub name: &'static str,
    /// The exact version fetched, matching `tools/fetch-payload.sh`.
    pub version: &'static str,
    /// What it becomes on the media, so a reader can tie a notice to a file.
    pub carried_as: &'static str,
    pub license: License,
    pub copyright: &'static str,
    /// The project.
    pub upstream: &'static str,
    /// Corresponding source **for this version**, not for HEAD. GPLv3 §6 is about the
    /// source of the object code that was actually conveyed.
    pub source: &'static str,
}

/// Every third-party component embedded in this binary and written onto an image.
///
/// Ordered copyleft first, because that is the part with obligations attached and the
/// part someone reading this output is looking for.
pub static PAYLOAD: &[Component] = &[
    Component {
        name: "uefi-ntfs",
        version: "v2.8",
        carried_as: "EFI/BOOT/uefintfs.efi on the ESP, chainloaded by \
                     startup.nsh",
        license: License::Gpl2OrLater,
        copyright: "Copyright © 2014-2025 Pete Batard <pete@akeo.ie>, \
                    with parts from rEFInd © 2012-2016 Roderick W. Smith",
        upstream: "https://github.com/pbatard/uefi-ntfs",
        source: "https://github.com/pbatard/uefi-ntfs/archive/refs/tags/v2.8.tar.gz",
    },
    Component {
        name: "efifs",
        version: "v1.12",
        // udf_x64.efi and iso9660_x64.efi are fetched and embedded but no volume
        // currently carries them — `boot_partition` writes the exFAT driver only.
        // Still conveyed, because they are inside the binary, so still owed a notice.
        carried_as: "EFI/Rufus/exfat_x64.efi on the ESP; udf_x64.efi and \
                     iso9660_x64.efi embedded but not written to a volume",
        license: License::Gpl3OrLater,
        copyright: "Copyright © 2014-2021 Pete Batard <pete@akeo.ie>, \
                    derived from GRUB 2.0 read-only filesystem drivers, \
                    © Free Software Foundation, Inc. and contributors",
        upstream: "https://github.com/pbatard/efifs",
        source: "https://github.com/pbatard/efifs/archive/refs/tags/v1.12.tar.gz",
    },
    Component {
        name: "UEFI-Shell",
        version: "26H1",
        carried_as: "EFI/BOOT/BOOTX64.EFI on the ESP, from shellx64.efi — it \
                     is the boot entry the firmware runs",
        license: License::Bsd2ClausePatent,
        copyright: "Copyright © 2019 TianoCore and contributors; \
                    release packaging © Pete Batard <pete@akeo.ie>",
        upstream: "https://github.com/pbatard/UEFI-Shell",
        source: "https://github.com/pbatard/UEFI-Shell/archive/refs/tags/26H1.tar.gz",
    },
    Component {
        name: "virtio-win guest drivers",
        version: "0.1.285-1",
        carried_as: "/drivers/<driver>/ on the exFAT volume, injected by the \
                     answer file",
        license: License::Bsd3Clause,
        copyright: "Copyright 2009-2025 Red Hat, Inc. and/or its affiliates; \
                    2016 Google, Inc.; 2016 Virtuozzo, Inc.; 2007 IBM Corporation",
        upstream: "https://github.com/virtio-win/kvm-guest-drivers-windows",
        source: "https://fedorapeople.org/groups/virt/virtio-win/\
                 direct-downloads/archive-virtio/virtio-win-0.1.285-1/",
    },
    Component {
        name: "Win32-OpenSSH",
        version: "10.0.0.0p2-Preview",
        carried_as: "/openssh/OpenSSH-Win64.zip on the exFAT volume, installed \
                     by the bootstrap script. Its own LICENSE.txt and NOTICE.txt \
                     travel inside that zip",
        license: License::OpenSsh,
        copyright: "Copyright © 1995 Tatu Ylonen, © 1999-2025 the OpenSSH \
                    contributors, and © Microsoft Corporation for the Windows port",
        upstream: "https://github.com/PowerShell/Win32-OpenSSH",
        source: "https://github.com/PowerShell/Win32-OpenSSH/archive/refs/tags/\
                 10.0.0.0p2-Preview.tar.gz",
    },
];

/// The notices, without the license texts. What `oxwin licenses` prints.
///
/// Written rather than derived from the payload table in `assets`, because it has to say
/// something true in a build with no payload embedded: someone asking what the terms are
/// is asking about the tool, not about whether this particular checkout has run the
/// fetch script.
pub fn summary() -> String {
    let mut out = String::from(
        "oxwin is Copyright 2026 Oxide Computer Company and is licensed \
         MPL-2.0.\n\nThe images it builds carry third-party software, embedded \
         in this binary and\nwritten onto the media unmodified:\n",
    );
    for c in PAYLOAD {
        out += &format!(
            "\n  {} {}\n    {}\n    carried as: {}\n    {}\n    upstream:   {}\n    \
             source:     {}\n",
            c.name,
            c.version,
            c.license.spdx(),
            c.carried_as,
            c.copyright,
            c.upstream,
            c.source,
        );
    }
    out += "\nThe GPL'd components are separate UEFI executables, conveyed \
            unmodified and\nrun by firmware rather than linked into this \
            program. Their complete\ncorresponding source is at the URLs above, \
            pinned to the versions shipped; ask\noxide.computer for a copy on \
            physical media if those are unreachable.\n\nRun `oxwin licenses \
            --full` for the license texts, or see THIRD-PARTY.md.\n";
    out
}

/// The notices plus every license text, each printed once.
pub fn full() -> String {
    let mut out = summary();
    let mut done: Vec<&'static str> = Vec::new();
    for c in PAYLOAD {
        let spdx = c.license.spdx();
        if done.contains(&spdx) {
            continue;
        }
        done.push(spdx);
        out += &format!(
            "\n\n{}\n{spdx}\n{}\n\n{}",
            "=".repeat(76),
            "=".repeat(76),
            c.license.text()
        );
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The one real risk in this file: a version bumped in `fetch-payload.sh` and not
    /// here, so the notices name terms for a component nobody ships any more and the
    /// source URL points at the wrong tree.
    ///
    /// Reads the script rather than skipping when it is absent. This workspace is not
    /// published as a crate, so `tools/` is always two directories up; if that ever
    /// stops being true this should fail loudly rather than quietly prove nothing.
    #[test]
    fn every_pinned_version_is_accounted_for() {
        let script = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
            .join("../../tools/fetch-payload.sh");
        let text = std::fs::read_to_string(&script).unwrap_or_else(|e| {
            panic!("{}: {e} — the notices cannot be checked", script.display())
        });

        // Every version the fetch script pins, and the component that must carry it.
        let pins = [
            ("VIRTIO_VERSION", "virtio-win guest drivers"),
            ("OPENSSH_VERSION", "Win32-OpenSSH"),
            ("EFIFS_VERSION", "efifs"),
            ("UEFI_SHELL_VERSION", "UEFI-Shell"),
            ("UEFI_NTFS_VERSION", "uefi-ntfs"),
        ];
        for (var, name) in pins {
            let prefix = format!("{var}=");
            let value = text
                .lines()
                .find_map(|l| l.trim().strip_prefix(&prefix))
                .map(|v| v.trim().trim_matches('"').to_string())
                .unwrap_or_else(|| {
                    panic!("{var} is no longer set in fetch-payload.sh")
                });
            let component = PAYLOAD
                .iter()
                .find(|c| c.name == name)
                .unwrap_or_else(|| panic!("no notice names {name}"));
            assert_eq!(
                component.version, value,
                "fetch-payload.sh pins {name} at {value} but the notices say \
                 {} — bump the version, the source URL and THIRD-PARTY.md",
                component.version
            );
        }

        // And nothing here is unpinned: a component in the notices that the script does
        // not fetch is a notice for something we do not ship.
        assert_eq!(
            PAYLOAD.len(),
            pins.len(),
            "the notices list {} components and fetch-payload.sh pins {}",
            PAYLOAD.len(),
            pins.len()
        );
    }

    /// Every license text is really present and really that license. `include_str!` of
    /// a wrong-but-existing file would otherwise ship the GPLv2 text for a GPLv3 work.
    #[test]
    fn every_license_text_is_the_license_it_claims() {
        for (license, marker) in [
            (License::Gpl2OrLater, "Version 2, June 1991"),
            (License::Gpl3OrLater, "Version 3, 29 June 2007"),
            (License::Bsd2ClausePatent, "BSD-2-Clause-Patent"),
            (License::Bsd3Clause, "Red Hat"),
            (License::OpenSsh, "part of the OpenSSH software"),
        ] {
            let text = license.text();
            assert!(
                text.contains(marker),
                "the text for {} does not contain {marker:?}",
                license.spdx()
            );
        }
    }
}
