// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Copyright 2026 Oxide Computer Company

//! `autounattend.xml` generation.
//!
//! Windows Setup scans every attached volume for `autounattend.xml` at boot, which is
//! the trick this whole project rests on: the answer disk needs no bootloader and no
//! cooperation from the install medium.
//!
//! This builds code that is then  tested agaubst the committed goldens in
//! `testdata/unattend/` (see the tests at the bottom). Those goldens were generated by
//! the JavaScript test code that was the v0. That output has installed Windows on real
//! Oxide hardware. An answer file that is subtly wrong does not error, it installs
//! a machine with no network, or no bootstrap, or stalls at a licence page.
//! So the formatting needs to be reproduced exactly, including the blank line an empty
//!  pass leaves behind, rather than tidied up.
//!
//! Two design decisions carried over from the original:
//!
//! * The guest bootstrap runs in `specialize` as SYSTEM, not from
//!   `FirstLogonCommands`. Those need an interactive logon, which means autologon,
//!   which means a console session nobody is watching.
//! * Nothing references the answer disk by drive letter. Letters are not stable across
//!   passes or guests, so the bootstrap is located by scanning filesystem drives.

use crate::settings::{Deployment, Settings, WindowsRelease};
use anyhow::{Result, bail};

/// Label of the volume carrying `autounattend.xml`, `bootstrap.ps1`, drivers and
/// OpenSSH. The image builder must label the volume with this same string.
pub const VOLUME_LABEL: &str = "WINSETUP";

const NS: &str = concat!(
    r#"xmlns="urn:schemas-microsoft-com:unattend" "#,
    r#"xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State""#
);
const ARCH: &str = concat!(
    r#"processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" "#,
    r#"language="neutral" versionScope="nonSxS""#
);

/// `<Path>` is capped at this by the unattend schema. Over it, Setup rejects the whole
/// answer file with a message naming only the pass, which reads like malformed XML.
pub const PATH_LIMIT: usize = 259;

/// Skips A and B (floppies) only. C is included deliberately: when the installer media
/// is the sole volume WinPE mounts it lands on C, and omitting it meant the drivers
/// were never found. Setup tolerates paths that do not resolve, so over-listing costs
/// only log noise.
const DRIVE_LETTERS: &[char] = &['C', 'D', 'E', 'F', 'G', 'H'];

pub fn xml_escape(value: &str) -> String {
    // Ampersand first, or the escapes introduced below get escaped again.
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

/// A Windows release and the editions its media carries.
struct Target {
    /// Oxide instances expose no vTPM and no UEFI Secure Boot, so stock Windows 11
    /// Setup refuses to install without the LabConfig bypasses.
    bypass_hardware_checks: bool,
    editions: Vec<Edition>,
}

struct Edition {
    id: String,
    /// The `/IMAGE/NAME` value, used only when no image index is known.
    name: String,
}

impl Edition {
    fn new(id: &str, name: String) -> Self {
        Self { id: id.to_string(), name }
    }
}

/// The editions on server media, which is one vocabulary across every release.
///
/// Server 2019, 2022 and 2025 ship the same four images with the same ids, differing only
/// in the year in the name — so this is parameterised rather than copy-pasted three
/// times. Copy-pasting is how `datacenter` came to be spelled two ways in one codebase.
///
/// The names must keep their exact spelling: `SERVERDATACENTER` is Desktop Experience and
/// `SERVERDATACENTERCORE` is Core, and a loose match between them installed a server with
/// no desktop once already.
fn server_editions(year: u16) -> Vec<Edition> {
    ["DATACENTER", "STANDARD"]
        .iter()
        .flat_map(|which| {
            let id = which.to_lowercase();
            [
                Edition::new(
                    &id,
                    format!("Windows Server {year} SERVER{which}"),
                ),
                Edition::new(
                    &format!("{id}-core"),
                    format!("Windows Server {year} SERVER{which}CORE"),
                ),
            ]
        })
        .collect()
}

/// The editions on client media.
///
/// Far more than server media carries, and the choice matters beyond the name: **Home has
/// no RDP host and cannot domain-join**, so it is reachable over SSH and the serial
/// console and not by Remote Desktop. There is no Core variant — `INSTALLATIONTYPE` is
/// `Client` on every image, which is also why Windows 11 Home being `FLAGS=Core` fooled
/// the old Core test.
fn client_editions(release: &str) -> Vec<Edition> {
    ["Home", "Pro", "Education", "Enterprise"]
        .iter()
        .map(|name| {
            Edition::new(&name.to_lowercase(), format!("{release} {name}"))
        })
        .collect()
}

fn target_for(release: WindowsRelease) -> Result<Target> {
    // Public KMS client setup keys are deliberately not carried over: nothing here
    // activates Windows, and the only reason the original held them was to stop Setup
    // asking for a key, which omitting <ProductKey> already achieves.
    //
    // The bypasses key off client-ness rather than naming Windows 11, so whatever client
    // release ships next gets them without anyone remembering to add it. Windows 10 does
    // not need them and is given them anyway: the keys are inert on firmware that has a
    // vTPM and on Setup that does not look, whereas a client release that needed them and
    // did not get them refuses to install at all.
    let editions = match release {
        WindowsRelease::Server2019 => server_editions(2019),
        WindowsRelease::Server2022 => server_editions(2022),
        WindowsRelease::Server2025 => server_editions(2025),
        WindowsRelease::Windows10 => client_editions("Windows 10"),
        WindowsRelease::Windows11 => client_editions("Windows 11"),
    };
    Ok(Target { bypass_hardware_checks: release.is_client(), editions })
}

/// Everything the answer file needs. Deliberately lower level than [`Settings`]: it
/// carries the fields only the orchestration layer knows (`image_index`) and the
/// diagnostic escape hatches the UI does not expose, so the answer file can be generated
/// and inspected without a UI in the loop.
#[derive(Debug, Clone)]
pub struct Config {
    pub release: WindowsRelease,
    /// Edition id, e.g. `datacenter` or `datacenter-core`.
    pub edition: String,
    pub computer_name: String,
    pub username: String,
    pub password: String,
    pub enable_rdp: bool,
    pub inject_drivers: bool,
    pub enable_serial_console: bool,
    pub target_disk: u8,
    pub locale: String,
    pub timezone: String,
    pub product_key: Option<String>,
    /// Console autologon. For debugging installs only.
    pub auto_logon: bool,
    /// Where Setup writes `setupact.log` and `setuperr.log`.
    ///
    /// `None` leaves Setup's default, which during `windowsPE` is the WinPE RAM disk — so
    /// an install that stalls there takes its own explanation down with it on reset. That
    /// is why a rack hang has been unreadable. Point this at the installer volume, which
    /// is writable and survives, and the logs can be read afterwards by attaching that
    /// disk to a machine that works.
    ///
    /// The path has to be a literal, and WinPE drive letters are not stable — the media
    /// is usually `C:` when the target disk is still unformatted, but nothing guarantees
    /// it. Diagnostic, not something to depend on.
    pub log_path: Option<String>,
    /// `OnError` on every `WillShowUI`, which is the shipped behaviour, or `Never`.
    ///
    /// **On an Oxide guest `OnError` means an infinite hang.** There is no console to show
    /// UI on, so Setup waits forever for a click nobody can make, and from the outside
    /// that is indistinguishable from a slow install. `Never` makes it fail fast instead —
    /// worse for a human at a keyboard, far better for a machine nobody is watching.
    pub show_ui_on_error: bool,
    /// Emit a serial marker at the end of `windowsPE` and the start of `specialize`, not
    /// only at the start of `windowsPE`.
    ///
    /// Diagnostic, and off by default so the answer file stays byte-identical to the one
    /// that has installed on a rack. With one marker a hang is only ever "it started";
    /// with three, the console says which pass it died in — and Setup renders to graphics
    /// an Oxide instance does not have, so these markers are the only view there is.
    pub verbose_serial: bool,
    /// Index of the image to install, read from the WIM's own metadata. Preferred over
    /// a name: names vary across retail, evaluation, OEM and localised media, so a
    /// hardcoded name silently matches nothing and Setup shows an empty edition list.
    pub image_index: Option<u32>,
    /// Diagnostic escape hatch: drop `<ImageInstall>` so Setup picks the edition and
    /// resolves the licence itself.
    pub skip_image_install: bool,
    /// Explicit path to `install.wim`, when it is not on the booted volume.
    pub install_from: Option<String>,
    pub install_from_letter: Option<char>,
    /// Volume label to pin to a drive letter with diskpart before Setup looks for
    /// `install.wim`.
    pub install_from_label: Option<String>,
    /// Public keys authorised for SSH. Read only by the bootstrap script — the answer
    /// file has nowhere to put them, since the account does not exist until
    /// `oobeSystem` and sshd is configured in `specialize`.
    pub ssh_keys: Vec<String>,
    /// Install and start OpenSSH in the guest. Also read only by the bootstrap.
    pub enable_ssh: bool,
}

impl Config {
    /// Build a config from the user-facing settings. Everything the UI does not expose
    /// takes the value the current builder uses.
    pub fn from_settings(
        settings: &Settings,
        image_index: Option<u32>,
    ) -> Self {
        Self {
            release: settings.release,
            // One convention, not two. This used to append `-core` here while
            // `Settings::edition_hint` appended `core`, for the same fact — and neither
            // spelling is needed now that Core-ness is a property of the image the user
            // picked out of the media's own list rather than a separate switch.
            edition: settings.edition.trim().to_lowercase(),
            computer_name: match &settings.deployment {
                Deployment::GoldenImage => "*".to_string(),
                Deployment::Named { hostname } => hostname.clone(),
            },
            username: settings.credentials.username.clone(),
            password: settings.credentials.password.clone(),
            enable_rdp: settings.enable_rdp,
            inject_drivers: settings.inject_drivers,
            enable_serial_console: settings.enable_serial_console,
            target_disk: settings.target_disk,
            locale: "en-US".into(),
            timezone: "UTC".into(),
            product_key: settings.product_key.clone(),
            auto_logon: false,
            log_path: None,
            show_ui_on_error: true,
            verbose_serial: false,
            image_index,
            skip_image_install: false,
            install_from: None,
            install_from_letter: None,
            install_from_label: None,
            ssh_keys: settings.credentials.keys.clone(),
            enable_ssh: true,
        }
    }
}

/// One entry in a `<RunSynchronous>` block.
struct Command {
    path: String,
    description: String,
}

/// `OnError` or `Never` for every `WillShowUI` in the answer file.
///
/// One function rather than three literals: the whole point is that they agree, and this
/// codebase has already been bitten twice by one fact spelled two ways.
fn will_show_ui(config: &Config) -> &'static str {
    if config.show_ui_on_error { "OnError" } else { "Never" }
}

pub fn build(config: &Config) -> Result<String> {
    let target = target_for(config.release)?;
    // The edition is needed for exactly one thing: the `/IMAGE/NAME` written when no
    // image index is known. With an index it is dead weight, so an unrecognised one is
    // only fatal without an index — which is what lets the caller select an image by
    // number, or by anything else the WIM's own list offers, without also having to name
    // it in a table here. Requiring it turned a Windows 11 ISO into "unknown win11
    // edition \"datacenter\"", which describes our table rather than the user's media.
    let unnamed = Edition::new("", String::new());
    let found = target.editions.iter().find(|e| e.id == config.edition);
    let edition = match (found, config.image_index) {
        (Some(edition), _) => edition,
        (None, Some(_)) => &unnamed,
        (None, None) => bail!(
            "no image index, and {:?} is not a known {} edition — this release has {}",
            config.edition,
            config.release.token(),
            target
                .editions
                .iter()
                .map(|e| e.id.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        ),
    };

    // Joined with a newline, exactly as the original does — which means a pass that
    // returns an empty string leaves a blank line in the output. Preserved on purpose:
    // the reference file has it, and this is a byte-for-byte port.
    let settings = [
        windows_pe_pass(config, &target, edition)?,
        offline_servicing_pass(config),
        specialize_pass(config)?,
        oobe_pass(config),
    ];

    Ok(format!(
        "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<unattend {NS}>\n{}\n</unattend>\n",
        settings.join("\n")
    ))
}

fn driver_paths() -> String {
    DRIVE_LETTERS
        .iter()
        .enumerate()
        .map(|(i, letter)| {
            format!(
                "        <PathAndCredentials wcm:action=\"add\" wcm:keyValue=\"{}\">\n\
                 \x20         <Path>{letter}:\\drivers</Path>\n\
                 \x20       </PathAndCredentials>",
                i + 1
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn run_synchronous_commands(commands: &[Command]) -> String {
    commands
        .iter()
        .enumerate()
        .map(|(i, c)| {
            format!(
                "        <RunSynchronousCommand wcm:action=\"add\">\n\
                 \x20         <Order>{}</Order>\n\
                 \x20         <Path>{}</Path>\n\
                 \x20         <Description>{}</Description>\n\
                 \x20       </RunSynchronousCommand>",
                i + 1,
                xml_escape(&c.path),
                xml_escape(&c.description)
            )
        })
        .collect::<Vec<_>>()
        .join("\n")
}

fn windows_pe_pass(
    config: &Config,
    target: &Target,
    edition: &Edition,
) -> Result<String> {
    let locale = xml_escape(&config.locale);
    let mut components: Vec<String> = Vec::new();

    components.push(format!(
        "    <component name=\"Microsoft-Windows-International-Core-WinPE\" {ARCH}>\n\
         \x20     <SetupUILanguage>\n\
         \x20       <UILanguage>{locale}</UILanguage>\n\
         \x20     </SetupUILanguage>\n\
         \x20     <InputLocale>{locale}</InputLocale>\n\
         \x20     <SystemLocale>{locale}</SystemLocale>\n\
         \x20     <UILanguage>{locale}</UILanguage>\n\
         \x20     <UserLocale>{locale}</UserLocale>\n\
         \x20   </component>"
    ));

    if config.inject_drivers {
        // WinPE assigns drive letters in enumeration order and they cannot be
        // predicted, so every plausible letter is listed. Setup logs a miss and moves
        // on, which makes this safe if noisy.
        components.push(format!(
            "    <component name=\"Microsoft-Windows-PnpCustomizationsWinPE\" {ARCH}>\n\
             \x20     <DriverPaths>\n{}\n\
             \x20     </DriverPaths>\n\
             \x20   </component>",
            driver_paths()
        ));
    }

    let mut setup_commands: Vec<Command> = Vec::new();

    // Progress markers on COM1. Windows Setup renders only to graphics and an Oxide
    // instance has none, so without these an install is completely silent until the
    // installed OS brings up SAC — which can be twenty minutes of nothing. COM1 is
    // free during windowsPE; EMS is configured for the installed OS in specialize.
    //
    // No space before the redirect (`echo x>COM1`) or the space becomes part of the
    // output, and `& exit /b 0` because a non-zero exit from a RunSynchronousCommand
    // aborts Setup.
    setup_commands.push(Command {
        path: "cmd.exe /c echo OXIDE-STAGE windowsPE-begin>COM1 & exit /b 0"
            .into(),
        description: "Serial progress marker: windowsPE-begin".into(),
    });

    if target.bypass_hardware_checks {
        // One command per key. Chaining all five with && makes a 408-character
        // <Path>, over the 259 limit, and Setup then rejects the entire answer file.
        for check in [
            "BypassTPMCheck",
            "BypassSecureBootCheck",
            "BypassRAMCheck",
            "BypassCPUCheck",
            "BypassStorageCheck",
        ] {
            setup_commands.push(Command {
                path: format!(
                    "cmd.exe /c reg add HKLM\\System\\Setup\\LabConfig \
                     /v {check} /t REG_DWORD /d 1 /f"
                ),
                description: format!("Bypass Windows 11 {check}"),
            });
        }
    }

    if let Some(label) = &config.install_from_label {
        // install.wim on a second partition: Setup will not go looking for it, and
        // WinPE letters depend on how many disks are attached, so pin the volume to a
        // known letter by label first. diskpart takes a label directly and is always
        // present in WinPE, where PowerShell is not.
        let letter = config.install_from_letter.unwrap_or('W');
        let script = "X:\\oxide-diskpart.txt";
        setup_commands.push(Command {
            path: format!(
                "cmd.exe /c echo select volume={label} noerr>{script}\
                 \x20& echo remove noerr>>{script}\
                 \x20& echo assign letter={letter} noerr>>{script}\
                 \x20& diskpart /s {script}\
                 \x20& exit /b 0"
            ),
            description: format!(
                "Assign {letter}: to the volume labelled {label}"
            ),
        });
    }

    if config.verbose_serial {
        setup_commands.push(Command {
            path: "cmd.exe /c echo OXIDE-STAGE windowsPE-end>COM1 & exit /b 0"
                .into(),
            description: "Serial progress marker: windowsPE-end".into(),
        });
    }

    let run_sync = if setup_commands.is_empty() {
        String::new()
    } else {
        format!(
            "      <RunSynchronous>\n{}\n      </RunSynchronous>\n",
            run_synchronous_commands(&setup_commands)
        )
    };

    let image_install = if config.skip_image_install {
        String::new()
    } else {
        // Setup resolves sources\install.wim relative to the volume it booted from.
        // When install.wim lives elsewhere it has to be named explicitly or Setup
        // reports a missing media driver.
        let install_from =
            match (&config.install_from, config.install_from_letter) {
                (Some(path), _) => {
                    format!("            <Path>{}</Path>\n", xml_escape(path))
                }
                (None, Some(letter)) => format!(
                    "            <Path>{}</Path>\n",
                    xml_escape(&format!("{letter}:\\sources\\install.wim"))
                ),
                (None, None) => String::new(),
            };
        let metadata = match config.image_index {
            Some(index) => format!(
                "            <MetaData wcm:action=\"add\">\n\
                 \x20             <Key>/IMAGE/INDEX</Key>\n\
                 \x20             <Value>{index}</Value>\n\
                 \x20           </MetaData>"
            ),
            None => format!(
                "            <MetaData wcm:action=\"add\">\n\
                 \x20             <Key>/IMAGE/NAME</Key>\n\
                 \x20             <Value>{}</Value>\n\
                 \x20           </MetaData>",
                xml_escape(&edition.name)
            ),
        };
        format!(
            "      <ImageInstall>\n\
             \x20       <OSImage>\n\
             \x20         <InstallFrom>\n\
             {install_from}{metadata}\n\
             \x20         </InstallFrom>\n\
             \x20         <InstallTo>\n\
             \x20           <DiskID>{disk}</DiskID>\n\
             \x20           <PartitionID>3</PartitionID>\n\
             \x20         </InstallTo>\n\
             \x20         <WillShowUI>{ui}</WillShowUI>\n\
             \x20       </OSImage>\n\
             \x20     </ImageInstall>\n",
            disk = config.target_disk,
            ui = will_show_ui(config)
        )
    };

    // Omit <ProductKey> entirely when there is no key. An *empty* <Key> is not the
    // same as no key: Setup treats it as a key to resolve, matches no edition, and
    // fails with "Windows cannot find the Microsoft Software License Terms" before it
    // shows any page, because the licence lookup is downstream of edition resolution.
    // That cost a day. When a key *is* given it filters the image list to editions it
    // is valid for, so a retail key against evaluation media matches nothing.
    let product_key = match &config.product_key {
        Some(key) => format!(
            "        <ProductKey>\n\
             \x20         <Key>{}</Key>\n\
             \x20         <WillShowUI>{ui}</WillShowUI>\n\
             \x20       </ProductKey>\n",
            xml_escape(key),
            ui = will_show_ui(config)
        ),
        None => String::new(),
    };

    components.push(format!(
        "    <component name=\"Microsoft-Windows-Setup\" {ARCH}>\n\
         {run_sync}      {log_path}<DiskConfiguration>\n\
         \x20       <WillShowUI>{ui}</WillShowUI>\n\
         \x20       <Disk wcm:action=\"add\">\n\
         \x20         <DiskID>{disk}</DiskID>\n\
         \x20         <WillWipeDisk>true</WillWipeDisk>\n\
         \x20         <CreatePartitions>\n\
         \x20           <CreatePartition wcm:action=\"add\">\n\
         \x20             <Order>1</Order>\n\
         \x20             <Type>EFI</Type>\n\
         \x20             <Size>260</Size>\n\
         \x20           </CreatePartition>\n\
         \x20           <CreatePartition wcm:action=\"add\">\n\
         \x20             <Order>2</Order>\n\
         \x20             <Type>MSR</Type>\n\
         \x20             <Size>16</Size>\n\
         \x20           </CreatePartition>\n\
         \x20           <CreatePartition wcm:action=\"add\">\n\
         \x20             <Order>3</Order>\n\
         \x20             <Type>Primary</Type>\n\
         \x20             <Extend>true</Extend>\n\
         \x20           </CreatePartition>\n\
         \x20         </CreatePartitions>\n\
         \x20         <ModifyPartitions>\n\
         \x20           <ModifyPartition wcm:action=\"add\">\n\
         \x20             <Order>1</Order>\n\
         \x20             <PartitionID>1</PartitionID>\n\
         \x20             <Label>System</Label>\n\
         \x20             <Format>FAT32</Format>\n\
         \x20           </ModifyPartition>\n\
         \x20           <ModifyPartition wcm:action=\"add\">\n\
         \x20             <Order>2</Order>\n\
         \x20             <PartitionID>2</PartitionID>\n\
         \x20           </ModifyPartition>\n\
         \x20           <ModifyPartition wcm:action=\"add\">\n\
         \x20             <Order>3</Order>\n\
         \x20             <PartitionID>3</PartitionID>\n\
         \x20             <Label>Windows</Label>\n\
         \x20             <Letter>C</Letter>\n\
         \x20             <Format>NTFS</Format>\n\
         \x20           </ModifyPartition>\n\
         \x20         </ModifyPartitions>\n\
         \x20       </Disk>\n\
         \x20     </DiskConfiguration>\n\
         {image_install}      <UpgradeData>\n\
         \x20       <Upgrade>false</Upgrade>\n\
         \x20       <WillShowUI>Never</WillShowUI>\n\
         \x20     </UpgradeData>\n\
         \x20     <UserData>\n\
         \x20       <AcceptEula>true</AcceptEula>\n\
         \x20       <FullName>{user}</FullName>\n\
         \x20       <Organization>Oxide</Organization>\n\
         {product_key}      </UserData>\n\
         \x20   </component>",
        disk = config.target_disk,
        user = xml_escape(&config.username),
        ui = will_show_ui(config),
        log_path = match &config.log_path {
            Some(path) =>
                format!("      <LogPath>{}</LogPath>\n", xml_escape(path)),
            None => String::new(),
        },
    ));

    Ok(format!(
        "  <settings pass=\"windowsPE\">\n{}\n  </settings>",
        components.join("\n")
    ))
}

/// Out-of-box drivers are staged here, not in `specialize`.
/// `Microsoft-Windows-PnpCustomizationsNonWinPE` is only valid in `offlineServicing`
/// and `auditSystem`; in `specialize` Setup silently ignores the whole component. That
/// is exactly what happened — every install shipped with this block in the wrong pass,
/// no error anywhere, and NetKVM was never installed, so the guest had no network.
///
/// `offlineServicing` applies the drivers to the image before first boot, so the NIC
/// works from the very first boot rather than after a PnP rescan.
fn offline_servicing_pass(config: &Config) -> String {
    if !config.inject_drivers {
        return String::new();
    }
    format!(
        "  <settings pass=\"offlineServicing\">\n\
         \x20   <component name=\"Microsoft-Windows-PnpCustomizationsNonWinPE\" {ARCH}>\n\
         \x20     <DriverPaths>\n{}\n\
         \x20     </DriverPaths>\n\
         \x20   </component>\n\
         \x20 </settings>",
        driver_paths()
    )
}

fn specialize_pass(config: &Config) -> Result<String> {
    let mut components: Vec<String> = Vec::new();

    components.push(format!(
        "    <component name=\"Microsoft-Windows-Shell-Setup\" {ARCH}>\n\
         \x20     <ComputerName>{}</ComputerName>\n\
         \x20     <TimeZone>{}</TimeZone>\n\
         \x20   </component>",
        xml_escape(&config.computer_name),
        xml_escape(&config.timezone)
    ));

    if config.enable_rdp {
        components.push(format!(
            "    <component name=\"Microsoft-Windows-TerminalServices-LocalSessionManager\" {ARCH}>\n\
             \x20     <fDenyTSConnections>false</fDenyTSConnections>\n\
             \x20   </component>"
        ));
        // 1 keeps Network Level Authentication on. 0 disables it, which is the usual
        // copy-paste default and a real downgrade — it lets a client reach the logon
        // screen before authenticating. Standard clients handle NLA against a local
        // account fine, so there is no reason to ship the weaker setting.
        components.push(format!(
            "    <component name=\"Microsoft-Windows-TerminalServices-RDP-WinStationExtensions\" {ARCH}>\n\
             \x20     <UserAuthentication>1</UserAuthentication>\n\
             \x20   </component>"
        ));
        components.push(format!(
            "    <component name=\"Networking-MPSSVC-Svc\" {ARCH}>\n\
             \x20     <FirewallGroups>\n\
             \x20       <FirewallGroup wcm:action=\"add\" wcm:keyValue=\"RemoteDesktop\">\n\
             \x20         <Active>true</Active>\n\
             \x20         <Group>@FirewallAPI.dll,-28752</Group>\n\
             \x20         <Profile>all</Profile>\n\
             \x20       </FirewallGroup>\n\
             \x20     </FirewallGroups>\n\
             \x20   </component>"
        ));
    }

    let mut commands: Vec<Command> = Vec::new();

    if config.verbose_serial {
        // First thing in specialize, so reaching it proves windowsPE finished, the image
        // was applied and the guest rebooted into it.
        commands.push(Command {
            path:
                "cmd.exe /c echo OXIDE-STAGE specialize-begin>COM1 & exit /b 0"
                    .into(),
            description: "Serial progress marker: specialize-begin".into(),
        });
    }

    if config.enable_serial_console {
        // An Oxide rack's only out-of-band access to a guest is the serial console, so
        // without this an install that goes wrong is invisible. It runs first and as
        // its own command: if the bootstrap below fails, serial is what you need to
        // find out why. Propolis exposes the guest serial port as com1, hence
        // EMSPORT:1; /bootems additionally sends boot loader output to serial.
        commands.push(Command {
            path: "cmd.exe /c bcdedit /ems {current} on && bcdedit /emssettings \
                   EMSPORT:1 EMSBAUDRATE:115200 && bcdedit /bootems {current} on"
                .into(),
            description: "Enable EMS serial console on com1".into(),
        });
    }

    // Runs as SYSTEM before any user logs on. The drive letter is not knowable here,
    // so enumerate filesystem drives and look for the script itself. Looking it up by
    // volume label was too brittle: when the builder's label and VOLUME_LABEL
    // disagreed the lookup threw, this command failed, and the whole bootstrap was
    // skipped *without failing the install* — so the guest came up looking fine with
    // no OpenSSH, no firewall rule and no SSH keys.
    //
    // The terse aliases (gdr/%/?) rather than readable cmdlet names are what keep this
    // under the 259-character <Path> limit.
    let find = "gdr -PSProvider FileSystem|%{$_.Root+'setup\\bootstrap.ps1'}\
                |?{Test-Path $_}|select -First 1|%{& $_}";
    let path = format!(
        "powershell.exe -NoProfile -ExecutionPolicy Bypass -Command \"{find}\""
    );
    if path.length_over_limit() {
        bail!(
            "bootstrap RunSynchronousCommand path is {} chars, limit is {PATH_LIMIT}",
            path.len()
        );
    }
    commands
        .push(Command { path, description: "Oxide guest bootstrap".into() });

    components.push(format!(
        "    <component name=\"Microsoft-Windows-Deployment\" {ARCH}>\n\
         \x20     <RunSynchronous>\n{}\n\
         \x20     </RunSynchronous>\n\
         \x20   </component>",
        run_synchronous_commands(&commands)
    ));

    Ok(format!(
        "  <settings pass=\"specialize\">\n{}\n  </settings>",
        components.join("\n")
    ))
}

fn oobe_pass(config: &Config) -> String {
    let auto_logon = if config.auto_logon {
        format!(
            "      <AutoLogon>\n\
             \x20       <Enabled>true</Enabled>\n\
             \x20       <Username>{user}</Username>\n\
             \x20       <LogonCount>1</LogonCount>\n\
             \x20       <Password>\n\
             \x20         <Value>{pass}</Value>\n\
             \x20         <PlainText>true</PlainText>\n\
             \x20       </Password>\n\
             \x20     </AutoLogon>\n",
            user = xml_escape(&config.username),
            pass = xml_escape(&config.password)
        )
    } else {
        String::new()
    };

    format!(
        "  <settings pass=\"oobeSystem\">\n\
         \x20   <component name=\"Microsoft-Windows-Shell-Setup\" {ARCH}>\n\
         \x20     <OOBE>\n\
         \x20       <HideEULAPage>true</HideEULAPage>\n\
         \x20       <HideLocalAccountScreen>true</HideLocalAccountScreen>\n\
         \x20       <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>\n\
         \x20       <HideOnlineAccountScreens>true</HideOnlineAccountScreens>\n\
         \x20       <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>\n\
         \x20       <NetworkLocation>Work</NetworkLocation>\n\
         \x20       <ProtectYourPC>3</ProtectYourPC>\n\
         \x20     </OOBE>\n\
         \x20     <UserAccounts>\n\
         \x20       <LocalAccounts>\n\
         \x20         <LocalAccount wcm:action=\"add\">\n\
         \x20           <Name>{user}</Name>\n\
         \x20           <DisplayName>{user}</DisplayName>\n\
         \x20           <Group>Administrators</Group>\n\
         \x20           <Password>\n\
         \x20             <Value>{pass}</Value>\n\
         \x20             <PlainText>true</PlainText>\n\
         \x20           </Password>\n\
         \x20         </LocalAccount>\n\
         \x20       </LocalAccounts>\n\
         \x20     </UserAccounts>\n\
         {auto_logon}    </component>\n\
         \x20 </settings>",
        user = xml_escape(&config.username),
        pass = xml_escape(&config.password)
    )
}

/// Small helper so the limit check reads as a question about the path.
trait PathLimit {
    fn length_over_limit(&self) -> bool;
}

impl PathLimit for String {
    fn length_over_limit(&self) -> bool {
        self.len() > PATH_LIMIT
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn base() -> Config {
        Config {
            release: WindowsRelease::Server2022,
            edition: "datacenter".into(),
            computer_name: "win-server-01".into(),
            username: "oxide".into(),
            password: "0xide!230xide!23".into(),
            enable_rdp: true,
            inject_drivers: true,
            enable_serial_console: true,
            target_disk: 1,
            locale: "en-US".into(),
            timezone: "UTC".into(),
            product_key: None,
            auto_logon: false,
            verbose_serial: false,
            log_path: None,
            show_ui_on_error: true,
            image_index: Some(4),
            skip_image_install: false,
            install_from: None,
            install_from_letter: None,
            install_from_label: None,
            ssh_keys: Vec::new(),
            enable_ssh: true,
        }
    }

    /// Every branch in the generator. The slug is the golden's filename and the label
    /// is prose for a failure message — kept separate on purpose, because deriving the
    /// filename from the label would let a reworded label silently orphan a golden.
    fn cases() -> Vec<(&'static str, &'static str, Config)> {
        vec![
            ("defaults", "defaults", base()),
            (
                "no-drivers",
                "no drivers (leaves an empty offlineServicing pass)",
                Config { inject_drivers: false, ..base() },
            ),
            ("no-rdp", "no rdp", Config { enable_rdp: false, ..base() }),
            (
                "no-serial-console",
                "no serial console",
                Config { enable_serial_console: false, ..base() },
            ),
            // `image_index: None` on purpose. The edition only reaches the answer file
            // through the /IMAGE/NAME fallback; with an index set, these cases were
            // byte-identical to "defaults" and tested nothing.
            (
                "core-edition",
                "core edition",
                Config {
                    edition: "datacenter-core".into(),
                    image_index: None,
                    ..base()
                },
            ),
            (
                "standard-edition",
                "standard edition",
                Config {
                    edition: "standard".into(),
                    image_index: None,
                    ..base()
                },
            ),
            (
                "windows-11",
                "windows 11 (LabConfig bypasses)",
                Config {
                    release: WindowsRelease::Windows11,
                    edition: "pro".into(),
                    ..base()
                },
            ),
            (
                "product-key",
                "product key",
                Config {
                    product_key: Some("WX4NM-KYWYW-QJJR4-XV3QB-6VM33".into()),
                    ..base()
                },
            ),
            (
                "no-image-index",
                "no image index (falls back to /IMAGE/NAME)",
                Config { image_index: None, ..base() },
            ),
            (
                "skip-image-install",
                "skip image install",
                Config { skip_image_install: true, ..base() },
            ),
            (
                "install-from-label",
                "install from a labelled volume",
                Config {
                    install_from_label: Some("WINSETUP".into()),
                    install_from_letter: Some('W'),
                    ..base()
                },
            ),
            (
                "install-from-path",
                "explicit install path",
                Config {
                    install_from: Some("E:\\sources\\install.wim".into()),
                    ..base()
                },
            ),
            ("autologon", "autologon", Config { auto_logon: true, ..base() }),
            (
                "golden-image-name",
                "golden image uses a random computer name",
                Config { computer_name: "*".into(), ..base() },
            ),
            (
                "xml-hostile-credentials",
                "xml-hostile credentials survive escaping",
                Config {
                    username: "a<b>&c".into(),
                    password: "p<a>&s\"s'w0rd!".into(),
                    ..base()
                },
            ),
        ]
    }

    /// Rewrite the goldens from the current generator.
    ///
    ///   cargo test -p oxwin-core dump_goldens -- --ignored
    ///
    /// The committed goldens came from the JavaScript builder, which is the only answer
    /// file that has ever installed Windows Image Builder hardware. Running this replaces
    /// that provenance with "whatever the Rust does today", so the diff it produces is
    /// the review — an unexplained hunk here is a bug being blessed, not a test being
    /// updated.
    #[test]
    #[ignore = "rewrites goldens; run deliberately and read the diff"]
    fn dump_goldens() {
        let dir =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata/unattend");
        std::fs::create_dir_all(&dir).expect("create testdata/unattend");
        for (slug, _, config) in cases() {
            let ours = build(&config).expect("build");
            std::fs::write(dir.join(format!("{slug}.xml")), &ours)
                .expect("write golden");
        }
    }

    /// Every branch in the generator, against a committed golden byte for byte. The
    /// goldens were produced by the JavaScript builder, which is the only answer file
    /// that has installed Windows Image Builder hardware, and every way this file can be
    /// wrong is silent.
    #[test]
    fn matches_the_goldens() {
        let dir =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata/unattend");
        let cases = cases();

        let mut failures = Vec::new();
        for (slug, label, config) in &cases {
            let path = dir.join(format!("{slug}.xml"));
            // Missing goldens fail. The predecessor of this test skipped when its
            // reference was unavailable, and a test that skips is a test that lies.
            let theirs = std::fs::read_to_string(&path).unwrap_or_else(|e| {
                panic!("{}: {e}. Regenerate with dump_goldens", path.display())
            });
            let ours = build(config).expect("build");
            if ours != theirs {
                failures.push(format!(
                    "{label}: {}",
                    first_difference(&ours, &theirs)
                ));
            }
        }
        assert!(
            failures.is_empty(),
            "{} of {} cases differ from their golden:\n{}",
            failures.len(),
            cases.len(),
            failures.join("\n")
        );
    }

    /// A golden nothing compares against is dead weight, and a case whose golden was
    /// never written would otherwise be caught only by the read above. Check the two
    /// sets agree exactly.
    #[test]
    fn every_golden_has_a_case_and_every_case_a_golden() {
        let dir =
            PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata/unattend");
        let mut on_disk: Vec<String> = std::fs::read_dir(&dir)
            .expect("testdata/unattend")
            .map(|e| {
                e.expect("entry")
                    .file_name()
                    .to_string_lossy()
                    .trim_end_matches(".xml")
                    .to_string()
            })
            .collect();
        on_disk.sort();
        let mut expected: Vec<String> =
            cases().iter().map(|(slug, ..)| slug.to_string()).collect();
        expected.sort();
        assert_eq!(on_disk, expected);
    }

    /// Point at the first differing line, which is far more useful than a diff of two
    /// 8 KB strings when a single space is wrong.
    fn first_difference(ours: &str, theirs: &str) -> String {
        for (i, (a, b)) in ours.lines().zip(theirs.lines()).enumerate() {
            if a != b {
                return format!(
                    "line {}\n     ours: {a:?}\n  js ref: {b:?}",
                    i + 1
                );
            }
        }
        format!(
            "line counts differ: ours {} vs js ref {}",
            ours.lines().count(),
            theirs.lines().count()
        )
    }

    #[test]
    fn every_path_stays_under_the_schema_limit() {
        // The 259-char cap is what rejected an entire answer file once, with an error
        // naming only the pass. Check the decoded length, which is what the schema
        // sees, across every branch that can add commands.
        for config in [
            base(),
            Config {
                release: WindowsRelease::Windows11,
                edition: "pro".into(),
                ..base()
            },
            Config { install_from_label: Some("WINSETUP".into()), ..base() },
        ] {
            let xml = build(&config).expect("build");
            for chunk in xml.split("<Path>").skip(1) {
                let raw = chunk.split("</Path>").next().expect("closing tag");
                let decoded = raw
                    .replace("&quot;", "\"")
                    .replace("&apos;", "'")
                    .replace("&lt;", "<")
                    .replace("&gt;", ">")
                    .replace("&amp;", "&");
                assert!(
                    decoded.len() <= PATH_LIMIT,
                    "{} chars: {decoded}",
                    decoded.len()
                );
            }
        }
    }

    #[test]
    fn driver_paths_land_in_offline_servicing_not_specialize() {
        // In specialize this component is ignored with no error and NetKVM never
        // installs, which is a guest with no network and nothing in any log.
        let xml = build(&base()).expect("build");
        let offline = xml
            .split("<settings pass=\"offlineServicing\">")
            .nth(1)
            .expect("offlineServicing pass");
        assert!(offline.contains("PnpCustomizationsNonWinPE"));
        let specialize = xml
            .split("<settings pass=\"specialize\">")
            .nth(1)
            .expect("specialize pass");
        assert!(!specialize.contains("PnpCustomizationsNonWinPE"));
    }

    #[test]
    fn no_product_key_element_when_there_is_no_key() {
        // An empty <Key> is not the same as no key: Setup fails the licence lookup
        // before showing any page.
        assert!(!build(&base()).expect("build").contains("<ProductKey>"));
    }
}
