// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Copyright 2026 Oxide Computer Company

//! Minimal WIM metadata reader.
//!
//! Only enough to answer "which editions are in this `install.wim`?". Edition names
//! differ between retail, evaluation, OEM and localised media, so a hardcoded
//! `/IMAGE/NAME` in the answer file fails on media it was not written for: Setup opens
//! the WIM, matches nothing, and shows an empty "Select the operating system" list with
//! no explanation at all.
//!
//! No decompression and no WIM support proper is needed. The header carries a resource
//! descriptor pointing at an XML blob, and that blob is stored uncompressed as UTF-16LE.
//! Two reads, decode, done — about 12 KB, so there is nothing worth caching.
//!
//! Header layout (see \[MS-WIM\]):
//!
//! ```text
//!   0   ImageTag "MSWIM\0\0\0"
//!   44  dwImageCount
//!   48  rhOffsetTable   (resource descriptor)
//!   72  rhXmlData       (resource descriptor)  <- what we want
//! ```
//!
//! Each resource descriptor is 24 bytes: a 7-byte size, one flags byte, an 8-byte file
//! offset, then an 8-byte uncompressed size.

use anyhow::{Result, bail};

pub const HEADER_BYTES: usize = 208;
const XML_RESOURCE_OFFSET: usize = 72;

/// One image in the WIM.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Image {
    pub index: u32,
    pub name: String,
    pub description: String,
    /// Stable across retail, evaluation and OEM media, where `name` is not.
    pub edition_id: String,
    pub flags: String,
}

/// Where the XML resource lives.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct XmlResource {
    pub offset: u64,
    pub size: u64,
}

pub fn parse_header(header: &[u8]) -> Result<(u32, XmlResource)> {
    if header.len() < HEADER_BYTES {
        bail!("WIM header truncated: {} bytes", header.len());
    }
    if !header.starts_with(b"MSWIM") {
        bail!(
            "not a WIM file (tag {:?})",
            String::from_utf8_lossy(&header[..8])
        );
    }
    let image_count =
        u32::from_le_bytes(header[44..48].try_into().expect("four bytes"));
    // The size field is seven bytes, so it cannot be read as a u64 directly.
    let at = XML_RESOURCE_OFFSET;
    let mut size: u64 = 0;
    for i in (0..7).rev() {
        size = size * 256 + header[at + i] as u64;
    }
    let offset =
        u64::from_le_bytes(header[at + 8..at + 16].try_into().expect("eight"));
    Ok((image_count, XmlResource { offset, size }))
}

/// Parse the image list out of the raw XML resource: UTF-16LE, usually with a BOM.
///
/// Scanned rather than parsed, deliberately. This XML is machine-generated by
/// Microsoft's own tooling and has a fixed, flat shape, so a real parser would be a
/// dependency and a second set of failure modes for no benefit.
pub fn parse_xml(bytes: &[u8]) -> Result<Vec<Image>> {
    let units: Vec<u16> = bytes
        .chunks_exact(2)
        .map(|p| u16::from_le_bytes([p[0], p[1]]))
        .collect();
    let mut text = String::from_utf16_lossy(&units);
    if text.starts_with('\u{feff}') {
        text = text[3..].to_string();
    }

    let mut images = Vec::new();
    let mut rest = text.as_str();
    while let Some(start) = rest.find("<IMAGE ") {
        let after = &rest[start + "<IMAGE ".len()..];
        let Some(tag_end) = after.find('>') else { break };
        let (attrs, body_and_rest) = after.split_at(tag_end);
        let body_start = &body_and_rest[1..];
        let Some(body_end) = body_start.find("</IMAGE>") else { break };
        let body = &body_start[..body_end];

        if let Some(index) =
            attribute(attrs, "INDEX").and_then(|v| v.parse().ok())
        {
            images.push(Image {
                index,
                name: element(body, "NAME"),
                description: element(body, "DESCRIPTION"),
                edition_id: element(body, "EDITIONID"),
                flags: element(body, "FLAGS"),
            });
        }
        rest = &body_start[body_end + "</IMAGE>".len()..];
    }
    Ok(images)
}

fn attribute(attrs: &str, name: &str) -> Option<String> {
    let needle = format!("{name}=\"");
    let at = attrs.find(&needle)? + needle.len();
    let end = attrs[at..].find('"')?;
    Some(attrs[at..at + end].to_string())
}

/// The first `<TAG>…</TAG>` in `body`, trimmed. Empty when absent: a missing element and
/// an empty one are treated alike, which is what the goldens pin.
fn element(body: &str, tag: &str) -> String {
    let open = format!("<{tag}>");
    let close = format!("</{tag}>");
    let Some(at) = body.find(&open) else {
        return String::new();
    };
    let from = at + open.len();
    let Some(end) = body[from..].find(&close) else {
        return String::new();
    };
    body[from..from + end].trim().to_string()
}

/// Read the image list through a caller-supplied reader, so this works over a file, a
/// UDF reader, or anything else without depending on any of them.
pub fn read_images(
    read: &mut impl FnMut(u64, usize) -> Result<Vec<u8>>,
) -> Result<Vec<Image>> {
    let header = read(0, HEADER_BYTES)?;
    let (_, xml) = parse_header(&header)?;
    if xml.size == 0 {
        return Ok(Vec::new());
    }
    parse_xml(&read(xml.offset, xml.size as usize)?)
}

/// Whether this image is a Server Core image rather than Desktop Experience.
///
/// Server media marks the Core images with a `CORE` suffix and gives the Desktop
/// Experience images no marker at all:
///
/// ```text
///   [3] Windows Server 2022 SERVERDATACENTERCORE   flags ServerDataCenterEvalCore
///   [4] Windows Server 2022 SERVERDATACENTER       flags ServerDataCenterEval
/// ```
///
/// `flags` is checked first because it stays stable across retail, evaluation and OEM
/// media where `name` does not.
pub fn is_core_image(image: &Image) -> bool {
    ends_with_core(&image.flags) || ends_with_core(&image.name)
}

fn ends_with_core(s: &str) -> bool {
    s.len() >= 4 && s[s.len() - 4..].eq_ignore_ascii_case("core")
}

/// Choose the image matching a loose hint — an index, an `EDITIONID`, or any substring
/// of the name or description. Returns `None` when nothing matches, so a caller can
/// show what is actually available instead of failing opaquely.
///
/// The Core filter comes first and is the whole reason this is not one substring
/// search: `datacenter` is a substring of `SERVERDATACENTERCORE`, so a plain search
/// finds Core and silently installs a server with no desktop. That shipped once.
pub fn select_image<'a>(images: &'a [Image], hint: &str) -> Option<&'a Image> {
    if images.is_empty() {
        return None;
    }
    let want = hint.trim().to_lowercase();
    if want.is_empty() {
        return images.first();
    }
    if !want.is_empty() && want.chars().all(|c| c.is_ascii_digit()) {
        let index: u32 = want.parse().ok()?;
        return images.iter().find(|i| i.index == index);
    }

    let wants_core = want.contains("core");
    let stripped = want.replace("core", "");
    let needle = stripped.trim();
    let needle = if needle.is_empty() { want.as_str() } else { needle };

    let search = |list: &[&'a Image], text: &str| -> Option<&'a Image> {
        list.iter()
            .find(|i| i.edition_id.to_lowercase() == text)
            .or_else(|| list.iter().find(|i| i.name.to_lowercase() == text))
            .or_else(|| {
                list.iter().find(|i| i.name.to_lowercase().contains(text))
            })
            .or_else(|| {
                list.iter()
                    .find(|i| i.description.to_lowercase().contains(text))
            })
            .copied()
    };

    let preferred: Vec<&Image> =
        images.iter().filter(|i| is_core_image(i) == wants_core).collect();
    let all: Vec<&Image> = images.iter().collect();
    search(&preferred, needle).or_else(|| search(&all, &want))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The real image list from Server 2022 evaluation media.
    fn server_2022() -> Vec<Image> {
        [
            (
                1,
                "SERVERSTANDARDCORE",
                "ServerStandardEval",
                "ServerStandardEvalCore",
            ),
            (2, "SERVERSTANDARD", "ServerStandardEval", "ServerStandardEval"),
            (
                3,
                "SERVERDATACENTERCORE",
                "ServerDatacenterEval",
                "ServerDataCenterEvalCore",
            ),
            (
                4,
                "SERVERDATACENTER",
                "ServerDatacenterEval",
                "ServerDataCenterEval",
            ),
        ]
        .iter()
        .map(|(index, name, edition, flags)| Image {
            index: *index,
            name: format!("Windows Server 2022 {name}"),
            description: String::new(),
            edition_id: edition.to_string(),
            flags: flags.to_string(),
        })
        .collect()
    }

    /// Retail media drops `Eval` everywhere, which is why matching leans on FLAGS and
    /// substrings rather than an exact EDITIONID or a fixed index.
    fn retail() -> Vec<Image> {
        server_2022()
            .into_iter()
            .map(|i| Image {
                edition_id: i.edition_id.replace("Eval", ""),
                flags: i.flags.replace("Eval", ""),
                ..i
            })
            .collect()
    }

    /// The bug that shipped: `datacenter` matched `SERVERDATACENTERCORE` and installed
    /// a server with no desktop.
    #[test]
    fn a_desktop_hint_never_selects_core() {
        for list in [server_2022(), retail()] {
            assert_eq!(select_image(&list, "datacenter").unwrap().index, 4);
            assert_eq!(select_image(&list, "standard").unwrap().index, 2);
            assert_eq!(select_image(&list, "datacentercore").unwrap().index, 3);
            assert_eq!(select_image(&list, "standardcore").unwrap().index, 1);
        }
    }

    #[test]
    fn a_numeric_hint_is_an_index() {
        let list = server_2022();
        assert_eq!(select_image(&list, "3").unwrap().index, 3);
        assert_eq!(select_image(&list, " 1 ").unwrap().index, 1);
        assert!(select_image(&list, "9").is_none());
    }

    /// An exact EDITIONID beats any substring, and still respects the Core filter:
    /// images 3 and 4 share `ServerDatacenterEval`, and the Desktop one wins.
    /// Pinned by a golden, because this shipped wrong once.
    #[test]
    fn an_edition_id_matches_exactly_before_any_substring() {
        let list = server_2022();
        assert_eq!(
            select_image(&list, "ServerDatacenterEval").unwrap().index,
            4
        );
        assert_eq!(select_image(&list, "ServerStandardEval").unwrap().index, 2);
    }

    #[test]
    fn an_empty_hint_takes_the_first_image() {
        assert_eq!(select_image(&server_2022(), "").unwrap().index, 1);
        assert!(select_image(&[], "datacenter").is_none());
    }

    #[test]
    fn a_hint_matching_nothing_returns_none() {
        assert!(select_image(&server_2022(), "enterprise").is_none());
    }

    #[test]
    fn core_detection_uses_flags_before_name() {
        // Localised media where NAME is translated but FLAGS is not.
        let image = Image {
            index: 1,
            name: "Windows Server 2022 Datacenter (Kern)".into(),
            description: String::new(),
            edition_id: "ServerDatacenter".into(),
            flags: "ServerDataCenterCore".into(),
        };
        assert!(is_core_image(&image));
        // And "core" anywhere other than the end does not count.
        let image = Image { flags: "CoreServer".into(), ..image };
        assert!(!is_core_image(&image));
    }

    #[test]
    fn a_header_that_is_not_a_wim_is_refused() {
        let mut header = vec![0u8; HEADER_BYTES];
        header[..8].copy_from_slice(b"NOTAWIM\0");
        let err = parse_header(&header).err().unwrap().to_string();
        assert!(err.contains("not a WIM file"), "{err}");
        assert!(parse_header(&[1, 2, 3]).is_err());
    }

    #[test]
    fn the_xml_resource_descriptor_is_read_as_seven_bytes_plus_flags() {
        let mut header = vec![0u8; HEADER_BYTES];
        header[..8].copy_from_slice(b"MSWIM\0\0\0");
        header[44..48].copy_from_slice(&7u32.to_le_bytes());
        // A size of 0x0000_0000_00_1234 with a flags byte that must not leak into it.
        header[72..79].copy_from_slice(&[0x34, 0x12, 0, 0, 0, 0, 0]);
        header[79] = 0xff; // flags
        header[80..88].copy_from_slice(&0x4000_0000u64.to_le_bytes());
        let (count, xml) = parse_header(&header).unwrap();
        assert_eq!(count, 7);
        assert_eq!(xml.size, 0x1234, "the flags byte leaked into the size");
        assert_eq!(xml.offset, 0x4000_0000);
    }

    fn utf16le(s: &str) -> Vec<u8> {
        let mut out = Vec::new();
        for unit in s.encode_utf16() {
            out.extend_from_slice(&unit.to_le_bytes());
        }
        out
    }

    #[test]
    fn the_image_list_is_scanned_out_of_the_xml() {
        let xml = "\u{feff}<WIM><TOTALBYTES>1</TOTALBYTES>\
            <IMAGE INDEX=\"1\"><NAME>Server Core</NAME>\
            <DESCRIPTION>no desktop</DESCRIPTION>\
            <WINDOWS><EDITIONID>ServerStandardEval</EDITIONID></WINDOWS>\
            <FLAGS>ServerStandardEvalCore</FLAGS></IMAGE>\
            <IMAGE INDEX=\"2\"><NAME>Server Desktop</NAME>\
            <FLAGS>ServerStandardEval</FLAGS></IMAGE></WIM>";
        let images = parse_xml(&utf16le(xml)).unwrap();
        assert_eq!(images.len(), 2);
        assert_eq!(images[0].index, 1);
        assert_eq!(images[0].name, "Server Core");
        assert_eq!(images[0].description, "no desktop");
        // EDITIONID is nested inside WINDOWS; the scan does not care about depth.
        assert_eq!(images[0].edition_id, "ServerStandardEval");
        // A missing element reads as empty rather than failing.
        assert_eq!(images[1].description, "");
        assert!(is_core_image(&images[0]));
        assert!(!is_core_image(&images[1]));
    }

    #[test]
    fn element_text_is_trimmed_and_multi_line_tolerant() {
        let xml = "<IMAGE INDEX=\"1\"><NAME>\n  Spaced Out  \n</NAME></IMAGE>";
        let images = parse_xml(&utf16le(xml)).unwrap();
        assert_eq!(images[0].name, "Spaced Out");
    }

    /// The real thing, when an ISO is to hand. `install.wim` is 4.04 GiB, so this also
    /// proves the 64-bit offset is handled — the XML resource sits near the end.
    #[test]
    fn reads_the_image_list_from_real_media() {
        let Ok(iso) = std::env::var("OXWIN_TEST_ISO") else {
            eprintln!("skipped: set OXWIN_TEST_ISO to a Windows ISO");
            return;
        };
        let mut udf =
            crate::udf::UdfImage::open(std::path::Path::new(&iso)).unwrap();
        let entry = udf
            .walk()
            .unwrap()
            .into_iter()
            .find(|e| e.path.eq_ignore_ascii_case("sources/install.wim"))
            .expect("sources/install.wim");
        let mut read = |offset: u64, len: usize| -> Result<Vec<u8>> {
            udf.read_range(&entry, offset, len)
        };
        let images = read_images(&mut read).unwrap();
        assert!(!images.is_empty(), "no editions found");
        // Every image on real media names an edition and a set of flags.
        for image in &images {
            assert!(!image.name.is_empty(), "{image:?}");
            assert!(!image.edition_id.is_empty(), "{image:?}");
        }
        // And the hint the builder defaults to resolves to a Desktop Experience image.
        let chosen = select_image(&images, "datacenter").unwrap();
        assert!(!is_core_image(chosen), "picked Core: {chosen:?}");
    }
}
