// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

// Copyright 2026 Oxide Computer Company

//! Minimal WIM metadata reader.
//!
//! Only enough to answer "which editions are in this `install.wim`?". Edition names
//! differ between retail, evaluation, OEM and localised media, so a hardcoded
//! `/IMAGE/NAME` in the answer file fails on media it was not written for: Setup opens
//! the WIM, matches nothing, and shows an empty "Select the operating system" list with
//! no explanation at all.
//!
//! No decompression and no WIM support proper is needed. The header carries a resource
//! descriptor pointing at an XML blob, and that blob is stored uncompressed as UTF-16LE.
//! Two reads, decode, done: about 12 KB, so there is nothing worth caching.
//!
//! Header layout (see \[MS-WIM\]):
//!
//! ```text
//!   0   ImageTag "MSWIM\0\0\0"
//!   44  dwImageCount
//!   48  rhOffsetTable   (resource descriptor)
//!   72  rhXmlData       (resource descriptor)  <- what we want
//! ```
//!
//! Each resource descriptor is 24 bytes: a 7-byte size, one flags byte, an 8-byte file
//! offset, then an 8-byte uncompressed size.

use anyhow::{Result, bail};

pub const HEADER_BYTES: usize = 208;
const XML_RESOURCE_OFFSET: usize = 72;

/// One image in the WIM.
///
/// The last four fields are what let the media identify itself rather than be asserted
/// by whoever picked the ISO. They are per-image on the wire, and on every ISO read so
/// far every image agrees, but nothing in the format promises that: so they stay per
/// image here and a caller that wants one answer for the media has to say what it does
/// when they disagree. Tested server 2016-2025, Win 10+11.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Image {
    pub index: u32,
    pub name: String,
    pub description: String,
    /// Stable across retail, evaluation and OEM media, where `name` is not.
    pub edition_id: String,
    pub flags: String,
    /// `PROCESSOR_ARCHITECTURE`: 9 is amd64, 12 is arm64. `None` when absent.
    pub arch: Option<u32>,
    /// The *base* build, not the patch level: media whose filename says 19045 reports
    /// 19041. Never match the number a filename implies.
    pub build: Option<u32>,
    /// `ServerNT` or `WinNT` — the only structural server/client signal. Empty when
    /// absent.
    pub product_type: String,
    /// `Server`, `Server Core` or `Client`. Empty when absent.
    pub installation_type: String,
}

/// `ARCH` for amd64, the only architecture anything in this workspace supports.
pub const ARCH_AMD64: u32 = 9;
/// `ARCH` for arm64. Present on real media, and refused: the drivers are amd64 and the
/// answer file hardcodes `processorArchitecture="amd64"`.
pub const ARCH_ARM64: u32 = 12;

/// Where the XML resource lives.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct XmlResource {
    pub offset: u64,
    pub size: u64,
}

pub fn parse_header(header: &[u8]) -> Result<(u32, XmlResource)> {
    if header.len() < HEADER_BYTES {
        bail!("WIM header truncated: {} bytes", header.len());
    }
    if !header.starts_with(b"MSWIM") {
        bail!(
            "not a WIM file (tag {:?})",
            String::from_utf8_lossy(&header[..8])
        );
    }
    let image_count =
        u32::from_le_bytes(header[44..48].try_into().expect("four bytes"));
    // The size field is seven bytes, so it cannot be read as a u64 directly.
    let at = XML_RESOURCE_OFFSET;
    let mut size: u64 = 0;
    for i in (0..7).rev() {
        size = size * 256 + header[at + i] as u64;
    }
    let offset =
        u64::from_le_bytes(header[at + 8..at + 16].try_into().expect("eight"));
    Ok((image_count, XmlResource { offset, size }))
}

/// Parse the image list out of the raw XML resource: UTF-16LE, usually with a BOM.
///
/// Scanned rather than parsed, deliberately. This XML is machine-generated by
/// Microsoft's own tooling and has a fixed, flat shape, so a real parser would be a
/// dependency and a second set of failure modes for no benefit.
pub fn parse_xml(bytes: &[u8]) -> Result<Vec<Image>> {
    let units: Vec<u16> = bytes
        .chunks_exact(2)
        .map(|p| u16::from_le_bytes([p[0], p[1]]))
        .collect();
    let mut text = String::from_utf16_lossy(&units);
    if text.starts_with('\u{feff}') {
        text = text[3..].to_string();
    }

    let mut images = Vec::new();
    let mut rest = text.as_str();
    while let Some(start) = rest.find("<IMAGE ") {
        let after = &rest[start + "<IMAGE ".len()..];
        let Some(tag_end) = after.find('>') else { break };
        let (attrs, body_and_rest) = after.split_at(tag_end);
        let body_start = &body_and_rest[1..];
        let Some(body_end) = body_start.find("</IMAGE>") else { break };
        let body = &body_start[..body_end];

        if let Some(index) =
            attribute(attrs, "INDEX").and_then(|v| v.parse().ok())
        {
            images.push(Image {
                index,
                name: element(body, "NAME"),
                description: element(body, "DESCRIPTION"),
                edition_id: element(body, "EDITIONID"),
                flags: element(body, "FLAGS"),
                arch: number(body, "ARCH"),
                // `<BUILD>` is nested in `<VERSION>`, alongside `<SPBUILD>`. The scan
                // matches the literal `<BUILD>`, which `<SPBUILD>` does not contain.
                build: number(body, "BUILD"),
                product_type: element(body, "PRODUCTTYPE"),
                installation_type: element(body, "INSTALLATIONTYPE"),
            });
        }
        rest = &body_start[body_end + "</IMAGE>".len()..];
    }
    Ok(images)
}

fn attribute(attrs: &str, name: &str) -> Option<String> {
    let needle = format!("{name}=\"");
    let at = attrs.find(&needle)? + needle.len();
    let end = attrs[at..].find('"')?;
    Some(attrs[at..at + end].to_string())
}

/// The first `<TAG>...</TAG>` in `body`, trimmed. Empty when absent: a missing element and
/// an empty one are treated alike, which is what the goldens pin.
fn element(body: &str, tag: &str) -> String {
    let open = format!("<{tag}>");
    let close = format!("</{tag}>");
    let Some(at) = body.find(&open) else {
        return String::new();
    };
    let from = at + open.len();
    let Some(end) = body[from..].find(&close) else {
        return String::new();
    };
    body[from..from + end].trim().to_string()
}

/// The first `<TAG>...</TAG>` as a number. `None` covers absent, empty and unparseable
/// alike: all three mean "the media did not tell us", and there is no numeric value that
/// could stand in for that — build 0 and architecture 0 are both nonsense.
fn number(body: &str, tag: &str) -> Option<u32> {
    element(body, tag).parse().ok()
}

/// Read the image list through a caller-supplied reader, so this works over a file, a
/// UDF reader, or anything else without depending on any of them.
pub fn read_images(
    read: &mut impl FnMut(u64, usize) -> Result<Vec<u8>>,
) -> Result<Vec<Image>> {
    let header = read(0, HEADER_BYTES)?;
    let (_, xml) = parse_header(&header)?;
    if xml.size == 0 {
        return Ok(Vec::new());
    }
    parse_xml(&read(xml.offset, xml.size as usize)?)
}

/// Whether this image is a Server Core image rather than Desktop Experience.
///
/// `INSTALLATIONTYPE` says so outright — `Server`, `Server Core` or `Client` — so that is
/// what this reads. It used to test whether `flags` ended in `core`, which is true of
/// server media:
///
/// ```text
///   [3] Windows Server 2022 SERVERDATACENTERCORE   flags ServerDataCenterEvalCore
///   [4] Windows Server 2022 SERVERDATACENTER       flags ServerDataCenterEval
/// ```
///
/// and meaningless on client media, where **Windows 11 Home is `EDITIONID=Core`,
/// `FLAGS=Core`** and classified as Server Core by that test, while `Home N` (`CoreN`) is
/// not. Nothing had noticed because no client release was offered yet.
///
/// The string test survives only as the fallback for media omitting the tag, and there it
/// checks `flags` before `name` because `flags` stays stable across retail, evaluation and
/// OEM media where `name` does not.
pub fn is_core_image(image: &Image) -> bool {
    match image.installation_type.as_str() {
        "" => ends_with_core(&image.flags) || ends_with_core(&image.name),
        tag => tag.eq_ignore_ascii_case("server core"),
    }
}

/// Whether this image is a client release (Windows 10/11) rather than a server one.
///
/// `PRODUCTTYPE` is the only structural signal. Do not sniff for "Server" in an edition
/// name: it is a marketing string, translated on localised media.
pub fn is_client_image(image: &Image) -> bool {
    image.product_type.eq_ignore_ascii_case("WinNT")
        || image.installation_type.eq_ignore_ascii_case("client")
}

fn ends_with_core(s: &str) -> bool {
    s.len() >= 4 && s[s.len() - 4..].eq_ignore_ascii_case("core")
}

/// Choose the image matching a loose hint: an index, an `EDITIONID`, or any substring
/// of the name or description. Returns `None` when nothing matches, so a caller can
/// show what is actually available instead of failing opaquely.
///
/// The Core filter comes first and is the whole reason this is not one substring
/// search: `datacenter` is a substring of `SERVERDATACENTERCORE`, so a plain search
/// finds Core and silently installs a server with no desktop. That shipped once.
pub fn select_image<'a>(images: &'a [Image], hint: &str) -> Option<&'a Image> {
    if images.is_empty() {
        return None;
    }
    let want = hint.trim().to_lowercase();
    if want.is_empty() {
        return images.first();
    }
    if !want.is_empty() && want.chars().all(|c| c.is_ascii_digit()) {
        let index: u32 = want.parse().ok()?;
        return images.iter().find(|i| i.index == index);
    }

    let wants_core = want.contains("core");
    let stripped = want.replace("core", "");
    let needle = stripped.trim();
    let needle = if needle.is_empty() { want.as_str() } else { needle };

    let search = |list: &[&'a Image], text: &str| -> Option<&'a Image> {
        list.iter()
            .find(|i| i.edition_id.to_lowercase() == text)
            .or_else(|| list.iter().find(|i| i.name.to_lowercase() == text))
            .or_else(|| {
                list.iter().find(|i| i.name.to_lowercase().contains(text))
            })
            .or_else(|| {
                list.iter()
                    .find(|i| i.description.to_lowercase().contains(text))
            })
            .copied()
    };

    let preferred: Vec<&Image> =
        images.iter().filter(|i| is_core_image(i) == wants_core).collect();
    let all: Vec<&Image> = images.iter().collect();
    search(&preferred, needle).or_else(|| search(&all, &want))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The real image list from Server 2022 evaluation media, `INSTALLATIONTYPE` and all.
    ///
    /// Note the casing split between `EDITIONID` and `FLAGS`: `ServerDatacenterEval`
    /// against `ServerDataCenterEvalCore`. That is verbatim from the media, identically on
    /// 2019, 2022 and 2025, and it is why every comparison here lowercases first.
    fn server_2022() -> Vec<Image> {
        [
            (
                1,
                "SERVERSTANDARDCORE",
                "ServerStandardEval",
                "ServerStandardEvalCore",
                "Server Core",
            ),
            (
                2,
                "SERVERSTANDARD",
                "ServerStandardEval",
                "ServerStandardEval",
                "Server",
            ),
            (
                3,
                "SERVERDATACENTERCORE",
                "ServerDatacenterEval",
                "ServerDataCenterEvalCore",
                "Server Core",
            ),
            (
                4,
                "SERVERDATACENTER",
                "ServerDatacenterEval",
                "ServerDataCenterEval",
                "Server",
            ),
        ]
        .iter()
        .map(|(index, name, edition, flags, install)| Image {
            index: *index,
            name: format!("Windows Server 2022 {name}"),
            description: String::new(),
            edition_id: edition.to_string(),
            flags: flags.to_string(),
            arch: Some(ARCH_AMD64),
            build: Some(20348),
            product_type: "ServerNT".into(),
            installation_type: install.to_string(),
        })
        .collect()
    }

    /// Windows 11 22H2 retail, the four images that matter here. Home really is
    /// `EDITIONID=Core`/`FLAGS=Core` on the wire.
    fn windows_11() -> Vec<Image> {
        [
            (1, "Windows 11 Home", "Core", "Core"),
            (2, "Windows 11 Home N", "CoreN", "CoreN"),
            (5, "Windows 11 Pro", "Professional", "Professional"),
            (9, "Windows 11 Education", "Education", "Education"),
        ]
        .iter()
        .map(|(index, name, edition, flags)| Image {
            index: *index,
            name: name.to_string(),
            description: name.to_string(),
            edition_id: edition.to_string(),
            flags: flags.to_string(),
            arch: Some(ARCH_AMD64),
            build: Some(22621),
            product_type: "WinNT".into(),
            installation_type: "Client".into(),
        })
        .collect()
    }

    /// Retail media drops `Eval` everywhere, which is why matching leans on FLAGS and
    /// substrings rather than an exact EDITIONID or a fixed index.
    fn retail() -> Vec<Image> {
        server_2022()
            .into_iter()
            .map(|i| Image {
                edition_id: i.edition_id.replace("Eval", ""),
                flags: i.flags.replace("Eval", ""),
                ..i
            })
            .collect()
    }

    /// The bug that shipped: `datacenter` matched `SERVERDATACENTERCORE` and installed
    /// a server with no desktop.
    #[test]
    fn a_desktop_hint_never_selects_core() {
        for list in [server_2022(), retail()] {
            assert_eq!(select_image(&list, "datacenter").unwrap().index, 4);
            assert_eq!(select_image(&list, "standard").unwrap().index, 2);
            assert_eq!(select_image(&list, "datacentercore").unwrap().index, 3);
            assert_eq!(select_image(&list, "standardcore").unwrap().index, 1);
        }
    }

    #[test]
    fn a_numeric_hint_is_an_index() {
        let list = server_2022();
        assert_eq!(select_image(&list, "3").unwrap().index, 3);
        assert_eq!(select_image(&list, " 1 ").unwrap().index, 1);
        assert!(select_image(&list, "9").is_none());
    }

    /// An exact EDITIONID beats any substring, and still respects the Core filter:
    /// images 3 and 4 share `ServerDatacenterEval`, and the Desktop one wins.
    /// Pinned by a golden, because this shipped wrong once.
    #[test]
    fn an_edition_id_matches_exactly_before_any_substring() {
        let list = server_2022();
        assert_eq!(
            select_image(&list, "ServerDatacenterEval").unwrap().index,
            4
        );
        assert_eq!(select_image(&list, "ServerStandardEval").unwrap().index, 2);
    }

    #[test]
    fn an_empty_hint_takes_the_first_image() {
        assert_eq!(select_image(&server_2022(), "").unwrap().index, 1);
        assert!(select_image(&[], "datacenter").is_none());
    }

    #[test]
    fn a_hint_matching_nothing_returns_none() {
        assert!(select_image(&server_2022(), "enterprise").is_none());
    }

    /// `INSTALLATIONTYPE` decides Core-ness, so an image whose strings all say "core" is
    /// still Desktop Experience when the media says `Server`. Server media does not
    /// actually contradict itself this way; the point is which field wins.
    #[test]
    fn core_detection_reads_installationtype_not_the_strings() {
        let list = server_2022();
        assert!(is_core_image(&list[0]) && is_core_image(&list[2]));
        assert!(!is_core_image(&list[1]) && !is_core_image(&list[3]));

        let lying =
            Image { installation_type: "Server".into(), ..list[2].clone() };
        assert!(!is_core_image(&lying), "the strings beat INSTALLATIONTYPE");
    }

    /// The bug this fixes. Windows 11 Home is `EDITIONID=Core`, `FLAGS=Core`, so the old
    /// `flags`-ends-in-`core` test called it Server Core — while `Home N` (`CoreN`) came
    /// out Desktop. Nothing on client media is a Core image.
    #[test]
    fn windows_11_home_is_not_a_server_core_image() {
        for image in windows_11() {
            assert!(
                !is_core_image(&image),
                "{} classified as Server Core",
                image.name
            );
            assert!(is_client_image(&image), "{} is not client", image.name);
        }
        // The old heuristic, kept here so the regression is visible rather than implied.
        let home = &windows_11()[0];
        assert!(ends_with_core(&home.flags), "FLAGS really is `Core`");

        for image in server_2022() {
            assert!(!is_client_image(&image), "{} is not client", image.name);
        }
    }

    /// Media omitting `INSTALLATIONTYPE` falls back to the string test, which is the only
    /// thing such media offers. Localised media translates `NAME` but not `FLAGS`, so
    /// `flags` is checked first.
    #[test]
    fn core_detection_falls_back_to_flags_when_the_tag_is_absent() {
        let image = Image {
            index: 1,
            name: "Windows Server 2022 Datacenter (Kern)".into(),
            description: String::new(),
            edition_id: "ServerDatacenter".into(),
            flags: "ServerDataCenterCore".into(),
            arch: Some(ARCH_AMD64),
            build: Some(20348),
            product_type: "ServerNT".into(),
            installation_type: String::new(),
        };
        assert!(is_core_image(&image));
        // And "core" anywhere other than the end does not count.
        let image = Image { flags: "CoreServer".into(), ..image };
        assert!(!is_core_image(&image));
        // Without the tag, a server image is still not mistaken for a client one.
        assert!(!is_client_image(&image));
    }

    /// A client hint on client media must not be filtered out by the Core preference.
    /// `select_image` partitions on `is_core_image`, and Home used to land in the wrong
    /// half of that partition.
    #[test]
    fn a_client_edition_is_selectable_by_name_and_by_edition_id() {
        let list = windows_11();
        assert_eq!(select_image(&list, "Core").unwrap().index, 1);
        assert_eq!(select_image(&list, "pro").unwrap().index, 5);
        assert_eq!(select_image(&list, "Windows 11 Home").unwrap().index, 1);
        assert_eq!(select_image(&list, "CoreN").unwrap().index, 2);
    }

    #[test]
    fn a_header_that_is_not_a_wim_is_refused() {
        let mut header = vec![0u8; HEADER_BYTES];
        header[..8].copy_from_slice(b"NOTAWIM\0");
        let err = parse_header(&header).err().unwrap().to_string();
        assert!(err.contains("not a WIM file"), "{err}");
        assert!(parse_header(&[1, 2, 3]).is_err());
    }

    #[test]
    fn the_xml_resource_descriptor_is_read_as_seven_bytes_plus_flags() {
        let mut header = vec![0u8; HEADER_BYTES];
        header[..8].copy_from_slice(b"MSWIM\0\0\0");
        header[44..48].copy_from_slice(&7u32.to_le_bytes());
        // A size of 0x0000_0000_00_1234 with a flags byte that must not leak into it.
        header[72..79].copy_from_slice(&[0x34, 0x12, 0, 0, 0, 0, 0]);
        header[79] = 0xff; // flags
        header[80..88].copy_from_slice(&0x4000_0000u64.to_le_bytes());
        let (count, xml) = parse_header(&header).unwrap();
        assert_eq!(count, 7);
        assert_eq!(xml.size, 0x1234, "the flags byte leaked into the size");
        assert_eq!(xml.offset, 0x4000_0000);
    }

    fn utf16le(s: &str) -> Vec<u8> {
        let mut out = Vec::new();
        for unit in s.encode_utf16() {
            out.extend_from_slice(&unit.to_le_bytes());
        }
        out
    }

    #[test]
    fn the_image_list_is_scanned_out_of_the_xml() {
        let xml = "\u{feff}<WIM><TOTALBYTES>1</TOTALBYTES>\
            <IMAGE INDEX=\"1\"><NAME>Server Core</NAME>\
            <DESCRIPTION>no desktop</DESCRIPTION>\
            <WINDOWS><ARCH>9</ARCH><PRODUCTNAME>Windows Server</PRODUCTNAME>\
            <EDITIONID>ServerStandardEval</EDITIONID>\
            <INSTALLATIONTYPE>Server Core</INSTALLATIONTYPE>\
            <PRODUCTTYPE>ServerNT</PRODUCTTYPE>\
            <VERSION><MAJOR>10</MAJOR><MINOR>0</MINOR>\
            <BUILD>20348</BUILD><SPBUILD>169</SPBUILD></VERSION></WINDOWS>\
            <FLAGS>ServerStandardEvalCore</FLAGS></IMAGE>\
            <IMAGE INDEX=\"2\"><NAME>Server Desktop</NAME>\
            <FLAGS>ServerStandardEval</FLAGS></IMAGE></WIM>";
        let images = parse_xml(&utf16le(xml)).unwrap();
        assert_eq!(images.len(), 2);
        assert_eq!(images[0].index, 1);
        assert_eq!(images[0].name, "Server Core");
        assert_eq!(images[0].description, "no desktop");
        // EDITIONID is nested inside WINDOWS; the scan does not care about depth.
        assert_eq!(images[0].edition_id, "ServerStandardEval");
        assert_eq!(images[0].arch, Some(ARCH_AMD64));
        assert_eq!(images[0].product_type, "ServerNT");
        assert_eq!(images[0].installation_type, "Server Core");
        // `<BUILD>` sits next to `<SPBUILD>` inside `<VERSION>`: 20348, not 169. And
        // `<NAME>` must not be answered by the `<PRODUCTNAME>` two elements earlier.
        assert_eq!(images[0].build, Some(20348));
        // A missing element reads as empty, or as None where it is numeric, rather than
        // failing: the second image here carries none of the identity tags.
        assert_eq!(images[1].description, "");
        assert_eq!(images[1].arch, None);
        assert_eq!(images[1].build, None);
        assert_eq!(images[1].product_type, "");
        assert_eq!(images[1].installation_type, "");
        assert!(is_core_image(&images[0]));
        assert!(!is_core_image(&images[1]));
    }

    /// Nothing usable comes back as `None`, not as a zero that reads like a real answer.
    #[test]
    fn an_unparseable_number_is_absent_rather_than_zero() {
        let xml =
            "<IMAGE INDEX=\"1\"><ARCH></ARCH><BUILD>26100.1742</BUILD></IMAGE>";
        let images = parse_xml(&utf16le(xml)).unwrap();
        assert_eq!(images[0].arch, None);
        assert_eq!(images[0].build, None);
    }

    #[test]
    fn element_text_is_trimmed_and_multi_line_tolerant() {
        let xml = "<IMAGE INDEX=\"1\"><NAME>\n  Spaced Out  \n</NAME></IMAGE>";
        let images = parse_xml(&utf16le(xml)).unwrap();
        assert_eq!(images[0].name, "Spaced Out");
    }

    /// The real thing, when an ISO is to hand. `install.wim` is 4.04 GiB, so this also
    /// proves the 64-bit offset is handled — the XML resource sits near the end.
    #[test]
    fn reads_the_image_list_from_real_media() {
        let Ok(iso) = std::env::var("OXWIN_TEST_ISO") else {
            eprintln!("skipped: set OXWIN_TEST_ISO to a Windows ISO");
            return;
        };
        let mut udf =
            crate::udf::UdfImage::open(std::path::Path::new(&iso)).unwrap();
        let entry = udf
            .walk()
            .unwrap()
            .into_iter()
            .find(|e| e.path.eq_ignore_ascii_case("sources/install.wim"))
            .expect("sources/install.wim");
        let mut read = |offset: u64, len: usize| -> Result<Vec<u8>> {
            udf.read_range(&entry, offset, len)
        };
        let images = read_images(&mut read).unwrap();
        assert!(!images.is_empty(), "no editions found");
        // Every image on real media names an edition and a set of flags, and carries all
        // four identity fields. Real media has never omitted one; the fallbacks exist for
        // media nobody has handed us yet, so if this fires on an ISO the fallbacks are
        // suddenly load-bearing and want checking rather than trusting.
        for image in &images {
            assert!(!image.name.is_empty(), "{image:?}");
            assert!(!image.edition_id.is_empty(), "{image:?}");
            assert!(
                matches!(image.arch, Some(ARCH_AMD64 | ARCH_ARM64)),
                "unknown ARCH: {image:?}"
            );
            assert!(image.build.unwrap_or(0) > 7600, "{image:?}");
            assert!(
                matches!(image.product_type.as_str(), "ServerNT" | "WinNT"),
                "unknown PRODUCTTYPE: {image:?}"
            );
            assert!(
                matches!(
                    image.installation_type.as_str(),
                    "Server" | "Server Core" | "Client"
                ),
                "unknown INSTALLATIONTYPE: {image:?}"
            );
            // Core-ness and client-ness are mutually exclusive on every real release.
            assert!(
                !(is_core_image(image) && is_client_image(image)),
                "{image:?}"
            );
        }

        // Whatever the media, the fields agree with each other about what it is.
        let first = &images[0];
        for image in &images {
            assert_eq!(image.arch, first.arch, "images disagree on ARCH");
            assert_eq!(image.build, first.build, "images disagree on BUILD");
            assert_eq!(
                image.product_type, first.product_type,
                "images disagree on PRODUCTTYPE"
            );
        }

        if is_client_image(first) {
            // Client media carries no Core images at all — the check that would have
            // caught the Windows 11 Home misclassification against the real ISO.
            assert!(
                !images.iter().any(is_core_image),
                "client media reported a Server Core image"
            );
            return;
        }
        // On server media, the hint the builder defaults to resolves to Desktop
        // Experience, and the media really does carry both spellings.
        let chosen = select_image(&images, "datacenter").unwrap();
        assert!(!is_core_image(chosen), "picked Core: {chosen:?}");
        assert!(images.iter().any(is_core_image), "no Core image found");
    }
}
