# Generated by the Oxide Windows image builder. Runs as SYSTEM in the
# specialize pass, before any user logs on.
$ErrorActionPreference = 'Stop'
$src = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = (Split-Path -Parent $src).TrimEnd('\')

# Log to the installer media as well as the system drive. The media is the only
# copy anyone can read without getting into the guest: on the rack the console is
# serial-only, and off the rack the system drive is NTFS, which needs support the
# reading machine may not have - macOS mounts it read-only at best. Detach the
# installer disk afterwards and the log is on exFAT, which every OS mounts.
$log = "$env:SystemDrive\oxide-bootstrap.log"
$mediaLog = "$root\oxide-bootstrap.log"
function Log($m) {
  $line = "$(Get-Date -Format o)  $m"
  $line | Tee-Object -FilePath $log -Append
  # Best effort: the media may be read-only or already gone.
  try { Add-Content -LiteralPath $mediaLog -Value $line -ErrorAction Stop } catch {}
}

Log "Oxide guest bootstrap starting"

# Belt and suspenders: the DriverPaths in the unattend should already have
# handled these, but a driver missed there leaves the guest unreachable.
if (Test-Path "$root\drivers") {
  Log "Installing drivers from $root\drivers"
  $out = & pnputil.exe /add-driver "$root\drivers\*.inf" /subdirs /install 2>&1
  Log "pnputil exit $LASTEXITCODE"
  # Keep the output when it fails. A bare exit code told us nothing, and
  # "no NIC" is expensive to diagnose after the fact.
  if ($LASTEXITCODE -ne 0) { $out | ForEach-Object { Log "  pnputil: $_" } }
  $nic = Get-PnpDevice -Class Net -ErrorAction SilentlyContinue | Where-Object { $_.FriendlyName -match 'VirtIO|Red Hat' }
  Log "virtio NIC present: $([bool]$nic)"
}

# Cloud-init (cloudbase-init). Verified on the machine itself before install:
# the pinned SHA-256 in fetch-payload.sh proves we got the bytes we asked for
# and says nothing about who signed them. Same fail-closed check as OpenSSH.
# Wrapped, because $ErrorActionPreference is 'Stop' for this script: a throw in
# here would otherwise abort the bootstrap, and with it everything after it.
try {
  $msi = "$root\cloudbase\CloudbaseInitSetup_x64.msi"
  if (-not (Test-Path $msi)) {
    Log "WARNING: cloud-init was requested but no MSI is on this media"
  } else {
    $sig = Get-AuthenticodeSignature -FilePath $msi
    if ($sig.Status -ne 'Valid' -or $sig.SignerCertificate.Subject -notmatch 'O=Cloudbase Solutions') {
      Log "REFUSING to install cloud-init: [$($sig.Status)] $($sig.SignerCertificate.Subject)"
    } else {
      Log "cloud-init payload verified: signed by Cloudbase Solutions"
      $msiProc = Start-Process -FilePath 'msiexec.exe' -ArgumentList '/i',"`"$msi`"",'/qn','/norestart','RUN_SERVICE_AS_LOCAL_SYSTEM=1' -Wait -PassThru
      Log "msiexec exit $($msiProc.ExitCode)"
      $cbDir = "$env:ProgramFiles\Cloudbase Solutions\Cloudbase-Init"
      if (-not (Test-Path $cbDir)) { $cbDir = "${env:ProgramFiles(x86)}\Cloudbase Solutions\Cloudbase-Init" }
      if (-not (Test-Path "$cbDir\conf")) {
        Log "WARNING: cloud-init did not install: there is no $cbDir\conf"
      } else {
        foreach ($conf in "$root\cloudbase\cloudbase-init.conf", "$root\cloudbase\cloudbase-init-unattend.conf") {
          if (Test-Path $conf) {
            Copy-Item -LiteralPath $conf -Destination (Join-Path "$cbDir\conf" (Split-Path -Leaf $conf)) -Force
            Log "cloud-init: installed $(Split-Path -Leaf $conf)"
          } else { Log "WARNING: cloud-init: $conf is missing from the media" }
        }
        # The installer drops an answer file of its own in conf\. It would run
        # instead of ours.
        $stock = "$cbDir\conf\Unattend.xml"
        if (Test-Path $stock) {
          Remove-Item -LiteralPath $stock -Force
          Log "cloud-init: removed the installer's own conf\Unattend.xml"
        }
      }
    }
  }
  # Disabled for the install, so it cannot contend with Setup's own passes.
  # OxideCloudInit puts it back once Setup has finished.
  $cbSvc = Get-Service -Name cloudbase-init -ErrorAction SilentlyContinue
  if ($cbSvc) {
    if ($cbSvc.Status -eq 'Running') { Stop-Service -Name cloudbase-init -Force -ErrorAction SilentlyContinue }
    Set-Service -Name cloudbase-init -StartupType Disabled
    Log "cloud-init: service disabled for the install"
  } else {
    Log "WARNING: no cloudbase-init service; cloud-init will not run"
  }
  New-Item -ItemType Directory -Force -Path 'C:\oxide\log' | Out-Null
} catch { Log "WARNING: cloud-init install failed: $_" }

# OxideCloudInit: at every startup, once Setup has finished, bring the
# cloudbase-init service up -- in keep-my-account mode making the account's
# profile first. Registered in both account modes: a clone's specialize pass
# can set the service to Automatic, but the SCM has already started automatic
# services by then, so without this task the service would first run on the
# clone's second boot.
try {
  $ciDir = "$env:SystemRoot\Setup\Scripts"
  $ciTask = "$ciDir\oxide-cloud-init.ps1"
  New-Item -ItemType Directory -Force -Path $ciDir | Out-Null
  Set-Content -LiteralPath $ciTask -Encoding ASCII -Value @'
$ErrorActionPreference = 'Continue'
$log = "$env:SystemDrive\oxide-bootstrap.log"
function TLog($m) {
  "$(Get-Date -Format o)  cloud-init task: $m" | Tee-Object -FilePath $log -Append
}
# This task never unregisters itself and re-arms nothing: every step below is
# idempotent, so it simply runs at every startup. Generalizing gives each clone
# a new SID, so the profile it makes has to be made again on every clone -- an
# "unregister when done" edit would work on the golden image and silently break
# every machine cloned from it.
# The task fires at every startup, including boots where Setup is still
# working. Do nothing until it has finished and let the next boot try again.
$setup = Get-ItemProperty -Path 'HKLM:\SYSTEM\Setup' -ErrorAction SilentlyContinue
if ($setup.SystemSetupInProgress -ne 0 -or $setup.OOBEInProgress -ne 0) {
  TLog "Setup still in progress; waiting for the next boot"
  exit 0
}
# Keep-my-account mode. SetUserSSHPublicKeysPlugin writes to the account's
# profile, which it finds through ProfileList\<SID>\ProfileImagePath, and an
# account an answer file created has no profile until someone logs on. Without
# one the plugin raises "User profile not found!" and the instance's keys are
# silently absent. So make it, before the service runs.
$user = 'oxide'
$sid = $null
try {
  $sid = (New-Object System.Security.Principal.NTAccount($user)).Translate([System.Security.Principal.SecurityIdentifier]).Value
} catch { TLog "WARNING: no account named $user to make a profile for: $_" }
if ($sid) {
  $profileKey = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\$sid"
  $profilePath = (Get-ItemProperty -Path $profileKey -ErrorAction SilentlyContinue).ProfileImagePath
  if ($profilePath) {
    TLog "profile for $user already exists at $profilePath"
  } else {
    TLog "no profile for $user; making one so cloud-init can write its SSH keys"
    # userenv's CreateProfile makes the ProfileList entry and the profile
    # directory, needs no password, and works from LocalSystem. Logging on as
    # the user to load its profile does not: that is CreateProcessWithLogonW,
    # documented not to work from LocalSystem.
    try {
      Add-Type -Namespace Oxide -Name UserEnv -MemberDefinition '[DllImport("userenv.dll", CharSet = CharSet.Unicode)] public static extern int CreateProfile(string sid, string name, System.Text.StringBuilder path, uint len);' -ErrorAction Stop
      $buf = New-Object System.Text.StringBuilder 260
      $hr = [Oxide.UserEnv]::CreateProfile($sid, $user, $buf, 260)
      TLog ('CreateProfile returned 0x{0:X8}' -f $hr)
    } catch { TLog "CreateProfile failed: $_" }
    $profilePath = (Get-ItemProperty -Path $profileKey -ErrorAction SilentlyContinue).ProfileImagePath
    if ($profilePath) {
      TLog "profile for $user made at $profilePath"
    } else {
      TLog "WARNING: still no profile for $user; the instance's SSH keys will not be written"
    }
  }
}
if (-not (Get-Service -Name cloudbase-init -ErrorAction SilentlyContinue)) {
  TLog "WARNING: no cloudbase-init service; nothing to start"
  exit 0
}
try {
  Set-Service -Name cloudbase-init -StartupType Automatic -ErrorAction Stop
  TLog "cloudbase-init set to start automatically"
} catch { TLog "WARNING: could not set cloudbase-init to Automatic: $_" }
if ((Get-Service -Name cloudbase-init).Status -eq 'Running') {
  TLog "cloudbase-init already running"
} else {
  try {
    Start-Service -Name cloudbase-init -ErrorAction Stop
    TLog "cloudbase-init started"
  } catch { TLog "WARNING: could not start cloudbase-init: $_" }
}
exit 0
'@
  # Wrapped for the same reason OxideGeneralize is: a failed registration must
  # not abort the bootstrap without saying why.
  $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$ciTask`""
  $trigger = New-ScheduledTaskTrigger -AtStartup
  $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
  Register-ScheduledTask -TaskName 'OxideCloudInit' -Action $action -Trigger $trigger -Principal $principal -Force | Out-Null
  Log "cloud-init: OxideCloudInit registered; it starts cloud-init once Setup has finished"
} catch { Log "WARNING: could not register OxideCloudInit, so cloud-init will not start on its own: $_" }

# Oxide boots the configured boot_disk and does not fall through to another
# disk, so the ESP needs the removable-media fallback path populated or the
# installed system drops to the EFI shell.
try {
  $esp = (Get-Partition | Where-Object { $_.GptType -eq '{c12a7328-f81f-11d2-ba4b-00a0c93ec93b}' } | Select-Object -First 1)
  if ($esp) {
    $letter = 'S'
    $mounted = $false
    if (-not $esp.DriveLetter) {
      $esp | Set-Partition -NewDriveLetter $letter
      $mounted = $true
    } else { $letter = $esp.DriveLetter }
    try {
      $src2 = "${letter}:\EFI\Microsoft\Boot\bootmgfw.efi"
      $dstDir = "${letter}:\EFI\BOOT"
      if (-not (Test-Path $src2)) {
        Log "WARNING: ESP fallback: no bootmgfw.efi at $src2"
      } elseif (Test-Path "$dstDir\BOOTX64.EFI") {
        Log "ESP fallback bootloader: Windows already wrote \EFI\BOOT\BOOTX64.EFI"
      } else {
        New-Item -ItemType Directory -Force -Path $dstDir | Out-Null
        Copy-Item -Path $src2 -Destination "$dstDir\BOOTX64.EFI" -Force
        Log "ESP fallback bootloader installed at \EFI\BOOT\BOOTX64.EFI"
      }
    } finally {
      # An ESP has no drive letter on a normal install. Leaving the one assigned
      # above ships every clone with the ESP visible in Explorer and writable by
      # anything running as admin, so it comes back off even if the copy threw.
      if ($mounted) {
        try {
          Remove-PartitionAccessPath -DiskNumber $esp.DiskNumber -PartitionNumber $esp.PartitionNumber -AccessPath "${letter}:" -ErrorAction Stop
          Log "ESP unmounted from ${letter}:"
        } catch { Log "WARNING: could not unmount ESP from ${letter}: $_" }
      }
    }
  } else { Log "WARNING: no EFI system partition found" }
} catch { Log "WARNING: ESP fallback copy failed: $_" }

Log "Oxide guest bootstrap complete"
