# Generated by the Oxide Windows image builder. Runs as SYSTEM in the
# specialize pass, before any user logs on.
$ErrorActionPreference = 'Stop'
$src = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = (Split-Path -Parent $src).TrimEnd('\')

# Log to the installer media as well as the system drive. The media is the only
# copy anyone can read without getting into the guest: on the rack the console is
# serial-only, and off the rack the system drive is NTFS, which needs support the
# reading machine may not have - macOS mounts it read-only at best. Detach the
# installer disk afterwards and the log is on exFAT, which every OS mounts.
$log = "$env:SystemDrive\oxide-bootstrap.log"
$mediaLog = "$root\oxide-bootstrap.log"
function Log($m) {
  $line = "$(Get-Date -Format o)  $m"
  $line | Tee-Object -FilePath $log -Append
  # Best effort: the media may be read-only or already gone.
  try { Add-Content -LiteralPath $mediaLog -Value $line -ErrorAction Stop } catch {}
}

Log "Oxide guest bootstrap starting"

# Belt and suspenders: the DriverPaths in the unattend should already have
# handled these, but a driver missed there leaves the guest unreachable.
if (Test-Path "$root\drivers") {
  Log "Installing drivers from $root\drivers"
  $out = & pnputil.exe /add-driver "$root\drivers\*.inf" /subdirs /install 2>&1
  Log "pnputil exit $LASTEXITCODE"
  # Keep the output when it fails. A bare exit code told us nothing, and
  # "no NIC" is expensive to diagnose after the fact.
  if ($LASTEXITCODE -ne 0) { $out | ForEach-Object { Log "  pnputil: $_" } }
  $nic = Get-PnpDevice -Class Net -ErrorAction SilentlyContinue | Where-Object { $_.FriendlyName -match 'VirtIO|Red Hat' }
  Log "virtio NIC present: $([bool]$nic)"
}

# Only Server 2025 ships OpenSSH Server preinstalled. Server 2019, Server
# 2022, Windows 10 and Windows 11 have it as a Feature on Demand only, and
# Add-WindowsCapability needs Windows Update or an FoD source - an air-gapped
# rack has neither, and the payload is not on the install media. So: use
# whatever is already present, and fall back to the copy riding along on this
# disk. Nothing below is keyed on the release; it probes for what is there.
if (-not (Get-Service -Name sshd -ErrorAction SilentlyContinue)) {
  $inbox = "$env:SystemRoot\System32\OpenSSH\sshd.exe"
  $zip = Get-ChildItem -Path "$root\openssh" -Filter 'OpenSSH-Win64*.zip' -ErrorAction SilentlyContinue | Select-Object -First 1
  if (Test-Path $inbox) {
    # sshd.exe here means the Server component, not just the inbox client.
    Log "Registering preinstalled OpenSSH Server"
    & "$env:SystemRoot\System32\OpenSSH\install-sshd.ps1" 2>&1 | Out-Null
  } elseif ($zip) {
    Log "Installing OpenSSH from $($zip.Name)"
    $dest = "$env:ProgramFiles\OpenSSH"
    Expand-Archive -Path $zip.FullName -DestinationPath $env:TEMP\openssh -Force

    # Verify provenance on the machine itself before installing anything.
    # The bundled build is Microsoft's own port (PowerShell/Win32-OpenSSH),
    # Authenticode-signed by Microsoft Corporation off their ESRP pipeline.
    # fetch-payload.sh pins a SHA-256, but that only proves we got the bytes
    # we expected - it says nothing about who signed them. Checking the
    # signature here is free, needs no tooling, and fails closed.
    $stage = "$env:TEMP\openssh\OpenSSH-Win64"
    $unsigned = @()
    foreach ($exe in Get-ChildItem -Path $stage -Filter *.exe) {
      $sig = Get-AuthenticodeSignature -FilePath $exe.FullName
      if ($sig.Status -ne 'Valid' -or $sig.SignerCertificate.Subject -notmatch 'O=Microsoft Corporation') {
        $unsigned += "$($exe.Name) [$($sig.Status)] $($sig.SignerCertificate.Subject)"
      }
    }
    if ($unsigned.Count -gt 0) {
      Log "REFUSING to install OpenSSH: not signed by Microsoft"
      foreach ($u in $unsigned) { Log "  $u" }
    } else {
      Log "OpenSSH payload verified: signed by Microsoft Corporation"
      New-Item -ItemType Directory -Force -Path $dest | Out-Null
      Copy-Item -Path "$stage\*" -Destination $dest -Recurse -Force
      & powershell.exe -ExecutionPolicy Bypass -File "$dest\install-sshd.ps1" 2>&1 | Out-Null
      Log "install-sshd exit $LASTEXITCODE"
    }
  } else {
    Log "WARNING: no OpenSSH present and none on the answer disk"
  }
}

if (Get-Service -Name sshd -ErrorAction SilentlyContinue) {
  Set-Service -Name sshd -StartupType Automatic
  Set-Service -Name ssh-agent -StartupType Automatic -ErrorAction SilentlyContinue
  New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' `
    -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22 -ErrorAction SilentlyContinue | Out-Null

  # Make PowerShell the login shell rather than cmd.
  New-ItemProperty -Path 'HKLM:\SOFTWARE\OpenSSH' -Name DefaultShell `
    -Value "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force | Out-Null

  Start-Service sshd
  Log "sshd started"
  # Stock sshd_config ends with `Match Group administrators`, which points
  # AuthorizedKeysFile at administrators_authorized_keys only -- so an
  # administrator's own ~/.ssh/authorized_keys is ignored, and the per-instance
  # keys cloud-init writes there do nothing. Name both files rather than
  # deleting the block: the block is where the baked keys live.
  # Wrapped, because 'Stop' is in force and nothing here is worth the rest of
  # the bootstrap: an empty file reads as $null, and Replace throws on $null.
  try {
    $sshdConf = "$env:ProgramData\ssh\sshd_config"
    if (Test-Path $sshdConf) {
      $want = 'AuthorizedKeysFile .ssh/authorized_keys __PROGRAMDATA__/ssh/administrators_authorized_keys'
      $text = Get-Content -LiteralPath $sshdConf -Raw
      $new = [regex]::Replace($text, '(?m)^[ \t]*#?[ \t]*AuthorizedKeysFile[ \t]+__PROGRAMDATA__/ssh/administrators_authorized_keys[ \t]*(?=\r?$)', $want)
      if ($new -ne $text) {
        Set-Content -LiteralPath $sshdConf -Value $new -Encoding ascii
        Log "sshd_config: AuthorizedKeysFile now names both key files"
        if (Get-Service -Name sshd -ErrorAction SilentlyContinue) { Restart-Service sshd -ErrorAction SilentlyContinue }
      } else {
        Log "WARNING: sshd_config has no administrators_authorized_keys directive to rewrite; per-instance keys may be ignored"
      }
    } else {
      Log "WARNING: no sshd_config; per-instance keys will not be read"
    }
  } catch { Log "WARNING: could not rewrite sshd_config; per-instance keys may be ignored: $_" }
} else {
  Log "WARNING: sshd service not registered; SSH is not configured"
}

# Cloud-init (cloudbase-init). Verified on the machine itself before install:
# the pinned SHA-256 in fetch-payload.sh proves we got the bytes we asked for
# and says nothing about who signed them. Same fail-closed check as OpenSSH.
# Wrapped, because $ErrorActionPreference is 'Stop' for this script: a throw in
# here would otherwise abort the bootstrap, and with it everything after it.
try {
  $msi = "$root\cloudbase\CloudbaseInitSetup_x64.msi"
  if (-not (Test-Path $msi)) {
    Log "WARNING: cloud-init was requested but no MSI is on this media"
  } else {
    $sig = Get-AuthenticodeSignature -FilePath $msi
    if ($sig.Status -ne 'Valid' -or $sig.SignerCertificate.Subject -notmatch 'O=Cloudbase Solutions') {
      Log "REFUSING to install cloud-init: [$($sig.Status)] $($sig.SignerCertificate.Subject)"
    } else {
      Log "cloud-init payload verified: signed by Cloudbase Solutions"
      $msiProc = Start-Process -FilePath 'msiexec.exe' -ArgumentList '/i',"`"$msi`"",'/qn','/norestart','RUN_SERVICE_AS_LOCAL_SYSTEM=1' -Wait -PassThru
      Log "msiexec exit $($msiProc.ExitCode)"
      $cbDir = "$env:ProgramFiles\Cloudbase Solutions\Cloudbase-Init"
      if (-not (Test-Path $cbDir)) { $cbDir = "${env:ProgramFiles(x86)}\Cloudbase Solutions\Cloudbase-Init" }
      if (-not (Test-Path "$cbDir\conf")) {
        Log "WARNING: cloud-init did not install: there is no $cbDir\conf"
      } else {
        # The confs name mtools_path as a fixed directory, because the file they
        # replace is where the installer would have written it. Without mtools
        # a vFAT config drive cannot be read and every clone ends "No metadata
        # service found" -- so say so here, where it is still a build problem.
        $mtools = 'C:\Program Files\Cloudbase Solutions\Cloudbase-Init\bin\'
        if (-not (Test-Path "$cbDir\bin\mlabel.exe") -or "$cbDir\bin\" -ne $mtools) {
          Log "WARNING: cloud-init: the confs set mtools_path=$mtools but cloudbase-init is at $cbDir (mlabel.exe present: $(Test-Path "$cbDir\bin\mlabel.exe")); the config drive will not be read"
        }
        # mtools' own sanity check refuses any FAT volume whose total sector
        # count is not a multiple of its declared sectors-per-track (63) --
        # the exact "mlabel failed with error ... not a multiple of sectors
        # per track" line in cloudbase-init-unattend.log. Our own config
        # drive (cidata.rs) is sized to pass; the control plane's is not ours
        # to size, so every drive cloudbase-init might be pointed at gets a
        # pass on the check. Machine-scoped so a service started at the next
        # boot inherits it -- before the clone's task runs cloudbase-init.
        [Environment]::SetEnvironmentVariable('MTOOLS_SKIP_CHECK', '1', 'Machine')
        Log "cloud-init: MTOOLS_SKIP_CHECK=1 set machine-wide"
        foreach ($conf in "$root\cloudbase\cloudbase-init.conf", "$root\cloudbase\cloudbase-init-unattend.conf") {
          if (Test-Path $conf) {
            Copy-Item -LiteralPath $conf -Destination (Join-Path "$cbDir\conf" (Split-Path -Leaf $conf)) -Force
            Log "cloud-init: installed $(Split-Path -Leaf $conf)"
          } else { Log "WARNING: cloud-init: $conf is missing from the media" }
        }
        # The installer drops an answer file of its own in conf\. It would run
        # instead of ours.
        $stock = "$cbDir\conf\Unattend.xml"
        if (Test-Path $stock) {
          Remove-Item -LiteralPath $stock -Force
          Log "cloud-init: removed the installer's own conf\Unattend.xml"
        }
      }
    }
  }
  # Disabled for the install, so it cannot contend with Setup's own passes.
  # OxideCloudInit puts it back once Setup has finished.
  $cbSvc = Get-Service -Name cloudbase-init -ErrorAction SilentlyContinue
  if ($cbSvc) {
    if ($cbSvc.Status -eq 'Running') { Stop-Service -Name cloudbase-init -Force -ErrorAction SilentlyContinue }
    Set-Service -Name cloudbase-init -StartupType Disabled
    Log "cloud-init: service disabled for the install"
  } else {
    Log "WARNING: no cloudbase-init service; cloud-init will not run"
  }
  New-Item -ItemType Directory -Force -Path 'C:\oxide\log' | Out-Null
} catch { Log "WARNING: cloud-init install failed: $_" }

# The clone-side runner. The sysprep answer file's specialize pass runs it
# once on each clone's first boot, against the unattend conf.
try {
  $runner = 'C:\oxide\cloud-init.ps1'
  New-Item -ItemType Directory -Force -Path (Split-Path -Parent $runner) | Out-Null
  Set-Content -LiteralPath $runner -Encoding ASCII -Value @'
$ErrorActionPreference = 'Continue'
$log = "$env:SystemDrive\oxide-bootstrap.log"
function CLog($m) { "$(Get-Date -Format o)  cloud-init: $m" | Tee-Object -FilePath $log -Append }
# OxideCloudInit is registered disabled on the golden image, so it cannot race
# OxideGeneralize there. Only a clone's specialize pass runs this script, so
# this is where the task is armed.
try {
  Enable-ScheduledTask -TaskName 'OxideCloudInit' -ErrorAction Stop | Out-Null
  CLog "OxideCloudInit enabled for this clone"
} catch { CLog "WARNING: could not enable OxideCloudInit: $_" }
$cb = "$env:ProgramFiles\Cloudbase Solutions\Cloudbase-Init"
if (-not (Test-Path $cb)) { $cb = "${env:ProgramFiles(x86)}\Cloudbase Solutions\Cloudbase-Init" }
$exe = "$cb\Python\Scripts\cloudbase-init.exe"
$conf = "$cb\conf\cloudbase-init-unattend.conf"
$ulog = 'C:\oxide\log\cloudbase-init-unattend.log'
if (-not (Test-Path $exe)) { CLog "no cloudbase-init at $exe; nothing to run"; exit 0 }
# Only this run's lines are searched below, so count what is there already.
$ulogSkip = 0
if (Test-Path -LiteralPath $ulog) { $ulogSkip = @(Get-Content -LiteralPath $ulog -ErrorAction SilentlyContinue).Count }
$code = $null
# The specialize pass may not have picked up the Machine MTOOLS_SKIP_CHECK
# set at install time (services and processes read Machine variables at
# their own next start, not this one's), so set it for this process too --
# same mtools "not a multiple of sectors per track" mlabel failure this
# guards against on the install side.
$env:MTOOLS_SKIP_CHECK = '1'
try {
  $proc = Start-Process -FilePath $exe -ArgumentList "--config-file","`"$conf`"" -Wait -PassThru -ErrorAction Stop
  $code = $proc.ExitCode
} catch { CLog "could not start cloudbase-init: $_" }
CLog "cloudbase-init exited $code"
# cloudbase-init exits 0 when it finds no metadata at all, so "exited 0" alone
# reads as success for a run that did nothing. Its own log says which it was.
# A warning only: the exit code below is unchanged.
try {
  if (Test-Path -LiteralPath $ulog) {
    $missed = Get-Content -LiteralPath $ulog -ErrorAction Stop | Select-Object -Skip $ulogSkip | Select-String -SimpleMatch 'No metadata service found' -Quiet
    if ($missed) { CLog "WARNING: cloudbase-init found no config drive; hostname, keys and user-data were not applied" }
  } else {
    CLog "WARNING: no $ulog to check whether cloudbase-init found a config drive"
  }
} catch { CLog "WARNING: could not read ${ulog}: $_" }
# Exit 1 on SUCCESS, deliberately. This command runs from the sysprep answer
# file's specialize pass with WillReboot=OnRequest, which reads an exit code of
# 1 as "reboot requested" -- and a run that has just changed the computer name
# needs exactly that. Failure is 2. This is the opposite of every other exit
# code in this codebase.
if ($code -eq 0) { exit 1 }
exit 2
'@
  Log "cloud-init: wrote $runner"
} catch { Log "WARNING: could not write the cloud-init runner: $_" }

# OxideCloudInit: at every startup, once Setup has finished, bring the
# cloudbase-init service up -- in keep-my-account mode making the account's
# profile first. Registered in both account modes: a clone's specialize pass
# can set the service to Automatic, but the SCM has already started automatic
# services by then, so without this task the service would first run on the
# clone's second boot.
try {
  $ciDir = "$env:SystemRoot\Setup\Scripts"
  $ciTask = "$ciDir\oxide-cloud-init.ps1"
  New-Item -ItemType Directory -Force -Path $ciDir | Out-Null
  Set-Content -LiteralPath $ciTask -Encoding ASCII -Value @'
$ErrorActionPreference = 'Continue'
$log = "$env:SystemDrive\oxide-bootstrap.log"
function TLog($m) {
  "$(Get-Date -Format o)  cloud-init task: $m" | Tee-Object -FilePath $log -Append
}
# First, before anything that can fail. On the first QEMU clone this task's
# Last Result was 0xC0000005 (-1073741819, an access violation) at the first
# startup after specialize, with nothing logged; run by hand later it was fine.
# powershell.exe died at early boot. This line tells "crashed after starting"
# from "never got this far".
TLog "starting"
# This task never unregisters itself and re-arms nothing: every step below is
# idempotent, so it simply runs at every startup. Generalizing gives each clone
# a new SID, so the profile it makes has to be made again on every clone -- an
# "unregister when done" edit would work on the golden image and silently break
# every machine cloned from it.
# A golden image: before it is generalized there is nothing to do, and it
# shuts down straight after. oxide-generalized.txt is written just before the
# generalize and captured into the image, so it is there only on a clone.
if (-not (Test-Path "$env:SystemDrive\oxide-generalized.txt")) {
  TLog "not generalized yet; nothing to do until this image is cloned"
  exit 0
}
# The task fires at every startup, including boots where Setup is still
# working. Do nothing until it has finished and let the next boot try again.
$setup = Get-ItemProperty -Path 'HKLM:\SYSTEM\Setup' -ErrorAction SilentlyContinue
if ($setup.SystemSetupInProgress -ne 0 -or $setup.OOBEInProgress -ne 0) {
  TLog "Setup still in progress; waiting for the next boot"
  exit 0
}
# Keep-my-account mode. SetUserSSHPublicKeysPlugin writes to the account's
# profile, which it finds through ProfileList\<SID>\ProfileImagePath, and an
# account an answer file created has no profile until someone logs on. Without
# one the plugin raises "User profile not found!" and the instance's keys are
# silently absent. So make it, before the service runs.
$user = 'oxide'
$sid = $null
try {
  $sid = (New-Object System.Security.Principal.NTAccount($user)).Translate([System.Security.Principal.SecurityIdentifier]).Value
} catch { TLog "WARNING: no account named $user to make a profile for: $_" }
if ($sid) {
  $profileKey = "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\ProfileList\$sid"
  $profilePath = (Get-ItemProperty -Path $profileKey -ErrorAction SilentlyContinue).ProfileImagePath
  # C:\Users\TEMP (or TEMP.<something>) is the temporary profile Windows hands
  # out when it cannot load the real one, and it is thrown away at logoff:
  # keys written there vanish. Seen on the first QEMU clone, probably from a
  # console logon on the golden before it was generalized. Not a profile,
  # then -- and the service is not started this boot, so the next one can
  # try again.
  if ($profilePath -match '\\Users\\TEMP(\.[^\\]*)?\\?$') {
    TLog "WARNING: the profile for $user is a temporary one at $profilePath; not starting cloudbase-init this boot, because keys written there are lost"
    exit 0
  }
  if ($profilePath) {
    TLog "profile for $user already exists at $profilePath"
  } else {
    TLog "no profile for $user; making one so cloud-init can write its SSH keys"
    # userenv's CreateProfile makes the ProfileList entry and the profile
    # directory, needs no password, and works from LocalSystem. Logging on as
    # the user to load its profile does not: that is CreateProcessWithLogonW,
    # documented not to work from LocalSystem.
    try {
      Add-Type -Namespace Oxide -Name UserEnv -MemberDefinition '[DllImport("userenv.dll", CharSet = CharSet.Unicode)] public static extern int CreateProfile(string sid, string name, System.Text.StringBuilder path, uint len);' -ErrorAction Stop
      $buf = New-Object System.Text.StringBuilder 260
      $hr = [Oxide.UserEnv]::CreateProfile($sid, $user, $buf, 260)
      TLog ('CreateProfile returned 0x{0:X8}' -f $hr)
    } catch { TLog "CreateProfile failed: $_" }
    $profilePath = (Get-ItemProperty -Path $profileKey -ErrorAction SilentlyContinue).ProfileImagePath
    if ($profilePath) {
      TLog "profile for $user made at $profilePath"
    } else {
      TLog "WARNING: still no profile for $user; the instance's SSH keys will not be written"
    }
  }
}
if (-not (Get-Service -Name cloudbase-init -ErrorAction SilentlyContinue)) {
  TLog "WARNING: no cloudbase-init service; nothing to start"
  exit 0
}
try {
  Set-Service -Name cloudbase-init -StartupType Automatic -ErrorAction Stop
  TLog "cloudbase-init set to start automatically"
} catch { TLog "WARNING: could not set cloudbase-init to Automatic: $_" }
if ((Get-Service -Name cloudbase-init).Status -eq 'Running') {
  TLog "cloudbase-init already running"
} else {
  try {
    Start-Service -Name cloudbase-init -ErrorAction Stop
    TLog "cloudbase-init started"
  } catch { TLog "WARNING: could not start cloudbase-init: $_" }
}
exit 0
'@
  # Wrapped for the same reason OxideGeneralize is: a failed registration must
  # not abort the bootstrap without saying why.
  $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$ciTask`""
  $trigger = New-ScheduledTaskTrigger -AtStartup
  # A minute's delay, and three retries a minute apart. At the first startup
  # after a clone's specialize pass powershell.exe crashed with 0xC0000005
  # before this script logged a line, and a manual run later worked: early
  # boot, not the script. The delay is the fix; the retries are a second line,
  # since nothing here establishes that Task Scheduler counts a crashed
  # process's exit code as a failure to restart on.
  $trigger.Delay = 'PT1M'
  $settings = New-ScheduledTaskSettingsSet -RestartCount 3 -RestartInterval (New-TimeSpan -Minutes 1)
  $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
  Register-ScheduledTask -TaskName 'OxideCloudInit' -Action $action -Trigger $trigger -Settings $settings -Principal $principal -Force | Out-Null
  # Disabled on a golden image. OxideGeneralize is a startup task too and
  # starts alongside this one; it writes oxide-generalized.txt and then runs
  # sysprep, so the marker check alone would let this task make a profile
  # and start the service on the golden image mid-sysprep. The clone-side
  # runner, which only a clone's specialize pass runs, enables it.
  Disable-ScheduledTask -TaskName 'OxideCloudInit' | Out-Null
  Log "cloud-init: OxideCloudInit registered, disabled until a clone's specialize pass enables it"
} catch { Log "WARNING: could not register OxideCloudInit, so cloud-init will not start on its own: $_" }

# Oxide boots the configured boot_disk and does not fall through to another
# disk, so the ESP needs the removable-media fallback path populated or the
# installed system drops to the EFI shell.
try {
  $esp = (Get-Partition | Where-Object { $_.GptType -eq '{c12a7328-f81f-11d2-ba4b-00a0c93ec93b}' } | Select-Object -First 1)
  if ($esp) {
    $letter = 'S'
    $mounted = $false
    if (-not $esp.DriveLetter) {
      $esp | Set-Partition -NewDriveLetter $letter
      $mounted = $true
    } else { $letter = $esp.DriveLetter }
    try {
      $src2 = "${letter}:\EFI\Microsoft\Boot\bootmgfw.efi"
      $dstDir = "${letter}:\EFI\BOOT"
      if (-not (Test-Path $src2)) {
        Log "WARNING: ESP fallback: no bootmgfw.efi at $src2"
      } elseif (Test-Path "$dstDir\BOOTX64.EFI") {
        Log "ESP fallback bootloader: Windows already wrote \EFI\BOOT\BOOTX64.EFI"
      } else {
        New-Item -ItemType Directory -Force -Path $dstDir | Out-Null
        Copy-Item -Path $src2 -Destination "$dstDir\BOOTX64.EFI" -Force
        Log "ESP fallback bootloader installed at \EFI\BOOT\BOOTX64.EFI"
      }
    } finally {
      # An ESP has no drive letter on a normal install. Leaving the one assigned
      # above ships every clone with the ESP visible in Explorer and writable by
      # anything running as admin, so it comes back off even if the copy threw.
      if ($mounted) {
        try {
          Remove-PartitionAccessPath -DiskNumber $esp.DiskNumber -PartitionNumber $esp.PartitionNumber -AccessPath "${letter}:" -ErrorAction Stop
          Log "ESP unmounted from ${letter}:"
        } catch { Log "WARNING: could not unmount ESP from ${letter}: $_" }
      }
    }
  } else { Log "WARNING: no EFI system partition found" }
} catch { Log "WARNING: ESP fallback copy failed: $_" }

Log "Oxide guest bootstrap complete"

# Golden image: generalize after the install finishes, so this disk can be cloned.
$genDir = "$env:SystemRoot\Setup\Scripts"
$gen = "$genDir\oxide-generalize.ps1"
$unattend = "$env:SystemRoot\System32\Sysprep\oxide-unattend.xml"
New-Item -ItemType Directory -Force -Path $genDir | Out-Null
Set-Content -LiteralPath $unattend -Encoding UTF8 -Value @'
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
  <settings pass="specialize">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <ComputerName>*</ComputerName>
      <TimeZone>UTC</TimeZone>
    </component>
    <component name="Microsoft-Windows-TerminalServices-LocalSessionManager" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <fDenyTSConnections>false</fDenyTSConnections>
    </component>
    <component name="Microsoft-Windows-TerminalServices-RDP-WinStationExtensions" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <UserAuthentication>1</UserAuthentication>
    </component>
    <component name="Networking-MPSSVC-Svc" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <FirewallGroups>
        <FirewallGroup wcm:action="add" wcm:keyValue="RemoteDesktop">
          <Active>true</Active>
          <Group>@FirewallAPI.dll,-28752</Group>
          <Profile>all</Profile>
        </FirewallGroup>
      </FirewallGroups>
    </component>
    <component name="Microsoft-Windows-Deployment" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <RunSynchronous>
        <RunSynchronousCommand wcm:action="add">
          <Order>1</Order>
          <Path>cmd.exe /c bcdedit /ems {current} on &amp;&amp; bcdedit /emssettings EMSPORT:1 EMSBAUDRATE:115200 &amp;&amp; bcdedit /bootems {current} on</Path>
          <Description>Enable EMS serial console on com1</Description>
        </RunSynchronousCommand>
        <RunSynchronousCommand wcm:action="add">
          <Order>2</Order>
          <Path>powershell.exe -NoProfile -ExecutionPolicy Bypass -Command &quot;gdr -PSProvider FileSystem|%{$_.Root+&apos;setup\bootstrap.ps1&apos;}|?{Test-Path $_}|select -First 1|%{&amp; $_}&quot;</Path>
          <Description>Oxide guest bootstrap</Description>
        </RunSynchronousCommand>
        <RunSynchronousCommand wcm:action="add">
          <Order>3</Order>
          <Path>powershell.exe -NoProfile -ExecutionPolicy Bypass -File C:\oxide\cloud-init.ps1</Path>
          <Description>Run cloud-init once for this clone</Description>
        </RunSynchronousCommand>
      </RunSynchronous>
    </component>
  </settings>
  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <InputLocale>en-US</InputLocale>
      <SystemLocale>en-US</SystemLocale>
      <UILanguage>en-US</UILanguage>
      <UserLocale>en-US</UserLocale>
    </component>
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <OOBE>
        <HideEULAPage>true</HideEULAPage>
        <HideLocalAccountScreen>true</HideLocalAccountScreen>
        <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
        <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
        <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
        <NetworkLocation>Work</NetworkLocation>
        <ProtectYourPC>3</ProtectYourPC>
      </OOBE>
      <UserAccounts>
        <LocalAccounts>
          <LocalAccount wcm:action="add">
            <Name>oxide</Name>
            <DisplayName>oxide</DisplayName>
            <Group>Administrators</Group>
            <Password>
              <Value>0xide!230xide!23</Value>
              <PlainText>true</PlainText>
            </Password>
          </LocalAccount>
        </LocalAccounts>
      </UserAccounts>
    </component>
  </settings>
</unattend>
'@
# A single-quoted here-string: nothing below is expanded now. It is expanded on the
# machine, on a later boot, by the task registered underneath it.
Set-Content -LiteralPath $gen -Encoding ASCII -Value @'
$ErrorActionPreference = 'Continue'
$log = "$env:SystemDrive\oxide-bootstrap.log"
function GLog($m) {
  "$(Get-Date -Format o)  generalize: $m" | Tee-Object -FilePath $log -Append
}
# Written before sysprep runs, so it is captured into the image. A clone therefore
# finds it and does nothing. Without this every clone would generalize itself and
# shut down on first boot, which is a fleet that turns itself off.
$marker = "$env:SystemDrive\oxide-generalized.txt"
if (Test-Path $marker) {
  GLog "already generalized; this is a clone, nothing to do"
  Unregister-ScheduledTask -TaskName 'OxideGeneralize' -Confirm:$false -ErrorAction SilentlyContinue
  exit 0
}
# The task fires at every startup, including boots where Setup is still working. Do
# nothing until it has finished and let the next boot try again.
$setup = Get-ItemProperty -Path 'HKLM:\SYSTEM\Setup' -ErrorAction SilentlyContinue
if ($setup.SystemSetupInProgress -ne 0 -or $setup.OOBEInProgress -ne 0) {
  GLog "Setup still in progress; waiting for the next boot"
  exit 0
}
$unattend = "$env:SystemRoot\System32\Sysprep\oxide-unattend.xml"
if (-not (Test-Path $unattend)) {
  GLog "WARNING: $unattend is missing. Sysprep would fall back to the cached answer"
  GLog "file, whose password Windows has already deleted, and the clone would stop at"
  GLog "the out-of-box wizard. Refusing to generalize."
  exit 1
}
GLog "install finished; generalizing for cloning with $unattend"
Set-Content -LiteralPath $marker -Value (Get-Date -Format o)
Unregister-ScheduledTask -TaskName 'OxideGeneralize' -Confirm:$false -ErrorAction SilentlyContinue
# Start-Process -Wait -PassThru, NOT `& sysprep.exe`. $LASTEXITCODE is populated only
# by console-subsystem programs, and sysprep.exe leaves it unset here, so `$code -eq 0`
# compared $null against 0, was False, and took the failure path on a sysprep that had
# SUCCEEDED. That path deletes the marker and re-arms the task, so the machine
# generalized and shut itself down again on every boot. Seen on a rack over three
# cycles, each logging "sysprep FAILED with exit code " with no number after it -- the
# empty exit code is the tell.
$code = $null
try {
  $proc = Start-Process -FilePath "$env:SystemRoot\System32\Sysprep\sysprep.exe" -ArgumentList '/generalize','/oobe','/shutdown',"/unattend:$unattend" -Wait -PassThru -ErrorAction Stop
  $code = $proc.ExitCode
} catch {
  GLog "could not start sysprep: $_"
}
# Branch on the exit code, NOT on reaching this line. sysprep /shutdown returns
# straight away and Windows powers off a moment later, so everything below runs on
# success too unless it is guarded.
if ($code -eq 0) {
  GLog "sysprep accepted; the machine is shutting down. Snapshot it once it stops."
  exit 0
}
if ($null -eq $code) {
  # Unknown is not failure, and the two are not symmetric. The recovery below deletes
  # the marker and re-arms the task, so treating "no exit code" as a failure is what
  # turns one successful generalize into a machine that generalizes itself forever.
  # A machine needing one manual retry is a far better wrong answer than a fleet that
  # will not stay on. The task is already unregistered above, so exiting here leaves
  # the machine armed for nothing.
  GLog "sysprep returned no exit code, so whether it worked is unknown. Leaving the"
  GLog "marker in place and NOT re-arming the task: booting to OOBE means it worked."
  GLog "If it did not, see C:\Windows\System32\Sysprep\Panther and sysprep by hand."
  exit 0
}
GLog "sysprep FAILED with exit code $code; see C:\Windows\System32\Sysprep\Panther"
# Only now: undo the marker and put the task back, so a real failure retries rather
# than leaving a machine that looks generalized and is not.
Remove-Item -LiteralPath $marker -Force -ErrorAction SilentlyContinue
$a = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`""
$t = New-ScheduledTaskTrigger -AtStartup
$p = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
Register-ScheduledTask -TaskName 'OxideGeneralize' -Action $a -Trigger $t -Principal $p -Force | Out-Null
'@
# Wrapped, because $ErrorActionPreference is 'Stop' for this script: a failure to
# register the task would otherwise abort the bootstrap without saying why, and the
# machine would come up looking fine and never generalize.
try {
  $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$gen`""
  $trigger = New-ScheduledTaskTrigger -AtStartup
  $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
  Register-ScheduledTask -TaskName 'OxideGeneralize' -Action $action -Trigger $trigger -Principal $principal -Force | Out-Null
  Log "golden image: OxideGeneralize registered; the machine will sysprep and shut down once Setup finishes"
} catch { Log "WARNING: could not register OxideGeneralize, so this image will NOT be generalized: $_" }
