# Generated by the Oxide Windows image builder. Runs as SYSTEM in the
# specialize pass, before any user logs on.
$ErrorActionPreference = 'Stop'
$src = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = (Split-Path -Parent $src).TrimEnd('\')

# Log to the installer media as well as the system drive. The media is the only
# copy anyone can read without getting into the guest: on the rack the console is
# serial-only, and off the rack a Windows NTFS volume is awkward to read (macOS
# 26 dropped NTFS support entirely). Detach the installer disk afterwards and the
# log is right there on a volume every OS can mount.
$log = "$env:SystemDrive\oxide-bootstrap.log"
$mediaLog = "$root\oxide-bootstrap.log"
function Log($m) {
  $line = "$(Get-Date -Format o)  $m"
  $line | Tee-Object -FilePath $log -Append
  # Best effort: the media may be read-only or already gone.
  try { Add-Content -LiteralPath $mediaLog -Value $line -ErrorAction Stop } catch {}
}

Log "Oxide guest bootstrap starting"

# Belt and braces: the DriverPaths in the unattend should already have
# handled these, but a driver missed there leaves the guest unreachable.
if (Test-Path "$root\drivers") {
  Log "Installing drivers from $root\drivers"
  $out = & pnputil.exe /add-driver "$root\drivers\*.inf" /subdirs /install 2>&1
  Log "pnputil exit $LASTEXITCODE"
  # Keep the output when it fails. A bare exit code told us nothing, and
  # "no NIC" is expensive to diagnose after the fact.
  if ($LASTEXITCODE -ne 0) { $out | ForEach-Object { Log "  pnputil: $_" } }
  $nic = Get-PnpDevice -Class Net -ErrorAction SilentlyContinue | Where-Object { $_.FriendlyName -match 'VirtIO|Red Hat' }
  Log "virtio NIC present: $([bool]$nic)"
}

# Server 2025 ships OpenSSH Server preinstalled. Server 2022 and Windows 11
# have it only as a Feature on Demand, and Add-WindowsCapability needs
# Windows Update or an FoD source - an air-gapped rack has neither, and the
# payload is not on the install media. So: use whatever is already present,
# and fall back to the copy riding along on this disk.
if (-not (Get-Service -Name sshd -ErrorAction SilentlyContinue)) {
  $inbox = "$env:SystemRoot\System32\OpenSSH\sshd.exe"
  $zip = Get-ChildItem -Path "$root\openssh" -Filter 'OpenSSH-Win64*.zip' -ErrorAction SilentlyContinue | Select-Object -First 1
  if (Test-Path $inbox) {
    # sshd.exe here means the Server component, not just the inbox client.
    Log "Registering preinstalled OpenSSH Server"
    & "$env:SystemRoot\System32\OpenSSH\install-sshd.ps1" 2>&1 | Out-Null
  } elseif ($zip) {
    Log "Installing OpenSSH from $($zip.Name)"
    $dest = "$env:ProgramFiles\OpenSSH"
    Expand-Archive -Path $zip.FullName -DestinationPath $env:TEMP\openssh -Force

    # Verify provenance on the machine itself before installing anything.
    # The bundled build is Microsoft's own port (PowerShell/Win32-OpenSSH),
    # Authenticode-signed by Microsoft Corporation off their ESRP pipeline.
    # fetch-payload.sh pins a SHA-256, but that only proves we got the bytes
    # we expected - it says nothing about who signed them. Checking the
    # signature here is free, needs no tooling, and fails closed.
    $stage = "$env:TEMP\openssh\OpenSSH-Win64"
    $unsigned = @()
    foreach ($exe in Get-ChildItem -Path $stage -Filter *.exe) {
      $sig = Get-AuthenticodeSignature -FilePath $exe.FullName
      if ($sig.Status -ne 'Valid' -or $sig.SignerCertificate.Subject -notmatch 'O=Microsoft Corporation') {
        $unsigned += "$($exe.Name) [$($sig.Status)] $($sig.SignerCertificate.Subject)"
      }
    }
    if ($unsigned.Count -gt 0) {
      Log "REFUSING to install OpenSSH: not signed by Microsoft"
      foreach ($u in $unsigned) { Log "  $u" }
    } else {
      Log "OpenSSH payload verified: signed by Microsoft Corporation"
      New-Item -ItemType Directory -Force -Path $dest | Out-Null
      Copy-Item -Path "$stage\*" -Destination $dest -Recurse -Force
      & powershell.exe -ExecutionPolicy Bypass -File "$dest\install-sshd.ps1" 2>&1 | Out-Null
      Log "install-sshd exit $LASTEXITCODE"
    }
  } else {
    Log "WARNING: no OpenSSH present and none on the answer disk"
  }
}

if (Get-Service -Name sshd -ErrorAction SilentlyContinue) {
  Set-Service -Name sshd -StartupType Automatic
  Set-Service -Name ssh-agent -StartupType Automatic -ErrorAction SilentlyContinue
  New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' `
    -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22 -ErrorAction SilentlyContinue | Out-Null

  # Make PowerShell the login shell rather than cmd.
  New-ItemProperty -Path 'HKLM:\SOFTWARE\OpenSSH' -Name DefaultShell `
    -Value "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force | Out-Null

  Start-Service sshd
  Log "sshd started"
} else {
  Log "WARNING: sshd service not registered; SSH is not configured"
}

# See docs/windows-install-status.md: Oxide boots the configured boot_disk and
# does not fall through, so the ESP needs the fallback path populated.
try {
  $esp = (Get-Partition | Where-Object { $_.GptType -eq '{c12a7328-f81f-11d2-ba4b-00a0c93ec93b}' } | Select-Object -First 1)
  if ($esp) {
    $letter = 'S'
    if (-not $esp.DriveLetter) { $esp | Set-Partition -NewDriveLetter $letter } else { $letter = $esp.DriveLetter }
    $src2 = "${letter}:\EFI\Microsoft\Boot\bootmgfw.efi"
    $dstDir = "${letter}:\EFI\BOOT"
    if ((Test-Path $src2) -and -not (Test-Path "$dstDir\BOOTX64.EFI")) {
      New-Item -ItemType Directory -Force -Path $dstDir | Out-Null
      Copy-Item -Path $src2 -Destination "$dstDir\BOOTX64.EFI" -Force
      Log "ESP fallback bootloader installed at \EFI\BOOT\BOOTX64.EFI"
    } else {
      Log "ESP fallback bootloader: already present or bootmgfw missing"
    }
  } else { Log "WARNING: no EFI system partition found" }
} catch { Log "WARNING: ESP fallback copy failed: $_" }

Log "Oxide guest bootstrap complete"

# Golden image: generalize after the install finishes, so this disk can be cloned.
$genDir = "$env:SystemRoot\Setup\Scripts"
$gen = "$genDir\oxide-generalize.ps1"
$unattend = "$env:SystemRoot\System32\Sysprep\oxide-unattend.xml"
New-Item -ItemType Directory -Force -Path $genDir | Out-Null
Set-Content -LiteralPath $unattend -Encoding UTF8 -Value @'
<?xml version="1.0" encoding="utf-8"?>
<unattend xmlns="urn:schemas-microsoft-com:unattend" xmlns:wcm="http://schemas.microsoft.com/WMIConfig/2002/State">
  <settings pass="specialize">
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <ComputerName>*</ComputerName>
      <TimeZone>UTC</TimeZone>
    </component>
    <component name="Microsoft-Windows-TerminalServices-LocalSessionManager" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <fDenyTSConnections>false</fDenyTSConnections>
    </component>
    <component name="Microsoft-Windows-TerminalServices-RDP-WinStationExtensions" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <UserAuthentication>1</UserAuthentication>
    </component>
    <component name="Networking-MPSSVC-Svc" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <FirewallGroups>
        <FirewallGroup wcm:action="add" wcm:keyValue="RemoteDesktop">
          <Active>true</Active>
          <Group>@FirewallAPI.dll,-28752</Group>
          <Profile>all</Profile>
        </FirewallGroup>
      </FirewallGroups>
    </component>
    <component name="Microsoft-Windows-Deployment" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <RunSynchronous>
        <RunSynchronousCommand wcm:action="add">
          <Order>1</Order>
          <Path>cmd.exe /c bcdedit /ems {current} on &amp;&amp; bcdedit /emssettings EMSPORT:1 EMSBAUDRATE:115200 &amp;&amp; bcdedit /bootems {current} on</Path>
          <Description>Enable EMS serial console on com1</Description>
        </RunSynchronousCommand>
        <RunSynchronousCommand wcm:action="add">
          <Order>2</Order>
          <Path>powershell.exe -NoProfile -ExecutionPolicy Bypass -Command &quot;gdr -PSProvider FileSystem|%{$_.Root+&apos;setup\bootstrap.ps1&apos;}|?{Test-Path $_}|select -First 1|%{&amp; $_}&quot;</Path>
          <Description>Oxide guest bootstrap</Description>
        </RunSynchronousCommand>
      </RunSynchronous>
    </component>
  </settings>
  <settings pass="oobeSystem">
    <component name="Microsoft-Windows-International-Core" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <InputLocale>en-US</InputLocale>
      <SystemLocale>en-US</SystemLocale>
      <UILanguage>en-US</UILanguage>
      <UserLocale>en-US</UserLocale>
    </component>
    <component name="Microsoft-Windows-Shell-Setup" processorArchitecture="amd64" publicKeyToken="31bf3856ad364e35" language="neutral" versionScope="nonSxS">
      <OOBE>
        <HideEULAPage>true</HideEULAPage>
        <HideLocalAccountScreen>true</HideLocalAccountScreen>
        <HideOEMRegistrationScreen>true</HideOEMRegistrationScreen>
        <HideOnlineAccountScreens>true</HideOnlineAccountScreens>
        <HideWirelessSetupInOOBE>true</HideWirelessSetupInOOBE>
        <NetworkLocation>Work</NetworkLocation>
        <ProtectYourPC>3</ProtectYourPC>
      </OOBE>
      <UserAccounts>
        <LocalAccounts>
          <LocalAccount wcm:action="add">
            <Name>oxide</Name>
            <DisplayName>oxide</DisplayName>
            <Group>Administrators</Group>
            <Password>
              <Value>0xide!230xide!23</Value>
              <PlainText>true</PlainText>
            </Password>
          </LocalAccount>
        </LocalAccounts>
      </UserAccounts>
    </component>
  </settings>
</unattend>
'@
# A single-quoted here-string: nothing below is expanded now. It is expanded on the
# machine, on a later boot, by the task registered underneath it.
Set-Content -LiteralPath $gen -Encoding ASCII -Value @'
$ErrorActionPreference = 'Continue'
$log = "$env:SystemDrive\oxide-bootstrap.log"
function GLog($m) {
  "$(Get-Date -Format o)  generalize: $m" | Tee-Object -FilePath $log -Append
}
# Written before sysprep runs, so it is captured into the image. A clone therefore
# finds it and does nothing. Without this every clone would generalize itself and
# shut down on first boot, which is a fleet that turns itself off.
$marker = "$env:SystemDrive\oxide-generalized.txt"
if (Test-Path $marker) {
  GLog "already generalized; this is a clone, nothing to do"
  Unregister-ScheduledTask -TaskName 'OxideGeneralize' -Confirm:$false -ErrorAction SilentlyContinue
  exit 0
}
# The task fires at every startup, including boots where Setup is still working. Do
# nothing until it has finished and let the next boot try again.
$setup = Get-ItemProperty -Path 'HKLM:\SYSTEM\Setup' -ErrorAction SilentlyContinue
if ($setup.SystemSetupInProgress -ne 0 -or $setup.OOBEInProgress -ne 0) {
  GLog "Setup still in progress; waiting for the next boot"
  exit 0
}
$unattend = "$env:SystemRoot\System32\Sysprep\oxide-unattend.xml"
if (-not (Test-Path $unattend)) {
  GLog "WARNING: $unattend is missing. Sysprep would fall back to the cached answer"
  GLog "file, whose password Windows has already deleted, and the clone would stop at"
  GLog "the out-of-box wizard. Refusing to generalize."
  exit 1
}
GLog "install finished; generalizing for cloning with $unattend"
Set-Content -LiteralPath $marker -Value (Get-Date -Format o)
Unregister-ScheduledTask -TaskName 'OxideGeneralize' -Confirm:$false -ErrorAction SilentlyContinue
& "$env:SystemRoot\System32\Sysprep\sysprep.exe" /generalize /oobe /shutdown /unattend:"$unattend"
$code = $LASTEXITCODE
# Branch on the exit code, NOT on reaching this line. sysprep /shutdown returns
# straight away and Windows powers off a moment later, so everything below runs on
# success too unless it is guarded. Getting that wrong produced an infinite loop on a
# rack: sysprep succeeded, the lines below removed the marker and put the task back,
# and so every subsequent boot generalized the machine and shut it down again.
if ($code -eq 0) {
  GLog "sysprep accepted; the machine is shutting down. Snapshot it once it stops."
  exit 0
}
GLog "sysprep FAILED with exit code $code; see C:\Windows\System32\Sysprep\Panther"
# Only now: undo the marker and put the task back, so a real failure retries rather
# than leaving a machine that looks generalized and is not.
Remove-Item -LiteralPath $marker -Force -ErrorAction SilentlyContinue
$a = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`""
$t = New-ScheduledTaskTrigger -AtStartup
$p = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
Register-ScheduledTask -TaskName 'OxideGeneralize' -Action $a -Trigger $t -Principal $p -Force | Out-Null
'@
# Wrapped, because $ErrorActionPreference is 'Stop' for this script: a failure to
# register the task would otherwise abort the bootstrap without saying why, and the
# machine would come up looking fine and never generalize.
try {
  $action = New-ScheduledTaskAction -Execute 'powershell.exe' -Argument "-NoProfile -ExecutionPolicy Bypass -File `"$gen`""
  $trigger = New-ScheduledTaskTrigger -AtStartup
  $principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
  Register-ScheduledTask -TaskName 'OxideGeneralize' -Action $action -Trigger $trigger -Principal $principal -Force | Out-Null
  Log "golden image: OxideGeneralize registered; the machine will sysprep and shut down once Setup finishes"
} catch { Log "WARNING: could not register OxideGeneralize, so this image will NOT be generalized: $_" }
