# Generated by the Oxide Windows image builder. Runs as SYSTEM in the
# specialize pass, before any user logs on.
$ErrorActionPreference = 'Stop'
$src = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = (Split-Path -Parent $src).TrimEnd('\')

# Log to the installer media as well as the system drive. The media is the only
# copy anyone can read without getting into the guest: on the rack the console is
# serial-only, and off the rack the system drive is NTFS, which needs support the
# reading machine may not have - macOS mounts it read-only at best. Detach the
# installer disk afterwards and the log is on exFAT, which every OS mounts.
$log = "$env:SystemDrive\oxide-bootstrap.log"
$mediaLog = "$root\oxide-bootstrap.log"
function Log($m) {
  $line = "$(Get-Date -Format o)  $m"
  $line | Tee-Object -FilePath $log -Append
  # Best effort: the media may be read-only or already gone.
  try { Add-Content -LiteralPath $mediaLog -Value $line -ErrorAction Stop } catch {}
}

Log "Oxide guest bootstrap starting"

# Belt and suspenders: the DriverPaths in the unattend should already have
# handled these, but a driver missed there leaves the guest unreachable.
if (Test-Path "$root\drivers") {
  Log "Installing drivers from $root\drivers"
  $out = & pnputil.exe /add-driver "$root\drivers\*.inf" /subdirs /install 2>&1
  Log "pnputil exit $LASTEXITCODE"
  # Keep the output when it fails. A bare exit code told us nothing, and
  # "no NIC" is expensive to diagnose after the fact.
  if ($LASTEXITCODE -ne 0) { $out | ForEach-Object { Log "  pnputil: $_" } }
  $nic = Get-PnpDevice -Class Net -ErrorAction SilentlyContinue | Where-Object { $_.FriendlyName -match 'VirtIO|Red Hat' }
  Log "virtio NIC present: $([bool]$nic)"
}

# Oxide boots the configured boot_disk and does not fall through to another
# disk, so the ESP needs the removable-media fallback path populated or the
# installed system drops to the EFI shell.
try {
  $esp = (Get-Partition | Where-Object { $_.GptType -eq '{c12a7328-f81f-11d2-ba4b-00a0c93ec93b}' } | Select-Object -First 1)
  if ($esp) {
    $letter = 'S'
    if (-not $esp.DriveLetter) { $esp | Set-Partition -NewDriveLetter $letter } else { $letter = $esp.DriveLetter }
    $src2 = "${letter}:\EFI\Microsoft\Boot\bootmgfw.efi"
    $dstDir = "${letter}:\EFI\BOOT"
    if (-not (Test-Path $src2)) {
      Log "WARNING: ESP fallback: no bootmgfw.efi at $src2"
    } elseif (Test-Path "$dstDir\BOOTX64.EFI") {
      Log "ESP fallback bootloader: Windows already wrote \EFI\BOOT\BOOTX64.EFI"
    } else {
      New-Item -ItemType Directory -Force -Path $dstDir | Out-Null
      Copy-Item -Path $src2 -Destination "$dstDir\BOOTX64.EFI" -Force
      Log "ESP fallback bootloader installed at \EFI\BOOT\BOOTX64.EFI"
    }
  } else { Log "WARNING: no EFI system partition found" }
} catch { Log "WARNING: ESP fallback copy failed: $_" }

Log "Oxide guest bootstrap complete"
