# Generated by the Oxide Windows image builder. Runs as SYSTEM in the
# specialize pass, before any user logs on.
$ErrorActionPreference = 'Stop'
$src = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = (Split-Path -Parent $src).TrimEnd('\')

# Log to the installer media as well as the system drive. The media is the only
# copy anyone can read without getting into the guest: on the rack the console is
# serial-only, and off the rack the system drive is NTFS, which needs support the
# reading machine may not have - macOS mounts it read-only at best. Detach the
# installer disk afterwards and the log is on exFAT, which every OS mounts.
$log = "$env:SystemDrive\oxide-bootstrap.log"
$mediaLog = "$root\oxide-bootstrap.log"
function Log($m) {
  $line = "$(Get-Date -Format o)  $m"
  $line | Tee-Object -FilePath $log -Append
  # Best effort: the media may be read-only or already gone.
  try { Add-Content -LiteralPath $mediaLog -Value $line -ErrorAction Stop } catch {}
}

Log "Oxide guest bootstrap starting"

# Belt and suspenders: the DriverPaths in the unattend should already have
# handled these, but a driver missed there leaves the guest unreachable.
if (Test-Path "$root\drivers") {
  Log "Installing drivers from $root\drivers"
  $out = & pnputil.exe /add-driver "$root\drivers\*.inf" /subdirs /install 2>&1
  Log "pnputil exit $LASTEXITCODE"
  # Keep the output when it fails. A bare exit code told us nothing, and
  # "no NIC" is expensive to diagnose after the fact.
  if ($LASTEXITCODE -ne 0) { $out | ForEach-Object { Log "  pnputil: $_" } }
  $nic = Get-PnpDevice -Class Net -ErrorAction SilentlyContinue | Where-Object { $_.FriendlyName -match 'VirtIO|Red Hat' }
  Log "virtio NIC present: $([bool]$nic)"
}

# Only Server 2025 ships OpenSSH Server preinstalled. Server 2019, Server
# 2022, Windows 10 and Windows 11 have it as a Feature on Demand only, and
# Add-WindowsCapability needs Windows Update or an FoD source - an air-gapped
# rack has neither, and the payload is not on the install media. So: use
# whatever is already present, and fall back to the copy riding along on this
# disk. Nothing below is keyed on the release; it probes for what is there.
if (-not (Get-Service -Name sshd -ErrorAction SilentlyContinue)) {
  $inbox = "$env:SystemRoot\System32\OpenSSH\sshd.exe"
  $zip = Get-ChildItem -Path "$root\openssh" -Filter 'OpenSSH-Win64*.zip' -ErrorAction SilentlyContinue | Select-Object -First 1
  if (Test-Path $inbox) {
    # sshd.exe here means the Server component, not just the inbox client.
    Log "Registering preinstalled OpenSSH Server"
    & "$env:SystemRoot\System32\OpenSSH\install-sshd.ps1" 2>&1 | Out-Null
  } elseif ($zip) {
    Log "Installing OpenSSH from $($zip.Name)"
    $dest = "$env:ProgramFiles\OpenSSH"
    Expand-Archive -Path $zip.FullName -DestinationPath $env:TEMP\openssh -Force

    # Verify provenance on the machine itself before installing anything.
    # The bundled build is Microsoft's own port (PowerShell/Win32-OpenSSH),
    # Authenticode-signed by Microsoft Corporation off their ESRP pipeline.
    # fetch-payload.sh pins a SHA-256, but that only proves we got the bytes
    # we expected - it says nothing about who signed them. Checking the
    # signature here is free, needs no tooling, and fails closed.
    $stage = "$env:TEMP\openssh\OpenSSH-Win64"
    $unsigned = @()
    foreach ($exe in Get-ChildItem -Path $stage -Filter *.exe) {
      $sig = Get-AuthenticodeSignature -FilePath $exe.FullName
      if ($sig.Status -ne 'Valid' -or $sig.SignerCertificate.Subject -notmatch 'O=Microsoft Corporation') {
        $unsigned += "$($exe.Name) [$($sig.Status)] $($sig.SignerCertificate.Subject)"
      }
    }
    if ($unsigned.Count -gt 0) {
      Log "REFUSING to install OpenSSH: not signed by Microsoft"
      foreach ($u in $unsigned) { Log "  $u" }
    } else {
      Log "OpenSSH payload verified: signed by Microsoft Corporation"
      New-Item -ItemType Directory -Force -Path $dest | Out-Null
      Copy-Item -Path "$stage\*" -Destination $dest -Recurse -Force
      & powershell.exe -ExecutionPolicy Bypass -File "$dest\install-sshd.ps1" 2>&1 | Out-Null
      Log "install-sshd exit $LASTEXITCODE"
    }
  } else {
    Log "WARNING: no OpenSSH present and none on the answer disk"
  }
}

if (Get-Service -Name sshd -ErrorAction SilentlyContinue) {
  Set-Service -Name sshd -StartupType Automatic
  Set-Service -Name ssh-agent -StartupType Automatic -ErrorAction SilentlyContinue
  New-NetFirewallRule -Name 'OpenSSH-Server-In-TCP' -DisplayName 'OpenSSH Server (sshd)' `
    -Enabled True -Direction Inbound -Protocol TCP -Action Allow -LocalPort 22 -ErrorAction SilentlyContinue | Out-Null

  # Make PowerShell the login shell rather than cmd.
  New-ItemProperty -Path 'HKLM:\SOFTWARE\OpenSSH' -Name DefaultShell `
    -Value "$env:SystemRoot\System32\WindowsPowerShell\v1.0\powershell.exe" -PropertyType String -Force | Out-Null

  # sshd ignores this file unless Administrators and SYSTEM are the only
  # principals with access, so the inherited ACL has to go.
  $akFile = "$env:ProgramData\ssh\administrators_authorized_keys"
  New-Item -ItemType Directory -Force -Path "$env:ProgramData\ssh" | Out-Null
  $keys = @(
    'ssh-ed25519 AAAAC3Nz key@host'
  )
  Set-Content -Path $akFile -Value $keys -Encoding ascii
  $acl = Get-Acl $akFile
  $acl.SetAccessRuleProtection($true, $false)
  $acl.Access | ForEach-Object { $acl.RemoveAccessRule($_) | Out-Null }
  foreach ($who in 'BUILTIN\Administrators', 'NT AUTHORITY\SYSTEM') {
    $acl.AddAccessRule((New-Object System.Security.AccessControl.FileSystemAccessRule(
      $who, 'FullControl', 'None', 'None', 'Allow'))) | Out-Null
  }
  Set-Acl -Path $akFile -AclObject $acl
  Log "Wrote $($keys.Count) authorized key(s)"
  Start-Service sshd
  Log "sshd started"
} else {
  Log "WARNING: sshd service not registered; SSH is not configured"
}

# Oxide boots the configured boot_disk and does not fall through to another
# disk, so the ESP needs the removable-media fallback path populated or the
# installed system drops to the EFI shell.
try {
  $esp = (Get-Partition | Where-Object { $_.GptType -eq '{c12a7328-f81f-11d2-ba4b-00a0c93ec93b}' } | Select-Object -First 1)
  if ($esp) {
    $letter = 'S'
    if (-not $esp.DriveLetter) { $esp | Set-Partition -NewDriveLetter $letter } else { $letter = $esp.DriveLetter }
    $src2 = "${letter}:\EFI\Microsoft\Boot\bootmgfw.efi"
    $dstDir = "${letter}:\EFI\BOOT"
    if (-not (Test-Path $src2)) {
      Log "WARNING: ESP fallback: no bootmgfw.efi at $src2"
    } elseif (Test-Path "$dstDir\BOOTX64.EFI") {
      Log "ESP fallback bootloader: Windows already wrote \EFI\BOOT\BOOTX64.EFI"
    } else {
      New-Item -ItemType Directory -Force -Path $dstDir | Out-Null
      Copy-Item -Path $src2 -Destination "$dstDir\BOOTX64.EFI" -Force
      Log "ESP fallback bootloader installed at \EFI\BOOT\BOOTX64.EFI"
    }
  } else { Log "WARNING: no EFI system partition found" }
} catch { Log "WARNING: ESP fallback copy failed: $_" }

Log "Oxide guest bootstrap complete"
